# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# What the Assignment stage is allowed to do.
class AssignmentParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AssignmentParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAssignmentParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AssignmentParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The implementation, by the name it is registered under.
    # AssignmentParams
    def Assigner(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # How many launchers the assignment activates. Per chip.
    # AssignmentParams
    def LauncherTarget(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def AssignmentParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    AssignmentParamsStart(builder)

def AssignmentParamsAddAssigner(builder: flatbuffers.Builder, assigner: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(assigner), 0)

def AddAssigner(builder: flatbuffers.Builder, assigner: int):
    AssignmentParamsAddAssigner(builder, assigner)

def AssignmentParamsAddLauncherTarget(builder: flatbuffers.Builder, launcherTarget: int):
    builder.PrependUint32Slot(1, launcherTarget, 0)

def AddLauncherTarget(builder: flatbuffers.Builder, launcherTarget: int):
    AssignmentParamsAddLauncherTarget(builder, launcherTarget)

def AssignmentParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return AssignmentParamsEnd(builder)


class AssignmentParamsT(object):

    # AssignmentParamsT
    def __init__(
        self,
        assigner = None,
        launcherTarget = 0,
    ):
        self.assigner = assigner  # type: Optional[str]
        self.launcherTarget = launcherTarget  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        assignmentParams = AssignmentParams()
        assignmentParams.Init(buf, pos)
        return cls.InitFromObj(assignmentParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, assignmentParams):
        x = AssignmentParamsT()
        x._UnPack(assignmentParams)
        return x

    # AssignmentParamsT
    def _UnPack(self, assignmentParams):
        if assignmentParams is None:
            return
        self.assigner = assignmentParams.Assigner()
        if self.assigner is not None:
            self.assigner = self.assigner.decode('utf-8')
        self.launcherTarget = assignmentParams.LauncherTarget()

    # AssignmentParamsT
    def Pack(self, builder):
        if self.assigner is not None:
            assigner = builder.CreateString(self.assigner)
        AssignmentParamsStart(builder)
        if self.assigner is not None:
            AssignmentParamsAddAssigner(builder, assigner)
        AssignmentParamsAddLauncherTarget(builder, self.launcherTarget)
        assignmentParams = AssignmentParamsEnd(builder)
        return assignmentParams
