# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# One rule that pairs the two ports a wire crosses a component between.
# Each side is a regular expression with exactly one capture group, and two
# ports pair when they belong to one component and their captures are equal.
#
# The pairing is declared rather than measured. Opposite orientation and
# shortest distance do pick the right two ports on the benchmark chips, but
# they are a property of the artwork and not a statement of intent, and
# nothing checked that the two agreed.
class BridgeRule(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BridgeRule()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBridgeRule(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BridgeRule
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BridgeRule
    def First(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BridgeRule
    def Second(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def BridgeRuleStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    BridgeRuleStart(builder)

def BridgeRuleAddFirst(builder: flatbuffers.Builder, first: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(first), 0)

def AddFirst(builder: flatbuffers.Builder, first: int):
    BridgeRuleAddFirst(builder, first)

def BridgeRuleAddSecond(builder: flatbuffers.Builder, second: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(second), 0)

def AddSecond(builder: flatbuffers.Builder, second: int):
    BridgeRuleAddSecond(builder, second)

def BridgeRuleEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BridgeRuleEnd(builder)


class BridgeRuleT(object):

    # BridgeRuleT
    def __init__(
        self,
        first = None,
        second = None,
    ):
        self.first = first  # type: Optional[str]
        self.second = second  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bridgeRule = BridgeRule()
        bridgeRule.Init(buf, pos)
        return cls.InitFromObj(bridgeRule)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, bridgeRule):
        x = BridgeRuleT()
        x._UnPack(bridgeRule)
        return x

    # BridgeRuleT
    def _UnPack(self, bridgeRule):
        if bridgeRule is None:
            return
        self.first = bridgeRule.First()
        if self.first is not None:
            self.first = self.first.decode('utf-8')
        self.second = bridgeRule.Second()
        if self.second is not None:
            self.second = self.second.decode('utf-8')

    # BridgeRuleT
    def Pack(self, builder):
        if self.first is not None:
            first = builder.CreateString(self.first)
        if self.second is not None:
            second = builder.CreateString(self.second)
        BridgeRuleStart(builder)
        if self.first is not None:
            BridgeRuleAddFirst(builder, first)
        if self.second is not None:
            BridgeRuleAddSecond(builder, second)
        bridgeRule = BridgeRuleEnd(builder)
        return bridgeRule
