# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# What the Capacity stage is allowed to do.
class CapacityParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CapacityParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCapacityParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CapacityParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The implementation, by the name it is registered under.
    # CapacityParams
    def Planner(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # A place on the medial axis is a bottleneck only where the free radius
    # around it is below this many wire pitches, a pitch being one wire
    # spacing plus one obstacle spacing.
    #
    # The prototype used a fixed count of grid cells here, which is not a
    # length: the same literal admitted a radius of 235 layout units on the
    # 4-qubit grid and 484 on the 9-qubit one, purely because the two grids
    # have different cell sizes. The default below is the middle of that
    # range as a physical distance, and reproduces the prototype's own
    # bottleneck count on both.
    # CapacityParams
    def BottleneckClearance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 1.5

def CapacityParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    CapacityParamsStart(builder)

def CapacityParamsAddPlanner(builder: flatbuffers.Builder, planner: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(planner), 0)

def AddPlanner(builder: flatbuffers.Builder, planner: int):
    CapacityParamsAddPlanner(builder, planner)

def CapacityParamsAddBottleneckClearance(builder: flatbuffers.Builder, bottleneckClearance: float):
    builder.PrependFloat64Slot(1, bottleneckClearance, 1.5)

def AddBottleneckClearance(builder: flatbuffers.Builder, bottleneckClearance: float):
    CapacityParamsAddBottleneckClearance(builder, bottleneckClearance)

def CapacityParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CapacityParamsEnd(builder)


class CapacityParamsT(object):

    # CapacityParamsT
    def __init__(
        self,
        planner = None,
        bottleneckClearance = 1.5,
    ):
        self.planner = planner  # type: Optional[str]
        self.bottleneckClearance = bottleneckClearance  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        capacityParams = CapacityParams()
        capacityParams.Init(buf, pos)
        return cls.InitFromObj(capacityParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, capacityParams):
        x = CapacityParamsT()
        x._UnPack(capacityParams)
        return x

    # CapacityParamsT
    def _UnPack(self, capacityParams):
        if capacityParams is None:
            return
        self.planner = capacityParams.Planner()
        if self.planner is not None:
            self.planner = self.planner.decode('utf-8')
        self.bottleneckClearance = capacityParams.BottleneckClearance()

    # CapacityParamsT
    def Pack(self, builder):
        if self.planner is not None:
            planner = builder.CreateString(self.planner)
        CapacityParamsStart(builder)
        if self.planner is not None:
            CapacityParamsAddPlanner(builder, planner)
        CapacityParamsAddBottleneckClearance(builder, self.bottleneckClearance)
        capacityParams = CapacityParamsEnd(builder)
        return capacityParams
