# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.config.GridParams import GridParams
from mqt.scpd.flatbuffers.config.PortConfig import PortConfig
from mqt.scpd.flatbuffers.design.DesignRules import DesignRules
from typing import Optional
np = import_numpy()

# The whole run configuration.
class Config(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Config()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Config
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The chip input path, relative to the configuration file.
    # Config
    def ChipInput(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Config
    def Ports(self) -> Optional[PortConfig]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = PortConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Config
    def Rules(self) -> Optional[DesignRules]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DesignRules()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Config
    def Grid(self) -> Optional[GridParams]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = GridParams()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ConfigStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    ConfigStart(builder)

def ConfigAddChipInput(builder: flatbuffers.Builder, chipInput: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(chipInput), 0)

def AddChipInput(builder: flatbuffers.Builder, chipInput: int):
    ConfigAddChipInput(builder, chipInput)

def ConfigAddPorts(builder: flatbuffers.Builder, ports: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ports), 0)

def AddPorts(builder: flatbuffers.Builder, ports: int):
    ConfigAddPorts(builder, ports)

def ConfigAddRules(builder: flatbuffers.Builder, rules: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(rules), 0)

def AddRules(builder: flatbuffers.Builder, rules: int):
    ConfigAddRules(builder, rules)

def ConfigAddGrid(builder: flatbuffers.Builder, grid: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(grid), 0)

def AddGrid(builder: flatbuffers.Builder, grid: int):
    ConfigAddGrid(builder, grid)

def ConfigEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ConfigEnd(builder)

import mqt.scpd.flatbuffers.config.GridParams
import mqt.scpd.flatbuffers.config.PortConfig
import mqt.scpd.flatbuffers.design.DesignRules
try:
    from typing import Optional
except:
    pass

class ConfigT(object):

    # ConfigT
    def __init__(
        self,
        chipInput = None,
        ports = None,
        rules = None,
        grid = None,
    ):
        self.chipInput = chipInput  # type: Optional[str]
        self.ports = ports  # type: Optional[mqt.scpd.flatbuffers.config.PortConfig.PortConfigT]
        self.rules = rules  # type: Optional[mqt.scpd.flatbuffers.design.DesignRules.DesignRulesT]
        self.grid = grid  # type: Optional[mqt.scpd.flatbuffers.config.GridParams.GridParamsT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        config = Config()
        config.Init(buf, pos)
        return cls.InitFromObj(config)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, config):
        x = ConfigT()
        x._UnPack(config)
        return x

    # ConfigT
    def _UnPack(self, config):
        if config is None:
            return
        self.chipInput = config.ChipInput()
        if self.chipInput is not None:
            self.chipInput = self.chipInput.decode('utf-8')
        if config.Ports() is not None:
            self.ports = mqt.scpd.flatbuffers.config.PortConfig.PortConfigT.InitFromObj(config.Ports())
        if config.Rules() is not None:
            self.rules = mqt.scpd.flatbuffers.design.DesignRules.DesignRulesT.InitFromObj(config.Rules())
        if config.Grid() is not None:
            self.grid = mqt.scpd.flatbuffers.config.GridParams.GridParamsT.InitFromObj(config.Grid())

    # ConfigT
    def Pack(self, builder):
        if self.chipInput is not None:
            chipInput = builder.CreateString(self.chipInput)
        if self.ports is not None:
            ports = self.ports.Pack(builder)
        if self.rules is not None:
            rules = self.rules.Pack(builder)
        if self.grid is not None:
            grid = self.grid.Pack(builder)
        ConfigStart(builder)
        if self.chipInput is not None:
            ConfigAddChipInput(builder, chipInput)
        if self.ports is not None:
            ConfigAddPorts(builder, ports)
        if self.rules is not None:
            ConfigAddRules(builder, rules)
        if self.grid is not None:
            ConfigAddGrid(builder, grid)
        config = ConfigEnd(builder)
        return config
