# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# What the Detail stage is allowed to do.
#
# The clearance the stage keeps between two wires is **not** here. It is
# derived from `min_wire_spacing` on the detail grid, because a clearance is
# a length in layout units and a cell count is a property of the grid; the
# prototype carries the same quantity twice, once computed and once as the
# literal 6, and the two disagree on every benchmark.
class DetailParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DetailParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDetailParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DetailParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The implementation, by the name it is registered under.
    # DetailParams
    def Router(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # How far to either side of its own path a wire may be moved when it is
    # re-routed across the partition borders, in wire spacings.
    #
    # This is the prototype's `K`, and its `K` is 40 cells of the detail grid:
    # a cell count and therefore not a distance, because one cell is 19 layout
    # units on the 17-qubit grid and 40 on the 9-qubit one. The same 40 stands
    # for 760 units on the one and 1600 on the other, which is four wire
    # spacings there and eight here. Counted in spacings it is the same
    # distance on all eight chips: room for the wire and for the wires either
    # side of it to move over by one.
    # DetailParams
    def CorridorSpacings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 4

    # Sweeps over the wire list, alternating forward and backward. A wire that
    # has been re-routed is left alone; the sweeps exist so that a wire which
    # found no way through can take the room a later one has not claimed yet.
    #
    # The prototype's own figure is 8, and 8 is enough for what it asks: it
    # holds the clearance between a wire and the two beside it in the ring and
    # against nothing else. Holding it against every wire is a harder question
    # and takes more sweeps to settle — measured over the eight benchmarks, 8
    # sweeps leave 46 places where the rule does not hold and 30 leave three.
    # DetailParams
    def Rounds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 30

    # How many neighbouring wires a failed re-route may let go of, counted
    # along the sweep direction first and then against it.
    # DetailParams
    def MaxRelaxation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 30

    # How far the cost of running close to an obstacle reaches, in layout
    # units. Zero switches the penalty off.
    #
    # A distance and not a cell count, for the same reason as
    # `corridor_spacings`: the prototype's 6 cells is 114 layout units on the
    # 17-qubit chip and 240 on the 9-qubit one.
    # DetailParams
    def ObstaclePenaltyReach(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 185.0

    # What running right beside an obstacle costs, falling off linearly to
    # nothing at `obstacle_penalty_reach`. A price per step, against the ten a
    # step along an axis costs, so it is the same price on every grid.
    # DetailParams
    def ObstaclePenalty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 10

    # How many orders the wires of one partition are tried in before the best
    # of them is kept. One means the wires are routed in the order they are
    # given.
    # DetailParams
    def Orderings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 16

def DetailParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(7)

def Start(builder: flatbuffers.Builder):
    DetailParamsStart(builder)

def DetailParamsAddRouter(builder: flatbuffers.Builder, router: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(router), 0)

def AddRouter(builder: flatbuffers.Builder, router: int):
    DetailParamsAddRouter(builder, router)

def DetailParamsAddCorridorSpacings(builder: flatbuffers.Builder, corridorSpacings: int):
    builder.PrependUint32Slot(1, corridorSpacings, 4)

def AddCorridorSpacings(builder: flatbuffers.Builder, corridorSpacings: int):
    DetailParamsAddCorridorSpacings(builder, corridorSpacings)

def DetailParamsAddRounds(builder: flatbuffers.Builder, rounds: int):
    builder.PrependUint32Slot(2, rounds, 30)

def AddRounds(builder: flatbuffers.Builder, rounds: int):
    DetailParamsAddRounds(builder, rounds)

def DetailParamsAddMaxRelaxation(builder: flatbuffers.Builder, maxRelaxation: int):
    builder.PrependUint32Slot(3, maxRelaxation, 30)

def AddMaxRelaxation(builder: flatbuffers.Builder, maxRelaxation: int):
    DetailParamsAddMaxRelaxation(builder, maxRelaxation)

def DetailParamsAddObstaclePenaltyReach(builder: flatbuffers.Builder, obstaclePenaltyReach: float):
    builder.PrependFloat64Slot(4, obstaclePenaltyReach, 185.0)

def AddObstaclePenaltyReach(builder: flatbuffers.Builder, obstaclePenaltyReach: float):
    DetailParamsAddObstaclePenaltyReach(builder, obstaclePenaltyReach)

def DetailParamsAddObstaclePenalty(builder: flatbuffers.Builder, obstaclePenalty: int):
    builder.PrependUint32Slot(5, obstaclePenalty, 10)

def AddObstaclePenalty(builder: flatbuffers.Builder, obstaclePenalty: int):
    DetailParamsAddObstaclePenalty(builder, obstaclePenalty)

def DetailParamsAddOrderings(builder: flatbuffers.Builder, orderings: int):
    builder.PrependUint32Slot(6, orderings, 16)

def AddOrderings(builder: flatbuffers.Builder, orderings: int):
    DetailParamsAddOrderings(builder, orderings)

def DetailParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DetailParamsEnd(builder)


class DetailParamsT(object):

    # DetailParamsT
    def __init__(
        self,
        router = None,
        corridorSpacings = 4,
        rounds = 30,
        maxRelaxation = 30,
        obstaclePenaltyReach = 185.0,
        obstaclePenalty = 10,
        orderings = 16,
    ):
        self.router = router  # type: Optional[str]
        self.corridorSpacings = corridorSpacings  # type: int
        self.rounds = rounds  # type: int
        self.maxRelaxation = maxRelaxation  # type: int
        self.obstaclePenaltyReach = obstaclePenaltyReach  # type: float
        self.obstaclePenalty = obstaclePenalty  # type: int
        self.orderings = orderings  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        detailParams = DetailParams()
        detailParams.Init(buf, pos)
        return cls.InitFromObj(detailParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, detailParams):
        x = DetailParamsT()
        x._UnPack(detailParams)
        return x

    # DetailParamsT
    def _UnPack(self, detailParams):
        if detailParams is None:
            return
        self.router = detailParams.Router()
        if self.router is not None:
            self.router = self.router.decode('utf-8')
        self.corridorSpacings = detailParams.CorridorSpacings()
        self.rounds = detailParams.Rounds()
        self.maxRelaxation = detailParams.MaxRelaxation()
        self.obstaclePenaltyReach = detailParams.ObstaclePenaltyReach()
        self.obstaclePenalty = detailParams.ObstaclePenalty()
        self.orderings = detailParams.Orderings()

    # DetailParamsT
    def Pack(self, builder):
        if self.router is not None:
            router = builder.CreateString(self.router)
        DetailParamsStart(builder)
        if self.router is not None:
            DetailParamsAddRouter(builder, router)
        DetailParamsAddCorridorSpacings(builder, self.corridorSpacings)
        DetailParamsAddRounds(builder, self.rounds)
        DetailParamsAddMaxRelaxation(builder, self.maxRelaxation)
        DetailParamsAddObstaclePenaltyReach(builder, self.obstaclePenaltyReach)
        DetailParamsAddObstaclePenalty(builder, self.obstaclePenalty)
        DetailParamsAddOrderings(builder, self.orderings)
        detailParams = DetailParamsEnd(builder)
        return detailParams
