# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# What the Final stage is allowed to do.
#
# No clearance is here, for the reason `DetailParams` gives: a clearance is a
# length in layout units and a cell count is a property of the grid. The
# stage keeps `cells_for(min_wire_spacing, router)` between two wires and
# `cells_for(min_straight_length, router)` as its straight stub, and it bakes
# `min_obstacle_spacing` into the obstacle mask. The prototype writes all
# three as the literals 19, 9 and 2, and none of them records a reason.
class FinalParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FinalParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFinalParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FinalParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The implementation, by the name it is registered under.
    # FinalParams
    def Router(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # How far to either side of the way it already has a wire may be moved when
    # it is routed again, in wire spacings.
    #
    # The prototype's `outer_expansion` is 200 cells of the router grid in the
    # drivers that ship, which is 2000 layout units and therefore a different
    # distance on every chip. Counted in spacings the same number is the same
    # room everywhere.
    # FinalParams
    def CorridorSpacings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 11

    # The same, for the wires of the inner circuit, which run inside one unit
    # cell and need far less room.
    # FinalParams
    def InnerCorridorSpacings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 11

    # Sweeps over the wire list, alternating forward and backward. A wire that
    # has been routed is left alone; the sweeps exist so that a wire which
    # found no way through can take the room a later one has not claimed yet.
    # FinalParams
    def Rounds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 30

    # The same, for the inner circuit.
    # FinalParams
    def InnerRounds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 4

    # How many neighbouring wires a failed route may let go of, counted along
    # the sweep direction.
    # FinalParams
    def MaxRelaxation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 10

    # Rounds that route every wire again against a proximity price, to widen
    # the room around it. A wire that does not route keeps the way it had.
    # FinalParams
    def RefinementRounds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 2

    # How long a resonator's way is made before the coupler is spliced into
    # it, in layout units. Zero switches the meander off.
    #
    # This is not `target_resonator_length`. The wire is fed from the segment
    # between two launchers and the coupler is spliced where the way left to
    # the qubit port reaches the target length, so the whole way has to be
    # longer than the target. The prototype's own figures are 3000 layout units
    # on the 17-qubit chip and 6000 on the 69-qubit one.
    # FinalParams
    def MeanderLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 3000.0

    # What one eighth turn costs, in hundredths of a cell.
    #
    # A price and not a distance, but it is still normalised: a bend costs a
    # fixed amount while a way's cost grows with the grid, so the prototype had
    # to retune it per chip from 8000 to 30000. It is quoted here against the
    # sum of the grid's two extents, as the prototype's own `_norm` fields do,
    # and multiplied by that sum at the point of use.
    # FinalParams
    def BendPenaltyNorm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 2.5

    # What running beside another wire costs, on the same scale.
    # FinalParams
    def WireProximityPenaltyNorm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.00125

    # What running beside an obstacle costs, on the same scale.
    # FinalParams
    def StaticProximityPenaltyNorm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.00033

    # How far the cost of running close to an obstacle reaches, in layout
    # units. Zero switches the penalty off.
    # FinalParams
    def ObstaclePenaltyReach(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 100.0

    # The physical size of the coupler body the stage instantiates, in layout
    # units. The prototype carries it as 20 by 3 cells.
    # FinalParams
    def CouplerLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 200.0

    # FinalParams
    def CouplerHeight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 26.0

def FinalParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(14)

def Start(builder: flatbuffers.Builder):
    FinalParamsStart(builder)

def FinalParamsAddRouter(builder: flatbuffers.Builder, router: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(router), 0)

def AddRouter(builder: flatbuffers.Builder, router: int):
    FinalParamsAddRouter(builder, router)

def FinalParamsAddCorridorSpacings(builder: flatbuffers.Builder, corridorSpacings: int):
    builder.PrependUint32Slot(1, corridorSpacings, 11)

def AddCorridorSpacings(builder: flatbuffers.Builder, corridorSpacings: int):
    FinalParamsAddCorridorSpacings(builder, corridorSpacings)

def FinalParamsAddInnerCorridorSpacings(builder: flatbuffers.Builder, innerCorridorSpacings: int):
    builder.PrependUint32Slot(2, innerCorridorSpacings, 11)

def AddInnerCorridorSpacings(builder: flatbuffers.Builder, innerCorridorSpacings: int):
    FinalParamsAddInnerCorridorSpacings(builder, innerCorridorSpacings)

def FinalParamsAddRounds(builder: flatbuffers.Builder, rounds: int):
    builder.PrependUint32Slot(3, rounds, 30)

def AddRounds(builder: flatbuffers.Builder, rounds: int):
    FinalParamsAddRounds(builder, rounds)

def FinalParamsAddInnerRounds(builder: flatbuffers.Builder, innerRounds: int):
    builder.PrependUint32Slot(4, innerRounds, 4)

def AddInnerRounds(builder: flatbuffers.Builder, innerRounds: int):
    FinalParamsAddInnerRounds(builder, innerRounds)

def FinalParamsAddMaxRelaxation(builder: flatbuffers.Builder, maxRelaxation: int):
    builder.PrependUint32Slot(5, maxRelaxation, 10)

def AddMaxRelaxation(builder: flatbuffers.Builder, maxRelaxation: int):
    FinalParamsAddMaxRelaxation(builder, maxRelaxation)

def FinalParamsAddRefinementRounds(builder: flatbuffers.Builder, refinementRounds: int):
    builder.PrependUint32Slot(6, refinementRounds, 2)

def AddRefinementRounds(builder: flatbuffers.Builder, refinementRounds: int):
    FinalParamsAddRefinementRounds(builder, refinementRounds)

def FinalParamsAddMeanderLength(builder: flatbuffers.Builder, meanderLength: float):
    builder.PrependFloat64Slot(7, meanderLength, 3000.0)

def AddMeanderLength(builder: flatbuffers.Builder, meanderLength: float):
    FinalParamsAddMeanderLength(builder, meanderLength)

def FinalParamsAddBendPenaltyNorm(builder: flatbuffers.Builder, bendPenaltyNorm: float):
    builder.PrependFloat64Slot(8, bendPenaltyNorm, 2.5)

def AddBendPenaltyNorm(builder: flatbuffers.Builder, bendPenaltyNorm: float):
    FinalParamsAddBendPenaltyNorm(builder, bendPenaltyNorm)

def FinalParamsAddWireProximityPenaltyNorm(builder: flatbuffers.Builder, wireProximityPenaltyNorm: float):
    builder.PrependFloat64Slot(9, wireProximityPenaltyNorm, 0.00125)

def AddWireProximityPenaltyNorm(builder: flatbuffers.Builder, wireProximityPenaltyNorm: float):
    FinalParamsAddWireProximityPenaltyNorm(builder, wireProximityPenaltyNorm)

def FinalParamsAddStaticProximityPenaltyNorm(builder: flatbuffers.Builder, staticProximityPenaltyNorm: float):
    builder.PrependFloat64Slot(10, staticProximityPenaltyNorm, 0.00033)

def AddStaticProximityPenaltyNorm(builder: flatbuffers.Builder, staticProximityPenaltyNorm: float):
    FinalParamsAddStaticProximityPenaltyNorm(builder, staticProximityPenaltyNorm)

def FinalParamsAddObstaclePenaltyReach(builder: flatbuffers.Builder, obstaclePenaltyReach: float):
    builder.PrependFloat64Slot(11, obstaclePenaltyReach, 100.0)

def AddObstaclePenaltyReach(builder: flatbuffers.Builder, obstaclePenaltyReach: float):
    FinalParamsAddObstaclePenaltyReach(builder, obstaclePenaltyReach)

def FinalParamsAddCouplerLength(builder: flatbuffers.Builder, couplerLength: float):
    builder.PrependFloat64Slot(12, couplerLength, 200.0)

def AddCouplerLength(builder: flatbuffers.Builder, couplerLength: float):
    FinalParamsAddCouplerLength(builder, couplerLength)

def FinalParamsAddCouplerHeight(builder: flatbuffers.Builder, couplerHeight: float):
    builder.PrependFloat64Slot(13, couplerHeight, 26.0)

def AddCouplerHeight(builder: flatbuffers.Builder, couplerHeight: float):
    FinalParamsAddCouplerHeight(builder, couplerHeight)

def FinalParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FinalParamsEnd(builder)


class FinalParamsT(object):

    # FinalParamsT
    def __init__(
        self,
        router = None,
        corridorSpacings = 11,
        innerCorridorSpacings = 11,
        rounds = 30,
        innerRounds = 4,
        maxRelaxation = 10,
        refinementRounds = 2,
        meanderLength = 3000.0,
        bendPenaltyNorm = 2.5,
        wireProximityPenaltyNorm = 0.00125,
        staticProximityPenaltyNorm = 0.00033,
        obstaclePenaltyReach = 100.0,
        couplerLength = 200.0,
        couplerHeight = 26.0,
    ):
        self.router = router  # type: Optional[str]
        self.corridorSpacings = corridorSpacings  # type: int
        self.innerCorridorSpacings = innerCorridorSpacings  # type: int
        self.rounds = rounds  # type: int
        self.innerRounds = innerRounds  # type: int
        self.maxRelaxation = maxRelaxation  # type: int
        self.refinementRounds = refinementRounds  # type: int
        self.meanderLength = meanderLength  # type: float
        self.bendPenaltyNorm = bendPenaltyNorm  # type: float
        self.wireProximityPenaltyNorm = wireProximityPenaltyNorm  # type: float
        self.staticProximityPenaltyNorm = staticProximityPenaltyNorm  # type: float
        self.obstaclePenaltyReach = obstaclePenaltyReach  # type: float
        self.couplerLength = couplerLength  # type: float
        self.couplerHeight = couplerHeight  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        finalParams = FinalParams()
        finalParams.Init(buf, pos)
        return cls.InitFromObj(finalParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, finalParams):
        x = FinalParamsT()
        x._UnPack(finalParams)
        return x

    # FinalParamsT
    def _UnPack(self, finalParams):
        if finalParams is None:
            return
        self.router = finalParams.Router()
        if self.router is not None:
            self.router = self.router.decode('utf-8')
        self.corridorSpacings = finalParams.CorridorSpacings()
        self.innerCorridorSpacings = finalParams.InnerCorridorSpacings()
        self.rounds = finalParams.Rounds()
        self.innerRounds = finalParams.InnerRounds()
        self.maxRelaxation = finalParams.MaxRelaxation()
        self.refinementRounds = finalParams.RefinementRounds()
        self.meanderLength = finalParams.MeanderLength()
        self.bendPenaltyNorm = finalParams.BendPenaltyNorm()
        self.wireProximityPenaltyNorm = finalParams.WireProximityPenaltyNorm()
        self.staticProximityPenaltyNorm = finalParams.StaticProximityPenaltyNorm()
        self.obstaclePenaltyReach = finalParams.ObstaclePenaltyReach()
        self.couplerLength = finalParams.CouplerLength()
        self.couplerHeight = finalParams.CouplerHeight()

    # FinalParamsT
    def Pack(self, builder):
        if self.router is not None:
            router = builder.CreateString(self.router)
        FinalParamsStart(builder)
        if self.router is not None:
            FinalParamsAddRouter(builder, router)
        FinalParamsAddCorridorSpacings(builder, self.corridorSpacings)
        FinalParamsAddInnerCorridorSpacings(builder, self.innerCorridorSpacings)
        FinalParamsAddRounds(builder, self.rounds)
        FinalParamsAddInnerRounds(builder, self.innerRounds)
        FinalParamsAddMaxRelaxation(builder, self.maxRelaxation)
        FinalParamsAddRefinementRounds(builder, self.refinementRounds)
        FinalParamsAddMeanderLength(builder, self.meanderLength)
        FinalParamsAddBendPenaltyNorm(builder, self.bendPenaltyNorm)
        FinalParamsAddWireProximityPenaltyNorm(builder, self.wireProximityPenaltyNorm)
        FinalParamsAddStaticProximityPenaltyNorm(builder, self.staticProximityPenaltyNorm)
        FinalParamsAddObstaclePenaltyReach(builder, self.obstaclePenaltyReach)
        FinalParamsAddCouplerLength(builder, self.couplerLength)
        FinalParamsAddCouplerHeight(builder, self.couplerHeight)
        finalParams = FinalParamsEnd(builder)
        return finalParams
