# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# What the Global stage is allowed to do.
class GlobalParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GlobalParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGlobalParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GlobalParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The implementation, by the name it is registered under.
    # GlobalParams
    def Router(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Whether an inner wire may cross a component the outer ring does not
    # reach, through one of that component's own bridges.
    #
    # Off by default. Such a crossing is a wire that enters a coupler the
    # assignment never sees and leaves on the far side, so where it runs is
    # decided by nothing the later stages can read back. The prototype allows
    # it and has no way to say otherwise.
    # GlobalParams
    def InternalBridges(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def GlobalParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    GlobalParamsStart(builder)

def GlobalParamsAddRouter(builder: flatbuffers.Builder, router: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(router), 0)

def AddRouter(builder: flatbuffers.Builder, router: int):
    GlobalParamsAddRouter(builder, router)

def GlobalParamsAddInternalBridges(builder: flatbuffers.Builder, internalBridges: bool):
    builder.PrependBoolSlot(1, internalBridges, 0)

def AddInternalBridges(builder: flatbuffers.Builder, internalBridges: bool):
    GlobalParamsAddInternalBridges(builder, internalBridges)

def GlobalParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return GlobalParamsEnd(builder)


class GlobalParamsT(object):

    # GlobalParamsT
    def __init__(
        self,
        router = None,
        internalBridges = False,
    ):
        self.router = router  # type: Optional[str]
        self.internalBridges = internalBridges  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        globalParams = GlobalParams()
        globalParams.Init(buf, pos)
        return cls.InitFromObj(globalParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, globalParams):
        x = GlobalParamsT()
        x._UnPack(globalParams)
        return x

    # GlobalParamsT
    def _UnPack(self, globalParams):
        if globalParams is None:
            return
        self.router = globalParams.Router()
        if self.router is not None:
            self.router = self.router.decode('utf-8')
        self.internalBridges = globalParams.InternalBridges()

    # GlobalParamsT
    def Pack(self, builder):
        if self.router is not None:
            router = builder.CreateString(self.router)
        GlobalParamsStart(builder)
        if self.router is not None:
            GlobalParamsAddRouter(builder, router)
        GlobalParamsAddInternalBridges(builder, self.internalBridges)
        globalParams = GlobalParamsEnd(builder)
        return globalParams
