# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

# Where the outer port ring comes from. See decision 0023.
class PortDetection(object):
    # The configuration supplies all_outer and fixed_outer.
    Manual = 0
    # The outer-boundary walk derives both sequences from the chip geometry.
    Auto = 1
