# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.config.PortPatterns import PortPatterns
from mqt.scpd.flatbuffers.config.PortSequences import PortSequences
from typing import Optional
np = import_numpy()

class PortConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PortConfig()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPortConfig(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PortConfig
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PortConfig
    def Patterns(self) -> Optional[PortPatterns]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = PortPatterns()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PortConfig
    def Detection(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Auto only. The component at which the closed ring is entered; empty
    # takes the walk's own start.
    # PortConfig
    def StartComponent(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Manual only.
    # PortConfig
    def Sequences(self) -> Optional[PortSequences]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = PortSequences()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PortConfigStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    PortConfigStart(builder)

def PortConfigAddPatterns(builder: flatbuffers.Builder, patterns: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(patterns), 0)

def AddPatterns(builder: flatbuffers.Builder, patterns: int):
    PortConfigAddPatterns(builder, patterns)

def PortConfigAddDetection(builder: flatbuffers.Builder, detection: int):
    builder.PrependUint8Slot(1, detection, 0)

def AddDetection(builder: flatbuffers.Builder, detection: int):
    PortConfigAddDetection(builder, detection)

def PortConfigAddStartComponent(builder: flatbuffers.Builder, startComponent: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(startComponent), 0)

def AddStartComponent(builder: flatbuffers.Builder, startComponent: int):
    PortConfigAddStartComponent(builder, startComponent)

def PortConfigAddSequences(builder: flatbuffers.Builder, sequences: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(sequences), 0)

def AddSequences(builder: flatbuffers.Builder, sequences: int):
    PortConfigAddSequences(builder, sequences)

def PortConfigEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PortConfigEnd(builder)

import mqt.scpd.flatbuffers.config.PortPatterns
import mqt.scpd.flatbuffers.config.PortSequences
try:
    from typing import Optional
except:
    pass

class PortConfigT(object):

    # PortConfigT
    def __init__(
        self,
        patterns = None,
        detection = 0,
        startComponent = None,
        sequences = None,
    ):
        self.patterns = patterns  # type: Optional[mqt.scpd.flatbuffers.config.PortPatterns.PortPatternsT]
        self.detection = detection  # type: int
        self.startComponent = startComponent  # type: Optional[str]
        self.sequences = sequences  # type: Optional[mqt.scpd.flatbuffers.config.PortSequences.PortSequencesT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        portConfig = PortConfig()
        portConfig.Init(buf, pos)
        return cls.InitFromObj(portConfig)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, portConfig):
        x = PortConfigT()
        x._UnPack(portConfig)
        return x

    # PortConfigT
    def _UnPack(self, portConfig):
        if portConfig is None:
            return
        if portConfig.Patterns() is not None:
            self.patterns = mqt.scpd.flatbuffers.config.PortPatterns.PortPatternsT.InitFromObj(portConfig.Patterns())
        self.detection = portConfig.Detection()
        self.startComponent = portConfig.StartComponent()
        if self.startComponent is not None:
            self.startComponent = self.startComponent.decode('utf-8')
        if portConfig.Sequences() is not None:
            self.sequences = mqt.scpd.flatbuffers.config.PortSequences.PortSequencesT.InitFromObj(portConfig.Sequences())

    # PortConfigT
    def Pack(self, builder):
        if self.patterns is not None:
            patterns = self.patterns.Pack(builder)
        if self.startComponent is not None:
            startComponent = builder.CreateString(self.startComponent)
        if self.sequences is not None:
            sequences = self.sequences.Pack(builder)
        PortConfigStart(builder)
        if self.patterns is not None:
            PortConfigAddPatterns(builder, patterns)
        PortConfigAddDetection(builder, self.detection)
        if self.startComponent is not None:
            PortConfigAddStartComponent(builder, startComponent)
        if self.sequences is not None:
            PortConfigAddSequences(builder, sequences)
        portConfig = PortConfigEnd(builder)
        return portConfig
