# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# One regular expression per role. Every port must match exactly one.
class PortPatterns(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PortPatterns()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPortPatterns(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PortPatterns
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PortPatterns
    def Launcher(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PortPatterns
    def Resonator(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PortPatterns
    def Conventional(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PortPatternsStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    PortPatternsStart(builder)

def PortPatternsAddLauncher(builder: flatbuffers.Builder, launcher: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(launcher), 0)

def AddLauncher(builder: flatbuffers.Builder, launcher: int):
    PortPatternsAddLauncher(builder, launcher)

def PortPatternsAddResonator(builder: flatbuffers.Builder, resonator: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(resonator), 0)

def AddResonator(builder: flatbuffers.Builder, resonator: int):
    PortPatternsAddResonator(builder, resonator)

def PortPatternsAddConventional(builder: flatbuffers.Builder, conventional: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(conventional), 0)

def AddConventional(builder: flatbuffers.Builder, conventional: int):
    PortPatternsAddConventional(builder, conventional)

def PortPatternsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PortPatternsEnd(builder)


class PortPatternsT(object):

    # PortPatternsT
    def __init__(
        self,
        launcher = None,
        resonator = None,
        conventional = None,
    ):
        self.launcher = launcher  # type: Optional[str]
        self.resonator = resonator  # type: Optional[str]
        self.conventional = conventional  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        portPatterns = PortPatterns()
        portPatterns.Init(buf, pos)
        return cls.InitFromObj(portPatterns)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, portPatterns):
        x = PortPatternsT()
        x._UnPack(portPatterns)
        return x

    # PortPatternsT
    def _UnPack(self, portPatterns):
        if portPatterns is None:
            return
        self.launcher = portPatterns.Launcher()
        if self.launcher is not None:
            self.launcher = self.launcher.decode('utf-8')
        self.resonator = portPatterns.Resonator()
        if self.resonator is not None:
            self.resonator = self.resonator.decode('utf-8')
        self.conventional = portPatterns.Conventional()
        if self.conventional is not None:
            self.conventional = self.conventional.decode('utf-8')

    # PortPatternsT
    def Pack(self, builder):
        if self.launcher is not None:
            launcher = builder.CreateString(self.launcher)
        if self.resonator is not None:
            resonator = builder.CreateString(self.resonator)
        if self.conventional is not None:
            conventional = builder.CreateString(self.conventional)
        PortPatternsStart(builder)
        if self.launcher is not None:
            PortPatternsAddLauncher(builder, launcher)
        if self.resonator is not None:
            PortPatternsAddResonator(builder, resonator)
        if self.conventional is not None:
            PortPatternsAddConventional(builder, conventional)
        portPatterns = PortPatternsEnd(builder)
        return portPatterns
