# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# How far a run goes.
class RunParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRunParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RunParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The last step to run: a stage, or a phase of a stage. Empty runs every
    # step this release implements. The command line can override it.
    # RunParams
    def StopAfter(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RunParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    RunParamsStart(builder)

def RunParamsAddStopAfter(builder: flatbuffers.Builder, stopAfter: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stopAfter), 0)

def AddStopAfter(builder: flatbuffers.Builder, stopAfter: int):
    RunParamsAddStopAfter(builder, stopAfter)

def RunParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return RunParamsEnd(builder)


class RunParamsT(object):

    # RunParamsT
    def __init__(
        self,
        stopAfter = None,
    ):
        self.stopAfter = stopAfter  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        runParams = RunParams()
        runParams.Init(buf, pos)
        return cls.InitFromObj(runParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, runParams):
        x = RunParamsT()
        x._UnPack(runParams)
        return x

    # RunParamsT
    def _UnPack(self, runParams):
        if runParams is None:
            return
        self.stopAfter = runParams.StopAfter()
        if self.stopAfter is not None:
            self.stopAfter = self.stopAfter.decode('utf-8')

    # RunParamsT
    def Pack(self, builder):
        if self.stopAfter is not None:
            stopAfter = builder.CreateString(self.stopAfter)
        RunParamsStart(builder)
        if self.stopAfter is not None:
            RunParamsAddStopAfter(builder, stopAfter)
        runParams = RunParamsEnd(builder)
        return runParams
