# automatically generated by the FlatBuffers compiler, do not modify

# namespace: config

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from typing import Optional
np = import_numpy()

# How the mixed-integer programs of the planning stages are solved.
class SolverParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SolverParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSolverParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SolverParams
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # "auto", "highs" or "gurobi". The environment variable SCPD_SOLVER
    # overrides it for one run.
    # SolverParams
    def Backend(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Seconds one solve may take, or zero for no limit.
    # SolverParams
    def TimeLimit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # The relative gap a solve may stop at, or zero for the backend's own.
    # SolverParams
    def RelativeGap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def SolverParamsStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    SolverParamsStart(builder)

def SolverParamsAddBackend(builder: flatbuffers.Builder, backend: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(backend), 0)

def AddBackend(builder: flatbuffers.Builder, backend: int):
    SolverParamsAddBackend(builder, backend)

def SolverParamsAddTimeLimit(builder: flatbuffers.Builder, timeLimit: float):
    builder.PrependFloat64Slot(1, timeLimit, 0.0)

def AddTimeLimit(builder: flatbuffers.Builder, timeLimit: float):
    SolverParamsAddTimeLimit(builder, timeLimit)

def SolverParamsAddRelativeGap(builder: flatbuffers.Builder, relativeGap: float):
    builder.PrependFloat64Slot(2, relativeGap, 0.0)

def AddRelativeGap(builder: flatbuffers.Builder, relativeGap: float):
    SolverParamsAddRelativeGap(builder, relativeGap)

def SolverParamsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SolverParamsEnd(builder)


class SolverParamsT(object):

    # SolverParamsT
    def __init__(
        self,
        backend = None,
        timeLimit = 0.0,
        relativeGap = 0.0,
    ):
        self.backend = backend  # type: Optional[str]
        self.timeLimit = timeLimit  # type: float
        self.relativeGap = relativeGap  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        solverParams = SolverParams()
        solverParams.Init(buf, pos)
        return cls.InitFromObj(solverParams)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, solverParams):
        x = SolverParamsT()
        x._UnPack(solverParams)
        return x

    # SolverParamsT
    def _UnPack(self, solverParams):
        if solverParams is None:
            return
        self.backend = solverParams.Backend()
        if self.backend is not None:
            self.backend = self.backend.decode('utf-8')
        self.timeLimit = solverParams.TimeLimit()
        self.relativeGap = solverParams.RelativeGap()

    # SolverParamsT
    def Pack(self, builder):
        if self.backend is not None:
            backend = builder.CreateString(self.backend)
        SolverParamsStart(builder)
        if self.backend is not None:
            SolverParamsAddBackend(builder, backend)
        SolverParamsAddTimeLimit(builder, self.timeLimit)
        SolverParamsAddRelativeGap(builder, self.relativeGap)
        solverParams = SolverParamsEnd(builder)
        return solverParams
