// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CONFIG_MQT_SCPD_FLATBUFFERS_CONFIG_H_
#define FLATBUFFERS_GENERATED_CONFIG_MQT_SCPD_FLATBUFFERS_CONFIG_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "mqt-scpd/flatbuffers/design.hpp"

namespace mqt {
namespace scpd {
namespace flatbuffers {
namespace config {

struct PortPatterns;
struct PortPatternsBuilder;
struct PortPatternsT;

struct PortSequences;
struct PortSequencesBuilder;
struct PortSequencesT;

struct PortConfig;
struct PortConfigBuilder;
struct PortConfigT;

struct GridParams;
struct GridParamsBuilder;
struct GridParamsT;

struct Config;
struct ConfigBuilder;
struct ConfigT;

bool operator==(const PortPatternsT &lhs, const PortPatternsT &rhs);
bool operator!=(const PortPatternsT &lhs, const PortPatternsT &rhs);
bool operator==(const PortSequencesT &lhs, const PortSequencesT &rhs);
bool operator!=(const PortSequencesT &lhs, const PortSequencesT &rhs);
bool operator==(const PortConfigT &lhs, const PortConfigT &rhs);
bool operator!=(const PortConfigT &lhs, const PortConfigT &rhs);
bool operator==(const GridParamsT &lhs, const GridParamsT &rhs);
bool operator!=(const GridParamsT &lhs, const GridParamsT &rhs);
bool operator==(const ConfigT &lhs, const ConfigT &rhs);
bool operator!=(const ConfigT &lhs, const ConfigT &rhs);

/// Where the outer port ring comes from. See decision 0023.
enum class PortDetection : uint8_t {
  /// The configuration supplies all_outer and fixed_outer.
  Manual = 0,
  /// The outer-boundary walk derives both sequences from the chip geometry.
  Auto = 1,
  MIN = Manual,
  MAX = Auto
};

inline const PortDetection (&EnumValuesPortDetection())[2] {
  static const PortDetection values[] = {
    PortDetection::Manual,
    PortDetection::Auto
  };
  return values;
}

inline const char * const *EnumNamesPortDetection() {
  static const char * const names[3] = {
    "Manual",
    "Auto",
    nullptr
  };
  return names;
}

inline const char *EnumNamePortDetection(PortDetection e) {
  if (::flatbuffers::IsOutRange(e, PortDetection::Manual, PortDetection::Auto)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPortDetection()[index];
}

struct PortPatternsT : public ::flatbuffers::NativeTable {
  typedef PortPatterns TableType;
  std::string launcher{};
  std::string resonator{};
  std::string conventional{};
};

/// One regular expression per role. Every port must match exactly one.
struct PortPatterns FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PortPatternsT NativeTableType;
  typedef PortPatternsBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LAUNCHER = 4,
    VT_RESONATOR = 6,
    VT_CONVENTIONAL = 8
  };
  const ::flatbuffers::String *launcher() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LAUNCHER);
  }
  const ::flatbuffers::String *resonator() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RESONATOR);
  }
  const ::flatbuffers::String *conventional() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONVENTIONAL);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_LAUNCHER) &&
           verifier.VerifyString(launcher()) &&
           VerifyOffsetRequired(verifier, VT_RESONATOR) &&
           verifier.VerifyString(resonator()) &&
           VerifyOffsetRequired(verifier, VT_CONVENTIONAL) &&
           verifier.VerifyString(conventional()) &&
           verifier.EndTable();
  }
  PortPatternsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PortPatternsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PortPatterns> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PortPatternsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PortPatternsBuilder {
  typedef PortPatterns Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_launcher(::flatbuffers::Offset<::flatbuffers::String> launcher) {
    fbb_.AddOffset(PortPatterns::VT_LAUNCHER, launcher);
  }
  void add_resonator(::flatbuffers::Offset<::flatbuffers::String> resonator) {
    fbb_.AddOffset(PortPatterns::VT_RESONATOR, resonator);
  }
  void add_conventional(::flatbuffers::Offset<::flatbuffers::String> conventional) {
    fbb_.AddOffset(PortPatterns::VT_CONVENTIONAL, conventional);
  }
  explicit PortPatternsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PortPatterns> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PortPatterns>(end);
    fbb_.Required(o, PortPatterns::VT_LAUNCHER);
    fbb_.Required(o, PortPatterns::VT_RESONATOR);
    fbb_.Required(o, PortPatterns::VT_CONVENTIONAL);
    return o;
  }
};

inline ::flatbuffers::Offset<PortPatterns> CreatePortPatterns(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> launcher = 0,
    ::flatbuffers::Offset<::flatbuffers::String> resonator = 0,
    ::flatbuffers::Offset<::flatbuffers::String> conventional = 0) {
  PortPatternsBuilder builder_(_fbb);
  builder_.add_conventional(conventional);
  builder_.add_resonator(resonator);
  builder_.add_launcher(launcher);
  return builder_.Finish();
}

struct PortPatterns::Traits {
  using type = PortPatterns;
  static auto constexpr Create = CreatePortPatterns;
};

inline ::flatbuffers::Offset<PortPatterns> CreatePortPatternsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *launcher = nullptr,
    const char *resonator = nullptr,
    const char *conventional = nullptr) {
  auto launcher__ = launcher ? _fbb.CreateString(launcher) : 0;
  auto resonator__ = resonator ? _fbb.CreateString(resonator) : 0;
  auto conventional__ = conventional ? _fbb.CreateString(conventional) : 0;
  return mqt::scpd::flatbuffers::config::CreatePortPatterns(
      _fbb,
      launcher__,
      resonator__,
      conventional__);
}

::flatbuffers::Offset<PortPatterns> CreatePortPatterns(::flatbuffers::FlatBufferBuilder &_fbb, const PortPatternsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PortSequencesT : public ::flatbuffers::NativeTable {
  typedef PortSequences TableType;
  std::vector<std::string> all_outer{};
  std::vector<std::string> fixed_outer{};
};

/// The two ordered outer port sequences. Required under Manual, an error
/// under Auto.
struct PortSequences FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PortSequencesT NativeTableType;
  typedef PortSequencesBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ALL_OUTER = 4,
    VT_FIXED_OUTER = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *all_outer() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_ALL_OUTER);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *fixed_outer() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_FIXED_OUTER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ALL_OUTER) &&
           verifier.VerifyVector(all_outer()) &&
           verifier.VerifyVectorOfStrings(all_outer()) &&
           VerifyOffsetRequired(verifier, VT_FIXED_OUTER) &&
           verifier.VerifyVector(fixed_outer()) &&
           verifier.VerifyVectorOfStrings(fixed_outer()) &&
           verifier.EndTable();
  }
  PortSequencesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PortSequencesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PortSequences> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PortSequencesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PortSequencesBuilder {
  typedef PortSequences Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_all_outer(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> all_outer) {
    fbb_.AddOffset(PortSequences::VT_ALL_OUTER, all_outer);
  }
  void add_fixed_outer(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> fixed_outer) {
    fbb_.AddOffset(PortSequences::VT_FIXED_OUTER, fixed_outer);
  }
  explicit PortSequencesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PortSequences> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PortSequences>(end);
    fbb_.Required(o, PortSequences::VT_ALL_OUTER);
    fbb_.Required(o, PortSequences::VT_FIXED_OUTER);
    return o;
  }
};

inline ::flatbuffers::Offset<PortSequences> CreatePortSequences(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> all_outer = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> fixed_outer = 0) {
  PortSequencesBuilder builder_(_fbb);
  builder_.add_fixed_outer(fixed_outer);
  builder_.add_all_outer(all_outer);
  return builder_.Finish();
}

struct PortSequences::Traits {
  using type = PortSequences;
  static auto constexpr Create = CreatePortSequences;
};

inline ::flatbuffers::Offset<PortSequences> CreatePortSequencesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *all_outer = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *fixed_outer = nullptr) {
  auto all_outer__ = all_outer ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*all_outer) : 0;
  auto fixed_outer__ = fixed_outer ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*fixed_outer) : 0;
  return mqt::scpd::flatbuffers::config::CreatePortSequences(
      _fbb,
      all_outer__,
      fixed_outer__);
}

::flatbuffers::Offset<PortSequences> CreatePortSequences(::flatbuffers::FlatBufferBuilder &_fbb, const PortSequencesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PortConfigT : public ::flatbuffers::NativeTable {
  typedef PortConfig TableType;
  std::unique_ptr<mqt::scpd::flatbuffers::config::PortPatternsT> patterns{};
  mqt::scpd::flatbuffers::config::PortDetection detection = mqt::scpd::flatbuffers::config::PortDetection::Manual;
  std::string start_component{};
  std::unique_ptr<mqt::scpd::flatbuffers::config::PortSequencesT> sequences{};
  PortConfigT() = default;
  PortConfigT(const PortConfigT &o);
  PortConfigT(PortConfigT&&) FLATBUFFERS_NOEXCEPT = default;
  PortConfigT &operator=(PortConfigT o) FLATBUFFERS_NOEXCEPT;
};

struct PortConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PortConfigT NativeTableType;
  typedef PortConfigBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PATTERNS = 4,
    VT_DETECTION = 6,
    VT_START_COMPONENT = 8,
    VT_SEQUENCES = 10
  };
  const mqt::scpd::flatbuffers::config::PortPatterns *patterns() const {
    return GetPointer<const mqt::scpd::flatbuffers::config::PortPatterns *>(VT_PATTERNS);
  }
  mqt::scpd::flatbuffers::config::PortDetection detection() const {
    return static_cast<mqt::scpd::flatbuffers::config::PortDetection>(GetField<uint8_t>(VT_DETECTION, 0));
  }
  /// Auto only. The component at which the closed ring is entered; empty
  /// takes the walk's own start.
  const ::flatbuffers::String *start_component() const {
    return GetPointer<const ::flatbuffers::String *>(VT_START_COMPONENT);
  }
  /// Manual only.
  const mqt::scpd::flatbuffers::config::PortSequences *sequences() const {
    return GetPointer<const mqt::scpd::flatbuffers::config::PortSequences *>(VT_SEQUENCES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_PATTERNS) &&
           verifier.VerifyTable(patterns()) &&
           VerifyField<uint8_t>(verifier, VT_DETECTION, 1) &&
           VerifyOffset(verifier, VT_START_COMPONENT) &&
           verifier.VerifyString(start_component()) &&
           VerifyOffset(verifier, VT_SEQUENCES) &&
           verifier.VerifyTable(sequences()) &&
           verifier.EndTable();
  }
  PortConfigT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PortConfigT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PortConfig> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PortConfigT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PortConfigBuilder {
  typedef PortConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_patterns(::flatbuffers::Offset<mqt::scpd::flatbuffers::config::PortPatterns> patterns) {
    fbb_.AddOffset(PortConfig::VT_PATTERNS, patterns);
  }
  void add_detection(mqt::scpd::flatbuffers::config::PortDetection detection) {
    fbb_.AddElement<uint8_t>(PortConfig::VT_DETECTION, static_cast<uint8_t>(detection), 0);
  }
  void add_start_component(::flatbuffers::Offset<::flatbuffers::String> start_component) {
    fbb_.AddOffset(PortConfig::VT_START_COMPONENT, start_component);
  }
  void add_sequences(::flatbuffers::Offset<mqt::scpd::flatbuffers::config::PortSequences> sequences) {
    fbb_.AddOffset(PortConfig::VT_SEQUENCES, sequences);
  }
  explicit PortConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PortConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PortConfig>(end);
    fbb_.Required(o, PortConfig::VT_PATTERNS);
    return o;
  }
};

inline ::flatbuffers::Offset<PortConfig> CreatePortConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<mqt::scpd::flatbuffers::config::PortPatterns> patterns = 0,
    mqt::scpd::flatbuffers::config::PortDetection detection = mqt::scpd::flatbuffers::config::PortDetection::Manual,
    ::flatbuffers::Offset<::flatbuffers::String> start_component = 0,
    ::flatbuffers::Offset<mqt::scpd::flatbuffers::config::PortSequences> sequences = 0) {
  PortConfigBuilder builder_(_fbb);
  builder_.add_sequences(sequences);
  builder_.add_start_component(start_component);
  builder_.add_patterns(patterns);
  builder_.add_detection(detection);
  return builder_.Finish();
}

struct PortConfig::Traits {
  using type = PortConfig;
  static auto constexpr Create = CreatePortConfig;
};

inline ::flatbuffers::Offset<PortConfig> CreatePortConfigDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<mqt::scpd::flatbuffers::config::PortPatterns> patterns = 0,
    mqt::scpd::flatbuffers::config::PortDetection detection = mqt::scpd::flatbuffers::config::PortDetection::Manual,
    const char *start_component = nullptr,
    ::flatbuffers::Offset<mqt::scpd::flatbuffers::config::PortSequences> sequences = 0) {
  auto start_component__ = start_component ? _fbb.CreateString(start_component) : 0;
  return mqt::scpd::flatbuffers::config::CreatePortConfig(
      _fbb,
      patterns,
      detection,
      start_component__,
      sequences);
}

::flatbuffers::Offset<PortConfig> CreatePortConfig(::flatbuffers::FlatBufferBuilder &_fbb, const PortConfigT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct GridParamsT : public ::flatbuffers::NativeTable {
  typedef GridParams TableType;
  uint32_t capacity_cells_x = 50;
  uint32_t capacity_cells_y = 0;
  uint32_t launcher_offset_x = 15;
  uint32_t launcher_offset_y = 15;
};

struct GridParams FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GridParamsT NativeTableType;
  typedef GridParamsBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CAPACITY_CELLS_X = 4,
    VT_CAPACITY_CELLS_Y = 6,
    VT_LAUNCHER_OFFSET_X = 8,
    VT_LAUNCHER_OFFSET_Y = 10
  };
  uint32_t capacity_cells_x() const {
    return GetField<uint32_t>(VT_CAPACITY_CELLS_X, 50);
  }
  /// Zero derives the value from the chip aspect ratio.
  uint32_t capacity_cells_y() const {
    return GetField<uint32_t>(VT_CAPACITY_CELLS_Y, 0);
  }
  uint32_t launcher_offset_x() const {
    return GetField<uint32_t>(VT_LAUNCHER_OFFSET_X, 15);
  }
  uint32_t launcher_offset_y() const {
    return GetField<uint32_t>(VT_LAUNCHER_OFFSET_Y, 15);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CAPACITY_CELLS_X, 4) &&
           VerifyField<uint32_t>(verifier, VT_CAPACITY_CELLS_Y, 4) &&
           VerifyField<uint32_t>(verifier, VT_LAUNCHER_OFFSET_X, 4) &&
           VerifyField<uint32_t>(verifier, VT_LAUNCHER_OFFSET_Y, 4) &&
           verifier.EndTable();
  }
  GridParamsT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(GridParamsT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<GridParams> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GridParamsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct GridParamsBuilder {
  typedef GridParams Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_capacity_cells_x(uint32_t capacity_cells_x) {
    fbb_.AddElement<uint32_t>(GridParams::VT_CAPACITY_CELLS_X, capacity_cells_x, 50);
  }
  void add_capacity_cells_y(uint32_t capacity_cells_y) {
    fbb_.AddElement<uint32_t>(GridParams::VT_CAPACITY_CELLS_Y, capacity_cells_y, 0);
  }
  void add_launcher_offset_x(uint32_t launcher_offset_x) {
    fbb_.AddElement<uint32_t>(GridParams::VT_LAUNCHER_OFFSET_X, launcher_offset_x, 15);
  }
  void add_launcher_offset_y(uint32_t launcher_offset_y) {
    fbb_.AddElement<uint32_t>(GridParams::VT_LAUNCHER_OFFSET_Y, launcher_offset_y, 15);
  }
  explicit GridParamsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GridParams> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GridParams>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GridParams> CreateGridParams(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t capacity_cells_x = 50,
    uint32_t capacity_cells_y = 0,
    uint32_t launcher_offset_x = 15,
    uint32_t launcher_offset_y = 15) {
  GridParamsBuilder builder_(_fbb);
  builder_.add_launcher_offset_y(launcher_offset_y);
  builder_.add_launcher_offset_x(launcher_offset_x);
  builder_.add_capacity_cells_y(capacity_cells_y);
  builder_.add_capacity_cells_x(capacity_cells_x);
  return builder_.Finish();
}

struct GridParams::Traits {
  using type = GridParams;
  static auto constexpr Create = CreateGridParams;
};

::flatbuffers::Offset<GridParams> CreateGridParams(::flatbuffers::FlatBufferBuilder &_fbb, const GridParamsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ConfigT : public ::flatbuffers::NativeTable {
  typedef Config TableType;
  std::string chip_input{};
  std::unique_ptr<mqt::scpd::flatbuffers::config::PortConfigT> ports{};
  std::unique_ptr<mqt::scpd::flatbuffers::design::DesignRulesT> rules{};
  std::unique_ptr<mqt::scpd::flatbuffers::config::GridParamsT> grid{};
  ConfigT() = default;
  ConfigT(const ConfigT &o);
  ConfigT(ConfigT&&) FLATBUFFERS_NOEXCEPT = default;
  ConfigT &operator=(ConfigT o) FLATBUFFERS_NOEXCEPT;
};

/// The whole run configuration.
struct Config FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConfigT NativeTableType;
  typedef ConfigBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CHIP_INPUT = 4,
    VT_PORTS = 6,
    VT_RULES = 8,
    VT_GRID = 10
  };
  /// The chip input path, relative to the configuration file.
  const ::flatbuffers::String *chip_input() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CHIP_INPUT);
  }
  const mqt::scpd::flatbuffers::config::PortConfig *ports() const {
    return GetPointer<const mqt::scpd::flatbuffers::config::PortConfig *>(VT_PORTS);
  }
  const mqt::scpd::flatbuffers::design::DesignRules *rules() const {
    return GetPointer<const mqt::scpd::flatbuffers::design::DesignRules *>(VT_RULES);
  }
  const mqt::scpd::flatbuffers::config::GridParams *grid() const {
    return GetPointer<const mqt::scpd::flatbuffers::config::GridParams *>(VT_GRID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_CHIP_INPUT) &&
           verifier.VerifyString(chip_input()) &&
           VerifyOffsetRequired(verifier, VT_PORTS) &&
           verifier.VerifyTable(ports()) &&
           VerifyOffsetRequired(verifier, VT_RULES) &&
           verifier.VerifyTable(rules()) &&
           VerifyOffset(verifier, VT_GRID) &&
           verifier.VerifyTable(grid()) &&
           verifier.EndTable();
  }
  ConfigT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ConfigT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Config> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConfigT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ConfigBuilder {
  typedef Config Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_chip_input(::flatbuffers::Offset<::flatbuffers::String> chip_input) {
    fbb_.AddOffset(Config::VT_CHIP_INPUT, chip_input);
  }
  void add_ports(::flatbuffers::Offset<mqt::scpd::flatbuffers::config::PortConfig> ports) {
    fbb_.AddOffset(Config::VT_PORTS, ports);
  }
  void add_rules(::flatbuffers::Offset<mqt::scpd::flatbuffers::design::DesignRules> rules) {
    fbb_.AddOffset(Config::VT_RULES, rules);
  }
  void add_grid(::flatbuffers::Offset<mqt::scpd::flatbuffers::config::GridParams> grid) {
    fbb_.AddOffset(Config::VT_GRID, grid);
  }
  explicit ConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Config> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Config>(end);
    fbb_.Required(o, Config::VT_CHIP_INPUT);
    fbb_.Required(o, Config::VT_PORTS);
    fbb_.Required(o, Config::VT_RULES);
    return o;
  }
};

inline ::flatbuffers::Offset<Config> CreateConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> chip_input = 0,
    ::flatbuffers::Offset<mqt::scpd::flatbuffers::config::PortConfig> ports = 0,
    ::flatbuffers::Offset<mqt::scpd::flatbuffers::design::DesignRules> rules = 0,
    ::flatbuffers::Offset<mqt::scpd::flatbuffers::config::GridParams> grid = 0) {
  ConfigBuilder builder_(_fbb);
  builder_.add_grid(grid);
  builder_.add_rules(rules);
  builder_.add_ports(ports);
  builder_.add_chip_input(chip_input);
  return builder_.Finish();
}

struct Config::Traits {
  using type = Config;
  static auto constexpr Create = CreateConfig;
};

inline ::flatbuffers::Offset<Config> CreateConfigDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *chip_input = nullptr,
    ::flatbuffers::Offset<mqt::scpd::flatbuffers::config::PortConfig> ports = 0,
    ::flatbuffers::Offset<mqt::scpd::flatbuffers::design::DesignRules> rules = 0,
    ::flatbuffers::Offset<mqt::scpd::flatbuffers::config::GridParams> grid = 0) {
  auto chip_input__ = chip_input ? _fbb.CreateString(chip_input) : 0;
  return mqt::scpd::flatbuffers::config::CreateConfig(
      _fbb,
      chip_input__,
      ports,
      rules,
      grid);
}

::flatbuffers::Offset<Config> CreateConfig(::flatbuffers::FlatBufferBuilder &_fbb, const ConfigT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const PortPatternsT &lhs, const PortPatternsT &rhs) {
  return
      (lhs.launcher == rhs.launcher) &&
      (lhs.resonator == rhs.resonator) &&
      (lhs.conventional == rhs.conventional);
}

inline bool operator!=(const PortPatternsT &lhs, const PortPatternsT &rhs) {
    return !(lhs == rhs);
}


inline PortPatternsT *PortPatterns::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<PortPatternsT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PortPatterns::UnPackTo(PortPatternsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = launcher(); if (_e) _o->launcher = _e->str(); }
  { auto _e = resonator(); if (_e) _o->resonator = _e->str(); }
  { auto _e = conventional(); if (_e) _o->conventional = _e->str(); }
}

inline ::flatbuffers::Offset<PortPatterns> CreatePortPatterns(::flatbuffers::FlatBufferBuilder &_fbb, const PortPatternsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return PortPatterns::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PortPatterns> PortPatterns::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PortPatternsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PortPatternsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _launcher = _fbb.CreateString(_o->launcher);
  auto _resonator = _fbb.CreateString(_o->resonator);
  auto _conventional = _fbb.CreateString(_o->conventional);
  return mqt::scpd::flatbuffers::config::CreatePortPatterns(
      _fbb,
      _launcher,
      _resonator,
      _conventional);
}


inline bool operator==(const PortSequencesT &lhs, const PortSequencesT &rhs) {
  return
      (lhs.all_outer == rhs.all_outer) &&
      (lhs.fixed_outer == rhs.fixed_outer);
}

inline bool operator!=(const PortSequencesT &lhs, const PortSequencesT &rhs) {
    return !(lhs == rhs);
}


inline PortSequencesT *PortSequences::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<PortSequencesT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PortSequences::UnPackTo(PortSequencesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = all_outer(); if (_e) { _o->all_outer.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->all_outer[_i] = _e->Get(_i)->str(); } } else { _o->all_outer.resize(0); } }
  { auto _e = fixed_outer(); if (_e) { _o->fixed_outer.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->fixed_outer[_i] = _e->Get(_i)->str(); } } else { _o->fixed_outer.resize(0); } }
}

inline ::flatbuffers::Offset<PortSequences> CreatePortSequences(::flatbuffers::FlatBufferBuilder &_fbb, const PortSequencesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return PortSequences::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PortSequences> PortSequences::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PortSequencesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PortSequencesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _all_outer = _fbb.CreateVectorOfStrings(_o->all_outer);
  auto _fixed_outer = _fbb.CreateVectorOfStrings(_o->fixed_outer);
  return mqt::scpd::flatbuffers::config::CreatePortSequences(
      _fbb,
      _all_outer,
      _fixed_outer);
}


inline bool operator==(const PortConfigT &lhs, const PortConfigT &rhs) {
  return
      ((lhs.patterns == rhs.patterns) || (lhs.patterns && rhs.patterns && *lhs.patterns == *rhs.patterns)) &&
      (lhs.detection == rhs.detection) &&
      (lhs.start_component == rhs.start_component) &&
      ((lhs.sequences == rhs.sequences) || (lhs.sequences && rhs.sequences && *lhs.sequences == *rhs.sequences));
}

inline bool operator!=(const PortConfigT &lhs, const PortConfigT &rhs) {
    return !(lhs == rhs);
}


inline PortConfigT::PortConfigT(const PortConfigT &o)
      : patterns((o.patterns) ? new mqt::scpd::flatbuffers::config::PortPatternsT(*o.patterns) : nullptr),
        detection(o.detection),
        start_component(o.start_component),
        sequences((o.sequences) ? new mqt::scpd::flatbuffers::config::PortSequencesT(*o.sequences) : nullptr) {
}

inline PortConfigT &PortConfigT::operator=(PortConfigT o) FLATBUFFERS_NOEXCEPT {
  std::swap(patterns, o.patterns);
  std::swap(detection, o.detection);
  std::swap(start_component, o.start_component);
  std::swap(sequences, o.sequences);
  return *this;
}

inline PortConfigT *PortConfig::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<PortConfigT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PortConfig::UnPackTo(PortConfigT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = patterns(); if (_e) { if(_o->patterns) { _e->UnPackTo(_o->patterns.get(), _resolver); } else { _o->patterns = std::unique_ptr<mqt::scpd::flatbuffers::config::PortPatternsT>(_e->UnPack(_resolver)); } } else if (_o->patterns) { _o->patterns.reset(); } }
  { auto _e = detection(); _o->detection = _e; }
  { auto _e = start_component(); if (_e) _o->start_component = _e->str(); }
  { auto _e = sequences(); if (_e) { if(_o->sequences) { _e->UnPackTo(_o->sequences.get(), _resolver); } else { _o->sequences = std::unique_ptr<mqt::scpd::flatbuffers::config::PortSequencesT>(_e->UnPack(_resolver)); } } else if (_o->sequences) { _o->sequences.reset(); } }
}

inline ::flatbuffers::Offset<PortConfig> CreatePortConfig(::flatbuffers::FlatBufferBuilder &_fbb, const PortConfigT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return PortConfig::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PortConfig> PortConfig::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PortConfigT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PortConfigT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _patterns = _o->patterns ? CreatePortPatterns(_fbb, _o->patterns.get(), _rehasher) : 0;
  auto _detection = _o->detection;
  auto _start_component = _o->start_component.empty() ? 0 : _fbb.CreateString(_o->start_component);
  auto _sequences = _o->sequences ? CreatePortSequences(_fbb, _o->sequences.get(), _rehasher) : 0;
  return mqt::scpd::flatbuffers::config::CreatePortConfig(
      _fbb,
      _patterns,
      _detection,
      _start_component,
      _sequences);
}


inline bool operator==(const GridParamsT &lhs, const GridParamsT &rhs) {
  return
      (lhs.capacity_cells_x == rhs.capacity_cells_x) &&
      (lhs.capacity_cells_y == rhs.capacity_cells_y) &&
      (lhs.launcher_offset_x == rhs.launcher_offset_x) &&
      (lhs.launcher_offset_y == rhs.launcher_offset_y);
}

inline bool operator!=(const GridParamsT &lhs, const GridParamsT &rhs) {
    return !(lhs == rhs);
}


inline GridParamsT *GridParams::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<GridParamsT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void GridParams::UnPackTo(GridParamsT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = capacity_cells_x(); _o->capacity_cells_x = _e; }
  { auto _e = capacity_cells_y(); _o->capacity_cells_y = _e; }
  { auto _e = launcher_offset_x(); _o->launcher_offset_x = _e; }
  { auto _e = launcher_offset_y(); _o->launcher_offset_y = _e; }
}

inline ::flatbuffers::Offset<GridParams> CreateGridParams(::flatbuffers::FlatBufferBuilder &_fbb, const GridParamsT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return GridParams::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<GridParams> GridParams::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const GridParamsT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const GridParamsT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _capacity_cells_x = _o->capacity_cells_x;
  auto _capacity_cells_y = _o->capacity_cells_y;
  auto _launcher_offset_x = _o->launcher_offset_x;
  auto _launcher_offset_y = _o->launcher_offset_y;
  return mqt::scpd::flatbuffers::config::CreateGridParams(
      _fbb,
      _capacity_cells_x,
      _capacity_cells_y,
      _launcher_offset_x,
      _launcher_offset_y);
}


inline bool operator==(const ConfigT &lhs, const ConfigT &rhs) {
  return
      (lhs.chip_input == rhs.chip_input) &&
      ((lhs.ports == rhs.ports) || (lhs.ports && rhs.ports && *lhs.ports == *rhs.ports)) &&
      ((lhs.rules == rhs.rules) || (lhs.rules && rhs.rules && *lhs.rules == *rhs.rules)) &&
      ((lhs.grid == rhs.grid) || (lhs.grid && rhs.grid && *lhs.grid == *rhs.grid));
}

inline bool operator!=(const ConfigT &lhs, const ConfigT &rhs) {
    return !(lhs == rhs);
}


inline ConfigT::ConfigT(const ConfigT &o)
      : chip_input(o.chip_input),
        ports((o.ports) ? new mqt::scpd::flatbuffers::config::PortConfigT(*o.ports) : nullptr),
        rules((o.rules) ? new mqt::scpd::flatbuffers::design::DesignRulesT(*o.rules) : nullptr),
        grid((o.grid) ? new mqt::scpd::flatbuffers::config::GridParamsT(*o.grid) : nullptr) {
}

inline ConfigT &ConfigT::operator=(ConfigT o) FLATBUFFERS_NOEXCEPT {
  std::swap(chip_input, o.chip_input);
  std::swap(ports, o.ports);
  std::swap(rules, o.rules);
  std::swap(grid, o.grid);
  return *this;
}

inline ConfigT *Config::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<ConfigT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Config::UnPackTo(ConfigT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = chip_input(); if (_e) _o->chip_input = _e->str(); }
  { auto _e = ports(); if (_e) { if(_o->ports) { _e->UnPackTo(_o->ports.get(), _resolver); } else { _o->ports = std::unique_ptr<mqt::scpd::flatbuffers::config::PortConfigT>(_e->UnPack(_resolver)); } } else if (_o->ports) { _o->ports.reset(); } }
  { auto _e = rules(); if (_e) { if(_o->rules) { _e->UnPackTo(_o->rules.get(), _resolver); } else { _o->rules = std::unique_ptr<mqt::scpd::flatbuffers::design::DesignRulesT>(_e->UnPack(_resolver)); } } else if (_o->rules) { _o->rules.reset(); } }
  { auto _e = grid(); if (_e) { if(_o->grid) { _e->UnPackTo(_o->grid.get(), _resolver); } else { _o->grid = std::unique_ptr<mqt::scpd::flatbuffers::config::GridParamsT>(_e->UnPack(_resolver)); } } else if (_o->grid) { _o->grid.reset(); } }
}

inline ::flatbuffers::Offset<Config> CreateConfig(::flatbuffers::FlatBufferBuilder &_fbb, const ConfigT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Config::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Config> Config::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConfigT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ConfigT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _chip_input = _fbb.CreateString(_o->chip_input);
  auto _ports = _o->ports ? CreatePortConfig(_fbb, _o->ports.get(), _rehasher) : 0;
  auto _rules = _o->rules ? CreateDesignRules(_fbb, _o->rules.get(), _rehasher) : 0;
  auto _grid = _o->grid ? CreateGridParams(_fbb, _o->grid.get(), _rehasher) : 0;
  return mqt::scpd::flatbuffers::config::CreateConfig(
      _fbb,
      _chip_input,
      _ports,
      _rules,
      _grid);
}

}  // namespace config
}  // namespace flatbuffers
}  // namespace scpd
}  // namespace mqt

#endif  // FLATBUFFERS_GENERATED_CONFIG_MQT_SCPD_FLATBUFFERS_CONFIG_H_
