// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DESIGN_MQT_SCPD_FLATBUFFERS_DESIGN_H_
#define FLATBUFFERS_GENERATED_DESIGN_MQT_SCPD_FLATBUFFERS_DESIGN_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "mqt-scpd/flatbuffers/geometry.hpp"

namespace mqt {
namespace scpd {
namespace flatbuffers {
namespace design {

struct PortRef;

struct ConnectionRef;

struct Port;
struct PortBuilder;
struct PortT;

struct Chip;
struct ChipBuilder;
struct ChipT;

struct Connection;
struct ConnectionBuilder;
struct ConnectionT;

struct DesignRules;
struct DesignRulesBuilder;
struct DesignRulesT;

struct CpwCoupler;
struct CpwCouplerBuilder;
struct CpwCouplerT;

struct Bridge;
struct BridgeBuilder;
struct BridgeT;

bool operator==(const PortRef &lhs, const PortRef &rhs);
bool operator!=(const PortRef &lhs, const PortRef &rhs);
bool operator==(const ConnectionRef &lhs, const ConnectionRef &rhs);
bool operator!=(const ConnectionRef &lhs, const ConnectionRef &rhs);
bool operator==(const PortT &lhs, const PortT &rhs);
bool operator!=(const PortT &lhs, const PortT &rhs);
bool operator==(const ChipT &lhs, const ChipT &rhs);
bool operator!=(const ChipT &lhs, const ChipT &rhs);
bool operator==(const ConnectionT &lhs, const ConnectionT &rhs);
bool operator!=(const ConnectionT &lhs, const ConnectionT &rhs);
bool operator==(const DesignRulesT &lhs, const DesignRulesT &rhs);
bool operator!=(const DesignRulesT &lhs, const DesignRulesT &rhs);
bool operator==(const CpwCouplerT &lhs, const CpwCouplerT &rhs);
bool operator!=(const CpwCouplerT &lhs, const CpwCouplerT &rhs);
bool operator==(const BridgeT &lhs, const BridgeT &rhs);
bool operator!=(const BridgeT &lhs, const BridgeT &rhs);

/// What a port is, before anything is decided. Set at load, from the role
/// patterns in the configuration, or by coupler insertion for a Coupler port.
enum class UnassignedRole : uint8_t {
  Unset = 0,
  Launcher = 1,
  Resonator = 2,
  Conventional = 3,
  /// Created by the Final stage's coupler insertion. No pattern produces it.
  Coupler = 4,
  MIN = Unset,
  MAX = Coupler
};

inline const UnassignedRole (&EnumValuesUnassignedRole())[5] {
  static const UnassignedRole values[] = {
    UnassignedRole::Unset,
    UnassignedRole::Launcher,
    UnassignedRole::Resonator,
    UnassignedRole::Conventional,
    UnassignedRole::Coupler
  };
  return values;
}

inline const char * const *EnumNamesUnassignedRole() {
  static const char * const names[6] = {
    "Unset",
    "Launcher",
    "Resonator",
    "Conventional",
    "Coupler",
    nullptr
  };
  return names;
}

inline const char *EnumNameUnassignedRole(UnassignedRole e) {
  if (::flatbuffers::IsOutRange(e, UnassignedRole::Unset, UnassignedRole::Coupler)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesUnassignedRole()[index];
}

/// What a port does in the solved design. Set by the Assignment stage, except
/// ResonatorSource, whose port the Final stage creates with the coupler.
enum class AssignedRole : uint8_t {
  Unset = 0,
  FeedlineSource = 1,
  FeedlineTarget = 2,
  ResonatorSource = 3,
  ResonatorTarget = 4,
  ConventionalSource = 5,
  ConventionalTarget = 6,
  MIN = Unset,
  MAX = ConventionalTarget
};

inline const AssignedRole (&EnumValuesAssignedRole())[7] {
  static const AssignedRole values[] = {
    AssignedRole::Unset,
    AssignedRole::FeedlineSource,
    AssignedRole::FeedlineTarget,
    AssignedRole::ResonatorSource,
    AssignedRole::ResonatorTarget,
    AssignedRole::ConventionalSource,
    AssignedRole::ConventionalTarget
  };
  return values;
}

inline const char * const *EnumNamesAssignedRole() {
  static const char * const names[8] = {
    "Unset",
    "FeedlineSource",
    "FeedlineTarget",
    "ResonatorSource",
    "ResonatorTarget",
    "ConventionalSource",
    "ConventionalTarget",
    nullptr
  };
  return names;
}

inline const char *EnumNameAssignedRole(AssignedRole e) {
  if (::flatbuffers::IsOutRange(e, AssignedRole::Unset, AssignedRole::ConventionalTarget)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAssignedRole()[index];
}

/// The eight-way rotation of a placed component.
enum class Rotation : uint8_t {
  Unset = 0,
  R0 = 1,
  R45 = 2,
  R90 = 3,
  R135 = 4,
  R180 = 5,
  R225 = 6,
  R270 = 7,
  R315 = 8,
  MIN = Unset,
  MAX = R315
};

inline const Rotation (&EnumValuesRotation())[9] {
  static const Rotation values[] = {
    Rotation::Unset,
    Rotation::R0,
    Rotation::R45,
    Rotation::R90,
    Rotation::R135,
    Rotation::R180,
    Rotation::R225,
    Rotation::R270,
    Rotation::R315
  };
  return values;
}

inline const char * const *EnumNamesRotation() {
  static const char * const names[10] = {
    "Unset",
    "R0",
    "R45",
    "R90",
    "R135",
    "R180",
    "R225",
    "R270",
    "R315",
    nullptr
  };
  return names;
}

inline const char *EnumNameRotation(Rotation e) {
  if (::flatbuffers::IsOutRange(e, Rotation::Unset, Rotation::R315)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRotation()[index];
}

/// A dense index into Chip.ports. A label is resolved to a PortRef once, at
/// load. Ports are appended and never reordered, so a PortRef stays valid for
/// the life of a run.
FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) PortRef FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t index_;

 public:
  struct Traits;
  PortRef()
      : index_(0) {
  }
  PortRef(uint32_t _index)
      : index_(::flatbuffers::EndianScalar(_index)) {
  }
  uint32_t index() const {
    return ::flatbuffers::EndianScalar(index_);
  }
};
FLATBUFFERS_STRUCT_END(PortRef, 4);

inline bool operator==(const PortRef &lhs, const PortRef &rhs) {
  return
      (lhs.index() == rhs.index());
}

inline bool operator!=(const PortRef &lhs, const PortRef &rhs) {
    return !(lhs == rhs);
}


struct PortRef::Traits {
  using type = PortRef;
};

/// A dense index into the connections of the Assignment stage's output.
FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) ConnectionRef FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t index_;

 public:
  struct Traits;
  ConnectionRef()
      : index_(0) {
  }
  ConnectionRef(uint32_t _index)
      : index_(::flatbuffers::EndianScalar(_index)) {
  }
  uint32_t index() const {
    return ::flatbuffers::EndianScalar(index_);
  }
};
FLATBUFFERS_STRUCT_END(ConnectionRef, 4);

inline bool operator==(const ConnectionRef &lhs, const ConnectionRef &rhs) {
  return
      (lhs.index() == rhs.index());
}

inline bool operator!=(const ConnectionRef &lhs, const ConnectionRef &rhs) {
    return !(lhs == rhs);
}


struct ConnectionRef::Traits {
  using type = ConnectionRef;
};

struct PortT : public ::flatbuffers::NativeTable {
  typedef Port TableType;
  std::string label{};
  mqt::scpd::flatbuffers::geometry::Point center{};
  double orientation = 0.0;
  mqt::scpd::flatbuffers::design::UnassignedRole role = mqt::scpd::flatbuffers::design::UnassignedRole::Unset;
};

/// A port of the chip. The label is the only name the input has; no algorithm
/// parses it.
struct Port FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PortT NativeTableType;
  typedef PortBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LABEL = 4,
    VT_CENTER = 6,
    VT_ORIENTATION = 8,
    VT_ROLE = 10
  };
  const ::flatbuffers::String *label() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LABEL);
  }
  const mqt::scpd::flatbuffers::geometry::Point *center() const {
    return GetStruct<const mqt::scpd::flatbuffers::geometry::Point *>(VT_CENTER);
  }
  /// Degrees, as the chip input carries it.
  double orientation() const {
    return GetField<double>(VT_ORIENTATION, 0.0);
  }
  mqt::scpd::flatbuffers::design::UnassignedRole role() const {
    return static_cast<mqt::scpd::flatbuffers::design::UnassignedRole>(GetField<uint8_t>(VT_ROLE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_LABEL) &&
           verifier.VerifyString(label()) &&
           VerifyFieldRequired<mqt::scpd::flatbuffers::geometry::Point>(verifier, VT_CENTER, 8) &&
           VerifyField<double>(verifier, VT_ORIENTATION, 8) &&
           VerifyField<uint8_t>(verifier, VT_ROLE, 1) &&
           verifier.EndTable();
  }
  PortT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PortT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Port> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PortT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PortBuilder {
  typedef Port Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_label(::flatbuffers::Offset<::flatbuffers::String> label) {
    fbb_.AddOffset(Port::VT_LABEL, label);
  }
  void add_center(const mqt::scpd::flatbuffers::geometry::Point *center) {
    fbb_.AddStruct(Port::VT_CENTER, center);
  }
  void add_orientation(double orientation) {
    fbb_.AddElement<double>(Port::VT_ORIENTATION, orientation, 0.0);
  }
  void add_role(mqt::scpd::flatbuffers::design::UnassignedRole role) {
    fbb_.AddElement<uint8_t>(Port::VT_ROLE, static_cast<uint8_t>(role), 0);
  }
  explicit PortBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Port> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Port>(end);
    fbb_.Required(o, Port::VT_LABEL);
    fbb_.Required(o, Port::VT_CENTER);
    return o;
  }
};

inline ::flatbuffers::Offset<Port> CreatePort(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> label = 0,
    const mqt::scpd::flatbuffers::geometry::Point *center = nullptr,
    double orientation = 0.0,
    mqt::scpd::flatbuffers::design::UnassignedRole role = mqt::scpd::flatbuffers::design::UnassignedRole::Unset) {
  PortBuilder builder_(_fbb);
  builder_.add_orientation(orientation);
  builder_.add_center(center);
  builder_.add_label(label);
  builder_.add_role(role);
  return builder_.Finish();
}

struct Port::Traits {
  using type = Port;
  static auto constexpr Create = CreatePort;
};

inline ::flatbuffers::Offset<Port> CreatePortDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *label = nullptr,
    const mqt::scpd::flatbuffers::geometry::Point *center = nullptr,
    double orientation = 0.0,
    mqt::scpd::flatbuffers::design::UnassignedRole role = mqt::scpd::flatbuffers::design::UnassignedRole::Unset) {
  auto label__ = label ? _fbb.CreateString(label) : 0;
  return mqt::scpd::flatbuffers::design::CreatePort(
      _fbb,
      label__,
      center,
      orientation,
      role);
}

::flatbuffers::Offset<Port> CreatePort(::flatbuffers::FlatBufferBuilder &_fbb, const PortT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ChipT : public ::flatbuffers::NativeTable {
  typedef Chip TableType;
  std::vector<std::unique_ptr<mqt::scpd::flatbuffers::geometry::PolygonT>> obstacles{};
  std::vector<std::unique_ptr<mqt::scpd::flatbuffers::design::PortT>> ports{};
  ChipT() = default;
  ChipT(const ChipT &o);
  ChipT(ChipT&&) FLATBUFFERS_NOEXCEPT = default;
  ChipT &operator=(ChipT o) FLATBUFFERS_NOEXCEPT;
};

/// The chip: obstacle geometry and ports, exactly as the input carries them.
struct Chip FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ChipT NativeTableType;
  typedef ChipBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBSTACLES = 4,
    VT_PORTS = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Polygon>> *obstacles() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Polygon>> *>(VT_OBSTACLES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::design::Port>> *ports() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::design::Port>> *>(VT_PORTS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_OBSTACLES) &&
           verifier.VerifyVector(obstacles()) &&
           verifier.VerifyVectorOfTables(obstacles()) &&
           VerifyOffsetRequired(verifier, VT_PORTS) &&
           verifier.VerifyVector(ports()) &&
           verifier.VerifyVectorOfTables(ports()) &&
           verifier.EndTable();
  }
  ChipT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ChipT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Chip> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ChipT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ChipBuilder {
  typedef Chip Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_obstacles(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Polygon>>> obstacles) {
    fbb_.AddOffset(Chip::VT_OBSTACLES, obstacles);
  }
  void add_ports(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::design::Port>>> ports) {
    fbb_.AddOffset(Chip::VT_PORTS, ports);
  }
  explicit ChipBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Chip> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Chip>(end);
    fbb_.Required(o, Chip::VT_OBSTACLES);
    fbb_.Required(o, Chip::VT_PORTS);
    return o;
  }
};

inline ::flatbuffers::Offset<Chip> CreateChip(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Polygon>>> obstacles = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::design::Port>>> ports = 0) {
  ChipBuilder builder_(_fbb);
  builder_.add_ports(ports);
  builder_.add_obstacles(obstacles);
  return builder_.Finish();
}

struct Chip::Traits {
  using type = Chip;
  static auto constexpr Create = CreateChip;
};

inline ::flatbuffers::Offset<Chip> CreateChipDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Polygon>> *obstacles = nullptr,
    const std::vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::design::Port>> *ports = nullptr) {
  auto obstacles__ = obstacles ? _fbb.CreateVector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Polygon>>(*obstacles) : 0;
  auto ports__ = ports ? _fbb.CreateVector<::flatbuffers::Offset<mqt::scpd::flatbuffers::design::Port>>(*ports) : 0;
  return mqt::scpd::flatbuffers::design::CreateChip(
      _fbb,
      obstacles__,
      ports__);
}

::flatbuffers::Offset<Chip> CreateChip(::flatbuffers::FlatBufferBuilder &_fbb, const ChipT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ConnectionT : public ::flatbuffers::NativeTable {
  typedef Connection TableType;
  std::unique_ptr<mqt::scpd::flatbuffers::design::PortRef> source{};
  mqt::scpd::flatbuffers::design::PortRef target{};
  mqt::scpd::flatbuffers::design::AssignedRole source_role = mqt::scpd::flatbuffers::design::AssignedRole::Unset;
  mqt::scpd::flatbuffers::design::AssignedRole target_role = mqt::scpd::flatbuffers::design::AssignedRole::Unset;
  ConnectionT() = default;
  ConnectionT(const ConnectionT &o);
  ConnectionT(ConnectionT&&) FLATBUFFERS_NOEXCEPT = default;
  ConnectionT &operator=(ConnectionT o) FLATBUFFERS_NOEXCEPT;
};

/// One endpoint pair of the solved design.
struct Connection FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ConnectionT NativeTableType;
  typedef ConnectionBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SOURCE = 4,
    VT_TARGET = 6,
    VT_SOURCE_ROLE = 8,
    VT_TARGET_ROLE = 10
  };
  /// Absent for a resonator until the Final stage inserts the coupler that
  /// carries the ResonatorSource role.
  const mqt::scpd::flatbuffers::design::PortRef *source() const {
    return GetStruct<const mqt::scpd::flatbuffers::design::PortRef *>(VT_SOURCE);
  }
  const mqt::scpd::flatbuffers::design::PortRef *target() const {
    return GetStruct<const mqt::scpd::flatbuffers::design::PortRef *>(VT_TARGET);
  }
  mqt::scpd::flatbuffers::design::AssignedRole source_role() const {
    return static_cast<mqt::scpd::flatbuffers::design::AssignedRole>(GetField<uint8_t>(VT_SOURCE_ROLE, 0));
  }
  mqt::scpd::flatbuffers::design::AssignedRole target_role() const {
    return static_cast<mqt::scpd::flatbuffers::design::AssignedRole>(GetField<uint8_t>(VT_TARGET_ROLE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<mqt::scpd::flatbuffers::design::PortRef>(verifier, VT_SOURCE, 4) &&
           VerifyFieldRequired<mqt::scpd::flatbuffers::design::PortRef>(verifier, VT_TARGET, 4) &&
           VerifyField<uint8_t>(verifier, VT_SOURCE_ROLE, 1) &&
           VerifyField<uint8_t>(verifier, VT_TARGET_ROLE, 1) &&
           verifier.EndTable();
  }
  ConnectionT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ConnectionT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Connection> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ConnectionBuilder {
  typedef Connection Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_source(const mqt::scpd::flatbuffers::design::PortRef *source) {
    fbb_.AddStruct(Connection::VT_SOURCE, source);
  }
  void add_target(const mqt::scpd::flatbuffers::design::PortRef *target) {
    fbb_.AddStruct(Connection::VT_TARGET, target);
  }
  void add_source_role(mqt::scpd::flatbuffers::design::AssignedRole source_role) {
    fbb_.AddElement<uint8_t>(Connection::VT_SOURCE_ROLE, static_cast<uint8_t>(source_role), 0);
  }
  void add_target_role(mqt::scpd::flatbuffers::design::AssignedRole target_role) {
    fbb_.AddElement<uint8_t>(Connection::VT_TARGET_ROLE, static_cast<uint8_t>(target_role), 0);
  }
  explicit ConnectionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Connection> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Connection>(end);
    fbb_.Required(o, Connection::VT_TARGET);
    return o;
  }
};

inline ::flatbuffers::Offset<Connection> CreateConnection(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const mqt::scpd::flatbuffers::design::PortRef *source = nullptr,
    const mqt::scpd::flatbuffers::design::PortRef *target = nullptr,
    mqt::scpd::flatbuffers::design::AssignedRole source_role = mqt::scpd::flatbuffers::design::AssignedRole::Unset,
    mqt::scpd::flatbuffers::design::AssignedRole target_role = mqt::scpd::flatbuffers::design::AssignedRole::Unset) {
  ConnectionBuilder builder_(_fbb);
  builder_.add_target(target);
  builder_.add_source(source);
  builder_.add_target_role(target_role);
  builder_.add_source_role(source_role);
  return builder_.Finish();
}

struct Connection::Traits {
  using type = Connection;
  static auto constexpr Create = CreateConnection;
};

::flatbuffers::Offset<Connection> CreateConnection(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DesignRulesT : public ::flatbuffers::NativeTable {
  typedef DesignRules TableType;
  double min_wire_spacing = 0.0;
  double min_obstacle_spacing = 0.0;
  double min_bend_radius = 0.0;
  double min_straight_length = 0.0;
  double target_resonator_length = 0.0;
  double resonator_length_tolerance = 0.0;
  uint32_t max_feedline_utilization = 0;
  uint32_t feedline_terminations = 0;
};

/// The design rules. Every rule is a length in layout units, held once and
/// converted to cells only through cells_for. See decision 0019.
struct DesignRules FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DesignRulesT NativeTableType;
  typedef DesignRulesBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MIN_WIRE_SPACING = 4,
    VT_MIN_OBSTACLE_SPACING = 6,
    VT_MIN_BEND_RADIUS = 8,
    VT_MIN_STRAIGHT_LENGTH = 10,
    VT_TARGET_RESONATOR_LENGTH = 12,
    VT_RESONATOR_LENGTH_TOLERANCE = 14,
    VT_MAX_FEEDLINE_UTILIZATION = 16,
    VT_FEEDLINE_TERMINATIONS = 18
  };
  double min_wire_spacing() const {
    return GetField<double>(VT_MIN_WIRE_SPACING, 0.0);
  }
  double min_obstacle_spacing() const {
    return GetField<double>(VT_MIN_OBSTACLE_SPACING, 0.0);
  }
  double min_bend_radius() const {
    return GetField<double>(VT_MIN_BEND_RADIUS, 0.0);
  }
  double min_straight_length() const {
    return GetField<double>(VT_MIN_STRAIGHT_LENGTH, 0.0);
  }
  double target_resonator_length() const {
    return GetField<double>(VT_TARGET_RESONATOR_LENGTH, 0.0);
  }
  double resonator_length_tolerance() const {
    return GetField<double>(VT_RESONATOR_LENGTH_TOLERANCE, 0.0);
  }
  uint32_t max_feedline_utilization() const {
    return GetField<uint32_t>(VT_MAX_FEEDLINE_UTILIZATION, 0);
  }
  uint32_t feedline_terminations() const {
    return GetField<uint32_t>(VT_FEEDLINE_TERMINATIONS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_MIN_WIRE_SPACING, 8) &&
           VerifyField<double>(verifier, VT_MIN_OBSTACLE_SPACING, 8) &&
           VerifyField<double>(verifier, VT_MIN_BEND_RADIUS, 8) &&
           VerifyField<double>(verifier, VT_MIN_STRAIGHT_LENGTH, 8) &&
           VerifyField<double>(verifier, VT_TARGET_RESONATOR_LENGTH, 8) &&
           VerifyField<double>(verifier, VT_RESONATOR_LENGTH_TOLERANCE, 8) &&
           VerifyField<uint32_t>(verifier, VT_MAX_FEEDLINE_UTILIZATION, 4) &&
           VerifyField<uint32_t>(verifier, VT_FEEDLINE_TERMINATIONS, 4) &&
           verifier.EndTable();
  }
  DesignRulesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DesignRulesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DesignRules> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DesignRulesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DesignRulesBuilder {
  typedef DesignRules Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_min_wire_spacing(double min_wire_spacing) {
    fbb_.AddElement<double>(DesignRules::VT_MIN_WIRE_SPACING, min_wire_spacing, 0.0);
  }
  void add_min_obstacle_spacing(double min_obstacle_spacing) {
    fbb_.AddElement<double>(DesignRules::VT_MIN_OBSTACLE_SPACING, min_obstacle_spacing, 0.0);
  }
  void add_min_bend_radius(double min_bend_radius) {
    fbb_.AddElement<double>(DesignRules::VT_MIN_BEND_RADIUS, min_bend_radius, 0.0);
  }
  void add_min_straight_length(double min_straight_length) {
    fbb_.AddElement<double>(DesignRules::VT_MIN_STRAIGHT_LENGTH, min_straight_length, 0.0);
  }
  void add_target_resonator_length(double target_resonator_length) {
    fbb_.AddElement<double>(DesignRules::VT_TARGET_RESONATOR_LENGTH, target_resonator_length, 0.0);
  }
  void add_resonator_length_tolerance(double resonator_length_tolerance) {
    fbb_.AddElement<double>(DesignRules::VT_RESONATOR_LENGTH_TOLERANCE, resonator_length_tolerance, 0.0);
  }
  void add_max_feedline_utilization(uint32_t max_feedline_utilization) {
    fbb_.AddElement<uint32_t>(DesignRules::VT_MAX_FEEDLINE_UTILIZATION, max_feedline_utilization, 0);
  }
  void add_feedline_terminations(uint32_t feedline_terminations) {
    fbb_.AddElement<uint32_t>(DesignRules::VT_FEEDLINE_TERMINATIONS, feedline_terminations, 0);
  }
  explicit DesignRulesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DesignRules> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DesignRules>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DesignRules> CreateDesignRules(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double min_wire_spacing = 0.0,
    double min_obstacle_spacing = 0.0,
    double min_bend_radius = 0.0,
    double min_straight_length = 0.0,
    double target_resonator_length = 0.0,
    double resonator_length_tolerance = 0.0,
    uint32_t max_feedline_utilization = 0,
    uint32_t feedline_terminations = 0) {
  DesignRulesBuilder builder_(_fbb);
  builder_.add_resonator_length_tolerance(resonator_length_tolerance);
  builder_.add_target_resonator_length(target_resonator_length);
  builder_.add_min_straight_length(min_straight_length);
  builder_.add_min_bend_radius(min_bend_radius);
  builder_.add_min_obstacle_spacing(min_obstacle_spacing);
  builder_.add_min_wire_spacing(min_wire_spacing);
  builder_.add_feedline_terminations(feedline_terminations);
  builder_.add_max_feedline_utilization(max_feedline_utilization);
  return builder_.Finish();
}

struct DesignRules::Traits {
  using type = DesignRules;
  static auto constexpr Create = CreateDesignRules;
};

::flatbuffers::Offset<DesignRules> CreateDesignRules(::flatbuffers::FlatBufferBuilder &_fbb, const DesignRulesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CpwCouplerT : public ::flatbuffers::NativeTable {
  typedef CpwCoupler TableType;
  mqt::scpd::flatbuffers::design::ConnectionRef connection{};
  std::unique_ptr<mqt::scpd::flatbuffers::design::PortT> port{};
  mqt::scpd::flatbuffers::geometry::Point center{};
  mqt::scpd::flatbuffers::design::Rotation rotation = mqt::scpd::flatbuffers::design::Rotation::Unset;
  double length = 0.0;
  double height = 0.0;
  CpwCouplerT() = default;
  CpwCouplerT(const CpwCouplerT &o);
  CpwCouplerT(CpwCouplerT&&) FLATBUFFERS_NOEXCEPT = default;
  CpwCouplerT &operator=(CpwCouplerT o) FLATBUFFERS_NOEXCEPT;
};

/// A coplanar-waveguide coupler that taps a feedline. Instantiated by the
/// Final stage at exact physical dimensions in layout units.
struct CpwCoupler FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CpwCouplerT NativeTableType;
  typedef CpwCouplerBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONNECTION = 4,
    VT_PORT = 6,
    VT_CENTER = 8,
    VT_ROTATION = 10,
    VT_LENGTH = 12,
    VT_HEIGHT = 14
  };
  /// The connection the coupler completes. The port below is its
  /// ResonatorSource endpoint, which the Assignment stage left absent.
  const mqt::scpd::flatbuffers::design::ConnectionRef *connection() const {
    return GetStruct<const mqt::scpd::flatbuffers::design::ConnectionRef *>(VT_CONNECTION);
  }
  /// The port the coupler creates. After the Final stage, Chip.ports is the
  /// input ports followed by the couplers' ports in coupler order, so this
  /// port's PortRef is the number of input ports plus the coupler's index.
  const mqt::scpd::flatbuffers::design::Port *port() const {
    return GetPointer<const mqt::scpd::flatbuffers::design::Port *>(VT_PORT);
  }
  const mqt::scpd::flatbuffers::geometry::Point *center() const {
    return GetStruct<const mqt::scpd::flatbuffers::geometry::Point *>(VT_CENTER);
  }
  mqt::scpd::flatbuffers::design::Rotation rotation() const {
    return static_cast<mqt::scpd::flatbuffers::design::Rotation>(GetField<uint8_t>(VT_ROTATION, 0));
  }
  double length() const {
    return GetField<double>(VT_LENGTH, 0.0);
  }
  double height() const {
    return GetField<double>(VT_HEIGHT, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyFieldRequired<mqt::scpd::flatbuffers::design::ConnectionRef>(verifier, VT_CONNECTION, 4) &&
           VerifyOffsetRequired(verifier, VT_PORT) &&
           verifier.VerifyTable(port()) &&
           VerifyFieldRequired<mqt::scpd::flatbuffers::geometry::Point>(verifier, VT_CENTER, 8) &&
           VerifyField<uint8_t>(verifier, VT_ROTATION, 1) &&
           VerifyField<double>(verifier, VT_LENGTH, 8) &&
           VerifyField<double>(verifier, VT_HEIGHT, 8) &&
           verifier.EndTable();
  }
  CpwCouplerT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CpwCouplerT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CpwCoupler> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CpwCouplerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CpwCouplerBuilder {
  typedef CpwCoupler Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_connection(const mqt::scpd::flatbuffers::design::ConnectionRef *connection) {
    fbb_.AddStruct(CpwCoupler::VT_CONNECTION, connection);
  }
  void add_port(::flatbuffers::Offset<mqt::scpd::flatbuffers::design::Port> port) {
    fbb_.AddOffset(CpwCoupler::VT_PORT, port);
  }
  void add_center(const mqt::scpd::flatbuffers::geometry::Point *center) {
    fbb_.AddStruct(CpwCoupler::VT_CENTER, center);
  }
  void add_rotation(mqt::scpd::flatbuffers::design::Rotation rotation) {
    fbb_.AddElement<uint8_t>(CpwCoupler::VT_ROTATION, static_cast<uint8_t>(rotation), 0);
  }
  void add_length(double length) {
    fbb_.AddElement<double>(CpwCoupler::VT_LENGTH, length, 0.0);
  }
  void add_height(double height) {
    fbb_.AddElement<double>(CpwCoupler::VT_HEIGHT, height, 0.0);
  }
  explicit CpwCouplerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CpwCoupler> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CpwCoupler>(end);
    fbb_.Required(o, CpwCoupler::VT_CONNECTION);
    fbb_.Required(o, CpwCoupler::VT_PORT);
    fbb_.Required(o, CpwCoupler::VT_CENTER);
    return o;
  }
};

inline ::flatbuffers::Offset<CpwCoupler> CreateCpwCoupler(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const mqt::scpd::flatbuffers::design::ConnectionRef *connection = nullptr,
    ::flatbuffers::Offset<mqt::scpd::flatbuffers::design::Port> port = 0,
    const mqt::scpd::flatbuffers::geometry::Point *center = nullptr,
    mqt::scpd::flatbuffers::design::Rotation rotation = mqt::scpd::flatbuffers::design::Rotation::Unset,
    double length = 0.0,
    double height = 0.0) {
  CpwCouplerBuilder builder_(_fbb);
  builder_.add_height(height);
  builder_.add_length(length);
  builder_.add_center(center);
  builder_.add_port(port);
  builder_.add_connection(connection);
  builder_.add_rotation(rotation);
  return builder_.Finish();
}

struct CpwCoupler::Traits {
  using type = CpwCoupler;
  static auto constexpr Create = CreateCpwCoupler;
};

::flatbuffers::Offset<CpwCoupler> CreateCpwCoupler(::flatbuffers::FlatBufferBuilder &_fbb, const CpwCouplerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct BridgeT : public ::flatbuffers::NativeTable {
  typedef Bridge TableType;
  mqt::scpd::flatbuffers::geometry::Point center{};
  mqt::scpd::flatbuffers::design::Rotation rotation = mqt::scpd::flatbuffers::design::Rotation::Unset;
  double width = 0.0;
  double height = 0.0;
};

/// An air bridge where a feedline crosses a regular wire. Instantiated at
/// exact physical dimensions in layout units.
struct Bridge FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BridgeT NativeTableType;
  typedef BridgeBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CENTER = 4,
    VT_ROTATION = 6,
    VT_WIDTH = 8,
    VT_HEIGHT = 10
  };
  const mqt::scpd::flatbuffers::geometry::Point *center() const {
    return GetStruct<const mqt::scpd::flatbuffers::geometry::Point *>(VT_CENTER);
  }
  mqt::scpd::flatbuffers::design::Rotation rotation() const {
    return static_cast<mqt::scpd::flatbuffers::design::Rotation>(GetField<uint8_t>(VT_ROTATION, 0));
  }
  double width() const {
    return GetField<double>(VT_WIDTH, 0.0);
  }
  double height() const {
    return GetField<double>(VT_HEIGHT, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyFieldRequired<mqt::scpd::flatbuffers::geometry::Point>(verifier, VT_CENTER, 8) &&
           VerifyField<uint8_t>(verifier, VT_ROTATION, 1) &&
           VerifyField<double>(verifier, VT_WIDTH, 8) &&
           VerifyField<double>(verifier, VT_HEIGHT, 8) &&
           verifier.EndTable();
  }
  BridgeT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BridgeT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Bridge> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BridgeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BridgeBuilder {
  typedef Bridge Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_center(const mqt::scpd::flatbuffers::geometry::Point *center) {
    fbb_.AddStruct(Bridge::VT_CENTER, center);
  }
  void add_rotation(mqt::scpd::flatbuffers::design::Rotation rotation) {
    fbb_.AddElement<uint8_t>(Bridge::VT_ROTATION, static_cast<uint8_t>(rotation), 0);
  }
  void add_width(double width) {
    fbb_.AddElement<double>(Bridge::VT_WIDTH, width, 0.0);
  }
  void add_height(double height) {
    fbb_.AddElement<double>(Bridge::VT_HEIGHT, height, 0.0);
  }
  explicit BridgeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Bridge> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Bridge>(end);
    fbb_.Required(o, Bridge::VT_CENTER);
    return o;
  }
};

inline ::flatbuffers::Offset<Bridge> CreateBridge(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const mqt::scpd::flatbuffers::geometry::Point *center = nullptr,
    mqt::scpd::flatbuffers::design::Rotation rotation = mqt::scpd::flatbuffers::design::Rotation::Unset,
    double width = 0.0,
    double height = 0.0) {
  BridgeBuilder builder_(_fbb);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_center(center);
  builder_.add_rotation(rotation);
  return builder_.Finish();
}

struct Bridge::Traits {
  using type = Bridge;
  static auto constexpr Create = CreateBridge;
};

::flatbuffers::Offset<Bridge> CreateBridge(::flatbuffers::FlatBufferBuilder &_fbb, const BridgeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const PortT &lhs, const PortT &rhs) {
  return
      (lhs.label == rhs.label) &&
      (lhs.center == rhs.center) &&
      (lhs.orientation == rhs.orientation) &&
      (lhs.role == rhs.role);
}

inline bool operator!=(const PortT &lhs, const PortT &rhs) {
    return !(lhs == rhs);
}


inline PortT *Port::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<PortT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Port::UnPackTo(PortT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = label(); if (_e) _o->label = _e->str(); }
  { auto _e = center(); if (_e) _o->center = *_e; }
  { auto _e = orientation(); _o->orientation = _e; }
  { auto _e = role(); _o->role = _e; }
}

inline ::flatbuffers::Offset<Port> CreatePort(::flatbuffers::FlatBufferBuilder &_fbb, const PortT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Port::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Port> Port::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PortT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PortT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _label = _fbb.CreateString(_o->label);
  auto _center = &_o->center;
  auto _orientation = _o->orientation;
  auto _role = _o->role;
  return mqt::scpd::flatbuffers::design::CreatePort(
      _fbb,
      _label,
      _center,
      _orientation,
      _role);
}


inline bool operator==(const ChipT &lhs, const ChipT &rhs) {
  return
      (lhs.obstacles.size() == rhs.obstacles.size() && std::equal(lhs.obstacles.cbegin(), lhs.obstacles.cend(), rhs.obstacles.cbegin(), [](std::unique_ptr<mqt::scpd::flatbuffers::geometry::PolygonT> const &a, std::unique_ptr<mqt::scpd::flatbuffers::geometry::PolygonT> const &b) { return (a == b) || (a && b && *a == *b); })) &&
      (lhs.ports.size() == rhs.ports.size() && std::equal(lhs.ports.cbegin(), lhs.ports.cend(), rhs.ports.cbegin(), [](std::unique_ptr<mqt::scpd::flatbuffers::design::PortT> const &a, std::unique_ptr<mqt::scpd::flatbuffers::design::PortT> const &b) { return (a == b) || (a && b && *a == *b); }));
}

inline bool operator!=(const ChipT &lhs, const ChipT &rhs) {
    return !(lhs == rhs);
}


inline ChipT::ChipT(const ChipT &o) {
  obstacles.reserve(o.obstacles.size());
  for (const auto &obstacles_ : o.obstacles) { obstacles.emplace_back((obstacles_) ? new mqt::scpd::flatbuffers::geometry::PolygonT(*obstacles_) : nullptr); }
  ports.reserve(o.ports.size());
  for (const auto &ports_ : o.ports) { ports.emplace_back((ports_) ? new mqt::scpd::flatbuffers::design::PortT(*ports_) : nullptr); }
}

inline ChipT &ChipT::operator=(ChipT o) FLATBUFFERS_NOEXCEPT {
  std::swap(obstacles, o.obstacles);
  std::swap(ports, o.ports);
  return *this;
}

inline ChipT *Chip::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<ChipT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Chip::UnPackTo(ChipT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = obstacles(); if (_e) { _o->obstacles.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->obstacles[_i]) { _e->Get(_i)->UnPackTo(_o->obstacles[_i].get(), _resolver); } else { _o->obstacles[_i] = std::unique_ptr<mqt::scpd::flatbuffers::geometry::PolygonT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->obstacles.resize(0); } }
  { auto _e = ports(); if (_e) { _o->ports.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->ports[_i]) { _e->Get(_i)->UnPackTo(_o->ports[_i].get(), _resolver); } else { _o->ports[_i] = std::unique_ptr<mqt::scpd::flatbuffers::design::PortT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->ports.resize(0); } }
}

inline ::flatbuffers::Offset<Chip> CreateChip(::flatbuffers::FlatBufferBuilder &_fbb, const ChipT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Chip::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Chip> Chip::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ChipT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ChipT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _obstacles = _fbb.CreateVector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Polygon>> (_o->obstacles.size(), [](size_t i, _VectorArgs *__va) { return CreatePolygon(*__va->__fbb, __va->__o->obstacles[i].get(), __va->__rehasher); }, &_va );
  auto _ports = _fbb.CreateVector<::flatbuffers::Offset<mqt::scpd::flatbuffers::design::Port>> (_o->ports.size(), [](size_t i, _VectorArgs *__va) { return CreatePort(*__va->__fbb, __va->__o->ports[i].get(), __va->__rehasher); }, &_va );
  return mqt::scpd::flatbuffers::design::CreateChip(
      _fbb,
      _obstacles,
      _ports);
}


inline bool operator==(const ConnectionT &lhs, const ConnectionT &rhs) {
  return
      ((lhs.source == rhs.source) || (lhs.source && rhs.source && *lhs.source == *rhs.source)) &&
      (lhs.target == rhs.target) &&
      (lhs.source_role == rhs.source_role) &&
      (lhs.target_role == rhs.target_role);
}

inline bool operator!=(const ConnectionT &lhs, const ConnectionT &rhs) {
    return !(lhs == rhs);
}


inline ConnectionT::ConnectionT(const ConnectionT &o)
      : source((o.source) ? new mqt::scpd::flatbuffers::design::PortRef(*o.source) : nullptr),
        target(o.target),
        source_role(o.source_role),
        target_role(o.target_role) {
}

inline ConnectionT &ConnectionT::operator=(ConnectionT o) FLATBUFFERS_NOEXCEPT {
  std::swap(source, o.source);
  std::swap(target, o.target);
  std::swap(source_role, o.source_role);
  std::swap(target_role, o.target_role);
  return *this;
}

inline ConnectionT *Connection::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<ConnectionT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Connection::UnPackTo(ConnectionT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = source(); if (_e) _o->source = std::unique_ptr<mqt::scpd::flatbuffers::design::PortRef>(new mqt::scpd::flatbuffers::design::PortRef(*_e)); }
  { auto _e = target(); if (_e) _o->target = *_e; }
  { auto _e = source_role(); _o->source_role = _e; }
  { auto _e = target_role(); _o->target_role = _e; }
}

inline ::flatbuffers::Offset<Connection> CreateConnection(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectionT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Connection::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Connection> Connection::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ConnectionT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ConnectionT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _source = _o->source ? _o->source.get() : nullptr;
  auto _target = &_o->target;
  auto _source_role = _o->source_role;
  auto _target_role = _o->target_role;
  return mqt::scpd::flatbuffers::design::CreateConnection(
      _fbb,
      _source,
      _target,
      _source_role,
      _target_role);
}


inline bool operator==(const DesignRulesT &lhs, const DesignRulesT &rhs) {
  return
      (lhs.min_wire_spacing == rhs.min_wire_spacing) &&
      (lhs.min_obstacle_spacing == rhs.min_obstacle_spacing) &&
      (lhs.min_bend_radius == rhs.min_bend_radius) &&
      (lhs.min_straight_length == rhs.min_straight_length) &&
      (lhs.target_resonator_length == rhs.target_resonator_length) &&
      (lhs.resonator_length_tolerance == rhs.resonator_length_tolerance) &&
      (lhs.max_feedline_utilization == rhs.max_feedline_utilization) &&
      (lhs.feedline_terminations == rhs.feedline_terminations);
}

inline bool operator!=(const DesignRulesT &lhs, const DesignRulesT &rhs) {
    return !(lhs == rhs);
}


inline DesignRulesT *DesignRules::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<DesignRulesT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DesignRules::UnPackTo(DesignRulesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = min_wire_spacing(); _o->min_wire_spacing = _e; }
  { auto _e = min_obstacle_spacing(); _o->min_obstacle_spacing = _e; }
  { auto _e = min_bend_radius(); _o->min_bend_radius = _e; }
  { auto _e = min_straight_length(); _o->min_straight_length = _e; }
  { auto _e = target_resonator_length(); _o->target_resonator_length = _e; }
  { auto _e = resonator_length_tolerance(); _o->resonator_length_tolerance = _e; }
  { auto _e = max_feedline_utilization(); _o->max_feedline_utilization = _e; }
  { auto _e = feedline_terminations(); _o->feedline_terminations = _e; }
}

inline ::flatbuffers::Offset<DesignRules> CreateDesignRules(::flatbuffers::FlatBufferBuilder &_fbb, const DesignRulesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return DesignRules::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DesignRules> DesignRules::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DesignRulesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DesignRulesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _min_wire_spacing = _o->min_wire_spacing;
  auto _min_obstacle_spacing = _o->min_obstacle_spacing;
  auto _min_bend_radius = _o->min_bend_radius;
  auto _min_straight_length = _o->min_straight_length;
  auto _target_resonator_length = _o->target_resonator_length;
  auto _resonator_length_tolerance = _o->resonator_length_tolerance;
  auto _max_feedline_utilization = _o->max_feedline_utilization;
  auto _feedline_terminations = _o->feedline_terminations;
  return mqt::scpd::flatbuffers::design::CreateDesignRules(
      _fbb,
      _min_wire_spacing,
      _min_obstacle_spacing,
      _min_bend_radius,
      _min_straight_length,
      _target_resonator_length,
      _resonator_length_tolerance,
      _max_feedline_utilization,
      _feedline_terminations);
}


inline bool operator==(const CpwCouplerT &lhs, const CpwCouplerT &rhs) {
  return
      (lhs.connection == rhs.connection) &&
      ((lhs.port == rhs.port) || (lhs.port && rhs.port && *lhs.port == *rhs.port)) &&
      (lhs.center == rhs.center) &&
      (lhs.rotation == rhs.rotation) &&
      (lhs.length == rhs.length) &&
      (lhs.height == rhs.height);
}

inline bool operator!=(const CpwCouplerT &lhs, const CpwCouplerT &rhs) {
    return !(lhs == rhs);
}


inline CpwCouplerT::CpwCouplerT(const CpwCouplerT &o)
      : connection(o.connection),
        port((o.port) ? new mqt::scpd::flatbuffers::design::PortT(*o.port) : nullptr),
        center(o.center),
        rotation(o.rotation),
        length(o.length),
        height(o.height) {
}

inline CpwCouplerT &CpwCouplerT::operator=(CpwCouplerT o) FLATBUFFERS_NOEXCEPT {
  std::swap(connection, o.connection);
  std::swap(port, o.port);
  std::swap(center, o.center);
  std::swap(rotation, o.rotation);
  std::swap(length, o.length);
  std::swap(height, o.height);
  return *this;
}

inline CpwCouplerT *CpwCoupler::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<CpwCouplerT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CpwCoupler::UnPackTo(CpwCouplerT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = connection(); if (_e) _o->connection = *_e; }
  { auto _e = port(); if (_e) { if(_o->port) { _e->UnPackTo(_o->port.get(), _resolver); } else { _o->port = std::unique_ptr<mqt::scpd::flatbuffers::design::PortT>(_e->UnPack(_resolver)); } } else if (_o->port) { _o->port.reset(); } }
  { auto _e = center(); if (_e) _o->center = *_e; }
  { auto _e = rotation(); _o->rotation = _e; }
  { auto _e = length(); _o->length = _e; }
  { auto _e = height(); _o->height = _e; }
}

inline ::flatbuffers::Offset<CpwCoupler> CreateCpwCoupler(::flatbuffers::FlatBufferBuilder &_fbb, const CpwCouplerT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CpwCoupler::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CpwCoupler> CpwCoupler::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CpwCouplerT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CpwCouplerT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _connection = &_o->connection;
  auto _port = _o->port ? CreatePort(_fbb, _o->port.get(), _rehasher) : 0;
  auto _center = &_o->center;
  auto _rotation = _o->rotation;
  auto _length = _o->length;
  auto _height = _o->height;
  return mqt::scpd::flatbuffers::design::CreateCpwCoupler(
      _fbb,
      _connection,
      _port,
      _center,
      _rotation,
      _length,
      _height);
}


inline bool operator==(const BridgeT &lhs, const BridgeT &rhs) {
  return
      (lhs.center == rhs.center) &&
      (lhs.rotation == rhs.rotation) &&
      (lhs.width == rhs.width) &&
      (lhs.height == rhs.height);
}

inline bool operator!=(const BridgeT &lhs, const BridgeT &rhs) {
    return !(lhs == rhs);
}


inline BridgeT *Bridge::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<BridgeT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Bridge::UnPackTo(BridgeT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = center(); if (_e) _o->center = *_e; }
  { auto _e = rotation(); _o->rotation = _e; }
  { auto _e = width(); _o->width = _e; }
  { auto _e = height(); _o->height = _e; }
}

inline ::flatbuffers::Offset<Bridge> CreateBridge(::flatbuffers::FlatBufferBuilder &_fbb, const BridgeT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Bridge::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Bridge> Bridge::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BridgeT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BridgeT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _center = &_o->center;
  auto _rotation = _o->rotation;
  auto _width = _o->width;
  auto _height = _o->height;
  return mqt::scpd::flatbuffers::design::CreateBridge(
      _fbb,
      _center,
      _rotation,
      _width,
      _height);
}

}  // namespace design
}  // namespace flatbuffers
}  // namespace scpd
}  // namespace mqt

#endif  // FLATBUFFERS_GENERATED_DESIGN_MQT_SCPD_FLATBUFFERS_DESIGN_H_
