// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GEOMETRY_MQT_SCPD_FLATBUFFERS_GEOMETRY_H_
#define FLATBUFFERS_GENERATED_GEOMETRY_MQT_SCPD_FLATBUFFERS_GEOMETRY_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace mqt {
namespace scpd {
namespace flatbuffers {
namespace geometry {

struct Point;

struct Polygon;
struct PolygonBuilder;
struct PolygonT;

struct Line;
struct LineBuilder;
struct LineT;

struct Arc;
struct ArcBuilder;
struct ArcT;

struct Segment;
struct SegmentBuilder;
struct SegmentT;

struct Path;
struct PathBuilder;
struct PathT;

bool operator==(const Point &lhs, const Point &rhs);
bool operator!=(const Point &lhs, const Point &rhs);
bool operator==(const PolygonT &lhs, const PolygonT &rhs);
bool operator!=(const PolygonT &lhs, const PolygonT &rhs);
bool operator==(const LineT &lhs, const LineT &rhs);
bool operator!=(const LineT &lhs, const LineT &rhs);
bool operator==(const ArcT &lhs, const ArcT &rhs);
bool operator!=(const ArcT &lhs, const ArcT &rhs);
bool operator==(const SegmentT &lhs, const SegmentT &rhs);
bool operator!=(const SegmentT &lhs, const SegmentT &rhs);
bool operator==(const PathT &lhs, const PathT &rhs);
bool operator!=(const PathT &lhs, const PathT &rhs);

/// The two analytic shapes a routed wire consists of.
enum class SegmentShape : uint8_t {
  NONE = 0,
  Line = 1,
  Arc = 2,
  MIN = NONE,
  MAX = Arc
};

inline const SegmentShape (&EnumValuesSegmentShape())[3] {
  static const SegmentShape values[] = {
    SegmentShape::NONE,
    SegmentShape::Line,
    SegmentShape::Arc
  };
  return values;
}

inline const char * const *EnumNamesSegmentShape() {
  static const char * const names[4] = {
    "NONE",
    "Line",
    "Arc",
    nullptr
  };
  return names;
}

inline const char *EnumNameSegmentShape(SegmentShape e) {
  if (::flatbuffers::IsOutRange(e, SegmentShape::NONE, SegmentShape::Arc)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSegmentShape()[index];
}

template<typename T> struct SegmentShapeTraits {
  static const SegmentShape enum_value = SegmentShape::NONE;
};

template<> struct SegmentShapeTraits<mqt::scpd::flatbuffers::geometry::Line> {
  static const SegmentShape enum_value = SegmentShape::Line;
};

template<> struct SegmentShapeTraits<mqt::scpd::flatbuffers::geometry::Arc> {
  static const SegmentShape enum_value = SegmentShape::Arc;
};

template<typename T> struct SegmentShapeUnionTraits {
  static const SegmentShape enum_value = SegmentShape::NONE;
};

template<> struct SegmentShapeUnionTraits<mqt::scpd::flatbuffers::geometry::LineT> {
  static const SegmentShape enum_value = SegmentShape::Line;
};

template<> struct SegmentShapeUnionTraits<mqt::scpd::flatbuffers::geometry::ArcT> {
  static const SegmentShape enum_value = SegmentShape::Arc;
};

struct SegmentShapeUnion {
  SegmentShape type;
  void *value;

  SegmentShapeUnion() : type(SegmentShape::NONE), value(nullptr) {}
  SegmentShapeUnion(SegmentShapeUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(SegmentShape::NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  SegmentShapeUnion(const SegmentShapeUnion &);
  SegmentShapeUnion &operator=(const SegmentShapeUnion &u)
    { SegmentShapeUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  SegmentShapeUnion &operator=(SegmentShapeUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~SegmentShapeUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = SegmentShapeUnionTraits<RT>::enum_value;
    if (type != SegmentShape::NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, SegmentShape type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  mqt::scpd::flatbuffers::geometry::LineT *AsLine() {
    return type == SegmentShape::Line ?
      reinterpret_cast<mqt::scpd::flatbuffers::geometry::LineT *>(value) : nullptr;
  }
  const mqt::scpd::flatbuffers::geometry::LineT *AsLine() const {
    return type == SegmentShape::Line ?
      reinterpret_cast<const mqt::scpd::flatbuffers::geometry::LineT *>(value) : nullptr;
  }
  mqt::scpd::flatbuffers::geometry::ArcT *AsArc() {
    return type == SegmentShape::Arc ?
      reinterpret_cast<mqt::scpd::flatbuffers::geometry::ArcT *>(value) : nullptr;
  }
  const mqt::scpd::flatbuffers::geometry::ArcT *AsArc() const {
    return type == SegmentShape::Arc ?
      reinterpret_cast<const mqt::scpd::flatbuffers::geometry::ArcT *>(value) : nullptr;
  }
};


inline bool operator==(const SegmentShapeUnion &lhs, const SegmentShapeUnion &rhs) {
  if (lhs.type != rhs.type) return false;
  switch (lhs.type) {
    case SegmentShape::NONE: {
      return true;
    }
    case SegmentShape::Line: {
      return *(reinterpret_cast<const mqt::scpd::flatbuffers::geometry::LineT *>(lhs.value)) ==
             *(reinterpret_cast<const mqt::scpd::flatbuffers::geometry::LineT *>(rhs.value));
    }
    case SegmentShape::Arc: {
      return *(reinterpret_cast<const mqt::scpd::flatbuffers::geometry::ArcT *>(lhs.value)) ==
             *(reinterpret_cast<const mqt::scpd::flatbuffers::geometry::ArcT *>(rhs.value));
    }
    default: {
      return false;
    }
  }
}

inline bool operator!=(const SegmentShapeUnion &lhs, const SegmentShapeUnion &rhs) {
    return !(lhs == rhs);
}

template <bool B = false>
bool VerifySegmentShape(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SegmentShape type);
template <bool B = false>
bool VerifySegmentShapeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<SegmentShape> *types);

/// A point in layout space. Micrometers, as double.
FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Point FLATBUFFERS_FINAL_CLASS {
 private:
  double x_;
  double y_;

 public:
  struct Traits;
  Point()
      : x_(0),
        y_(0) {
  }
  Point(double _x, double _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  double x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Point, 16);

inline bool operator==(const Point &lhs, const Point &rhs) {
  return
      (lhs.x() == rhs.x()) &&
      (lhs.y() == rhs.y());
}

inline bool operator!=(const Point &lhs, const Point &rhs) {
    return !(lhs == rhs);
}


struct Point::Traits {
  using type = Point;
};

struct PolygonT : public ::flatbuffers::NativeTable {
  typedef Polygon TableType;
  std::vector<mqt::scpd::flatbuffers::geometry::Point> vertices{};
};

/// A closed polygon in layout space, stored as the input carries it.
struct Polygon FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PolygonT NativeTableType;
  typedef PolygonBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTICES = 4
  };
  const ::flatbuffers::Vector<const mqt::scpd::flatbuffers::geometry::Point *> *vertices() const {
    return GetPointer<const ::flatbuffers::Vector<const mqt::scpd::flatbuffers::geometry::Point *> *>(VT_VERTICES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           verifier.EndTable();
  }
  PolygonT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PolygonT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Polygon> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PolygonT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PolygonBuilder {
  typedef Polygon Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertices(::flatbuffers::Offset<::flatbuffers::Vector<const mqt::scpd::flatbuffers::geometry::Point *>> vertices) {
    fbb_.AddOffset(Polygon::VT_VERTICES, vertices);
  }
  explicit PolygonBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Polygon> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Polygon>(end);
    fbb_.Required(o, Polygon::VT_VERTICES);
    return o;
  }
};

inline ::flatbuffers::Offset<Polygon> CreatePolygon(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const mqt::scpd::flatbuffers::geometry::Point *>> vertices = 0) {
  PolygonBuilder builder_(_fbb);
  builder_.add_vertices(vertices);
  return builder_.Finish();
}

struct Polygon::Traits {
  using type = Polygon;
  static auto constexpr Create = CreatePolygon;
};

inline ::flatbuffers::Offset<Polygon> CreatePolygonDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<mqt::scpd::flatbuffers::geometry::Point> *vertices = nullptr) {
  auto vertices__ = vertices ? _fbb.CreateVectorOfStructs<mqt::scpd::flatbuffers::geometry::Point>(*vertices) : 0;
  return mqt::scpd::flatbuffers::geometry::CreatePolygon(
      _fbb,
      vertices__);
}

::flatbuffers::Offset<Polygon> CreatePolygon(::flatbuffers::FlatBufferBuilder &_fbb, const PolygonT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct LineT : public ::flatbuffers::NativeTable {
  typedef Line TableType;
  mqt::scpd::flatbuffers::geometry::Point start{};
  mqt::scpd::flatbuffers::geometry::Point end{};
};

/// A straight segment in layout space.
struct Line FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LineT NativeTableType;
  typedef LineBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_START = 4,
    VT_END = 6
  };
  const mqt::scpd::flatbuffers::geometry::Point *start() const {
    return GetStruct<const mqt::scpd::flatbuffers::geometry::Point *>(VT_START);
  }
  const mqt::scpd::flatbuffers::geometry::Point *end() const {
    return GetStruct<const mqt::scpd::flatbuffers::geometry::Point *>(VT_END);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyFieldRequired<mqt::scpd::flatbuffers::geometry::Point>(verifier, VT_START, 8) &&
           VerifyFieldRequired<mqt::scpd::flatbuffers::geometry::Point>(verifier, VT_END, 8) &&
           verifier.EndTable();
  }
  LineT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(LineT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Line> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LineT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct LineBuilder {
  typedef Line Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_start(const mqt::scpd::flatbuffers::geometry::Point *start) {
    fbb_.AddStruct(Line::VT_START, start);
  }
  void add_end(const mqt::scpd::flatbuffers::geometry::Point *end) {
    fbb_.AddStruct(Line::VT_END, end);
  }
  explicit LineBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Line> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Line>(end);
    fbb_.Required(o, Line::VT_START);
    fbb_.Required(o, Line::VT_END);
    return o;
  }
};

inline ::flatbuffers::Offset<Line> CreateLine(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const mqt::scpd::flatbuffers::geometry::Point *start = nullptr,
    const mqt::scpd::flatbuffers::geometry::Point *end = nullptr) {
  LineBuilder builder_(_fbb);
  builder_.add_end(end);
  builder_.add_start(start);
  return builder_.Finish();
}

struct Line::Traits {
  using type = Line;
  static auto constexpr Create = CreateLine;
};

::flatbuffers::Offset<Line> CreateLine(::flatbuffers::FlatBufferBuilder &_fbb, const LineT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ArcT : public ::flatbuffers::NativeTable {
  typedef Arc TableType;
  mqt::scpd::flatbuffers::geometry::Point center{};
  double radius = 0.0;
  double start_angle = 0.0;
  double sweep = 0.0;
};

/// A circular arc in layout space with an exact center and radius. Angles are
/// radians; a positive sweep runs counter-clockwise.
struct Arc FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ArcT NativeTableType;
  typedef ArcBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CENTER = 4,
    VT_RADIUS = 6,
    VT_START_ANGLE = 8,
    VT_SWEEP = 10
  };
  const mqt::scpd::flatbuffers::geometry::Point *center() const {
    return GetStruct<const mqt::scpd::flatbuffers::geometry::Point *>(VT_CENTER);
  }
  double radius() const {
    return GetField<double>(VT_RADIUS, 0.0);
  }
  double start_angle() const {
    return GetField<double>(VT_START_ANGLE, 0.0);
  }
  double sweep() const {
    return GetField<double>(VT_SWEEP, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyFieldRequired<mqt::scpd::flatbuffers::geometry::Point>(verifier, VT_CENTER, 8) &&
           VerifyField<double>(verifier, VT_RADIUS, 8) &&
           VerifyField<double>(verifier, VT_START_ANGLE, 8) &&
           VerifyField<double>(verifier, VT_SWEEP, 8) &&
           verifier.EndTable();
  }
  ArcT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ArcT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Arc> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ArcT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ArcBuilder {
  typedef Arc Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_center(const mqt::scpd::flatbuffers::geometry::Point *center) {
    fbb_.AddStruct(Arc::VT_CENTER, center);
  }
  void add_radius(double radius) {
    fbb_.AddElement<double>(Arc::VT_RADIUS, radius, 0.0);
  }
  void add_start_angle(double start_angle) {
    fbb_.AddElement<double>(Arc::VT_START_ANGLE, start_angle, 0.0);
  }
  void add_sweep(double sweep) {
    fbb_.AddElement<double>(Arc::VT_SWEEP, sweep, 0.0);
  }
  explicit ArcBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Arc> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Arc>(end);
    fbb_.Required(o, Arc::VT_CENTER);
    return o;
  }
};

inline ::flatbuffers::Offset<Arc> CreateArc(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const mqt::scpd::flatbuffers::geometry::Point *center = nullptr,
    double radius = 0.0,
    double start_angle = 0.0,
    double sweep = 0.0) {
  ArcBuilder builder_(_fbb);
  builder_.add_sweep(sweep);
  builder_.add_start_angle(start_angle);
  builder_.add_radius(radius);
  builder_.add_center(center);
  return builder_.Finish();
}

struct Arc::Traits {
  using type = Arc;
  static auto constexpr Create = CreateArc;
};

::flatbuffers::Offset<Arc> CreateArc(::flatbuffers::FlatBufferBuilder &_fbb, const ArcT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SegmentT : public ::flatbuffers::NativeTable {
  typedef Segment TableType;
  mqt::scpd::flatbuffers::geometry::SegmentShapeUnion shape{};
};

/// One analytic segment of a path.
struct Segment FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SegmentT NativeTableType;
  typedef SegmentBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SHAPE_TYPE = 4,
    VT_SHAPE = 6
  };
  mqt::scpd::flatbuffers::geometry::SegmentShape shape_type() const {
    return static_cast<mqt::scpd::flatbuffers::geometry::SegmentShape>(GetField<uint8_t>(VT_SHAPE_TYPE, 0));
  }
  const void *shape() const {
    return GetPointer<const void *>(VT_SHAPE);
  }
  template<typename T> const T *shape_as() const;
  const mqt::scpd::flatbuffers::geometry::Line *shape_as_Line() const {
    return shape_type() == mqt::scpd::flatbuffers::geometry::SegmentShape::Line ? static_cast<const mqt::scpd::flatbuffers::geometry::Line *>(shape()) : nullptr;
  }
  const mqt::scpd::flatbuffers::geometry::Arc *shape_as_Arc() const {
    return shape_type() == mqt::scpd::flatbuffers::geometry::SegmentShape::Arc ? static_cast<const mqt::scpd::flatbuffers::geometry::Arc *>(shape()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SHAPE_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_SHAPE) &&
           VerifySegmentShape(verifier, shape(), shape_type()) &&
           verifier.EndTable();
  }
  SegmentT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SegmentT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Segment> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SegmentT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const mqt::scpd::flatbuffers::geometry::Line *Segment::shape_as<mqt::scpd::flatbuffers::geometry::Line>() const {
  return shape_as_Line();
}

template<> inline const mqt::scpd::flatbuffers::geometry::Arc *Segment::shape_as<mqt::scpd::flatbuffers::geometry::Arc>() const {
  return shape_as_Arc();
}

struct SegmentBuilder {
  typedef Segment Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_shape_type(mqt::scpd::flatbuffers::geometry::SegmentShape shape_type) {
    fbb_.AddElement<uint8_t>(Segment::VT_SHAPE_TYPE, static_cast<uint8_t>(shape_type), 0);
  }
  void add_shape(::flatbuffers::Offset<void> shape) {
    fbb_.AddOffset(Segment::VT_SHAPE, shape);
  }
  explicit SegmentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Segment> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Segment>(end);
    fbb_.Required(o, Segment::VT_SHAPE);
    return o;
  }
};

inline ::flatbuffers::Offset<Segment> CreateSegment(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    mqt::scpd::flatbuffers::geometry::SegmentShape shape_type = mqt::scpd::flatbuffers::geometry::SegmentShape::NONE,
    ::flatbuffers::Offset<void> shape = 0) {
  SegmentBuilder builder_(_fbb);
  builder_.add_shape(shape);
  builder_.add_shape_type(shape_type);
  return builder_.Finish();
}

struct Segment::Traits {
  using type = Segment;
  static auto constexpr Create = CreateSegment;
};

::flatbuffers::Offset<Segment> CreateSegment(::flatbuffers::FlatBufferBuilder &_fbb, const SegmentT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct PathT : public ::flatbuffers::NativeTable {
  typedef Path TableType;
  std::vector<std::unique_ptr<mqt::scpd::flatbuffers::geometry::SegmentT>> segments{};
  PathT() = default;
  PathT(const PathT &o);
  PathT(PathT&&) FLATBUFFERS_NOEXCEPT = default;
  PathT &operator=(PathT o) FLATBUFFERS_NOEXCEPT;
};

/// A routed wire as a sequence of analytic segments, never as sampled points.
struct Path FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PathT NativeTableType;
  typedef PathBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEGMENTS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Segment>> *segments() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Segment>> *>(VT_SEGMENTS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_SEGMENTS) &&
           verifier.VerifyVector(segments()) &&
           verifier.VerifyVectorOfTables(segments()) &&
           verifier.EndTable();
  }
  PathT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PathT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Path> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PathT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PathBuilder {
  typedef Path Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_segments(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Segment>>> segments) {
    fbb_.AddOffset(Path::VT_SEGMENTS, segments);
  }
  explicit PathBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Path> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Path>(end);
    fbb_.Required(o, Path::VT_SEGMENTS);
    return o;
  }
};

inline ::flatbuffers::Offset<Path> CreatePath(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Segment>>> segments = 0) {
  PathBuilder builder_(_fbb);
  builder_.add_segments(segments);
  return builder_.Finish();
}

struct Path::Traits {
  using type = Path;
  static auto constexpr Create = CreatePath;
};

inline ::flatbuffers::Offset<Path> CreatePathDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Segment>> *segments = nullptr) {
  auto segments__ = segments ? _fbb.CreateVector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Segment>>(*segments) : 0;
  return mqt::scpd::flatbuffers::geometry::CreatePath(
      _fbb,
      segments__);
}

::flatbuffers::Offset<Path> CreatePath(::flatbuffers::FlatBufferBuilder &_fbb, const PathT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const PolygonT &lhs, const PolygonT &rhs) {
  return
      (lhs.vertices == rhs.vertices);
}

inline bool operator!=(const PolygonT &lhs, const PolygonT &rhs) {
    return !(lhs == rhs);
}


inline PolygonT *Polygon::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<PolygonT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Polygon::UnPackTo(PolygonT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = vertices(); if (_e) { _o->vertices.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->vertices[_i] = *_e->Get(_i); } } else { _o->vertices.resize(0); } }
}

inline ::flatbuffers::Offset<Polygon> CreatePolygon(::flatbuffers::FlatBufferBuilder &_fbb, const PolygonT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Polygon::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Polygon> Polygon::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PolygonT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PolygonT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _vertices = _fbb.CreateVectorOfStructs(_o->vertices);
  return mqt::scpd::flatbuffers::geometry::CreatePolygon(
      _fbb,
      _vertices);
}


inline bool operator==(const LineT &lhs, const LineT &rhs) {
  return
      (lhs.start == rhs.start) &&
      (lhs.end == rhs.end);
}

inline bool operator!=(const LineT &lhs, const LineT &rhs) {
    return !(lhs == rhs);
}


inline LineT *Line::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<LineT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Line::UnPackTo(LineT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = start(); if (_e) _o->start = *_e; }
  { auto _e = end(); if (_e) _o->end = *_e; }
}

inline ::flatbuffers::Offset<Line> CreateLine(::flatbuffers::FlatBufferBuilder &_fbb, const LineT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Line::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Line> Line::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const LineT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const LineT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _start = &_o->start;
  auto _end = &_o->end;
  return mqt::scpd::flatbuffers::geometry::CreateLine(
      _fbb,
      _start,
      _end);
}


inline bool operator==(const ArcT &lhs, const ArcT &rhs) {
  return
      (lhs.center == rhs.center) &&
      (lhs.radius == rhs.radius) &&
      (lhs.start_angle == rhs.start_angle) &&
      (lhs.sweep == rhs.sweep);
}

inline bool operator!=(const ArcT &lhs, const ArcT &rhs) {
    return !(lhs == rhs);
}


inline ArcT *Arc::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<ArcT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Arc::UnPackTo(ArcT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = center(); if (_e) _o->center = *_e; }
  { auto _e = radius(); _o->radius = _e; }
  { auto _e = start_angle(); _o->start_angle = _e; }
  { auto _e = sweep(); _o->sweep = _e; }
}

inline ::flatbuffers::Offset<Arc> CreateArc(::flatbuffers::FlatBufferBuilder &_fbb, const ArcT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Arc::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Arc> Arc::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ArcT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ArcT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _center = &_o->center;
  auto _radius = _o->radius;
  auto _start_angle = _o->start_angle;
  auto _sweep = _o->sweep;
  return mqt::scpd::flatbuffers::geometry::CreateArc(
      _fbb,
      _center,
      _radius,
      _start_angle,
      _sweep);
}


inline bool operator==(const SegmentT &lhs, const SegmentT &rhs) {
  return
      (lhs.shape == rhs.shape);
}

inline bool operator!=(const SegmentT &lhs, const SegmentT &rhs) {
    return !(lhs == rhs);
}


inline SegmentT *Segment::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<SegmentT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Segment::UnPackTo(SegmentT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = shape_type(); _o->shape.type = _e; }
  { auto _e = shape(); if (_e) _o->shape.value = mqt::scpd::flatbuffers::geometry::SegmentShapeUnion::UnPack(_e, shape_type(), _resolver); }
}

inline ::flatbuffers::Offset<Segment> CreateSegment(::flatbuffers::FlatBufferBuilder &_fbb, const SegmentT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Segment::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Segment> Segment::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const SegmentT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const SegmentT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _shape_type = _o->shape.type;
  auto _shape = _o->shape.Pack(_fbb);
  return mqt::scpd::flatbuffers::geometry::CreateSegment(
      _fbb,
      _shape_type,
      _shape);
}


inline bool operator==(const PathT &lhs, const PathT &rhs) {
  return
      (lhs.segments.size() == rhs.segments.size() && std::equal(lhs.segments.cbegin(), lhs.segments.cend(), rhs.segments.cbegin(), [](std::unique_ptr<mqt::scpd::flatbuffers::geometry::SegmentT> const &a, std::unique_ptr<mqt::scpd::flatbuffers::geometry::SegmentT> const &b) { return (a == b) || (a && b && *a == *b); }));
}

inline bool operator!=(const PathT &lhs, const PathT &rhs) {
    return !(lhs == rhs);
}


inline PathT::PathT(const PathT &o) {
  segments.reserve(o.segments.size());
  for (const auto &segments_ : o.segments) { segments.emplace_back((segments_) ? new mqt::scpd::flatbuffers::geometry::SegmentT(*segments_) : nullptr); }
}

inline PathT &PathT::operator=(PathT o) FLATBUFFERS_NOEXCEPT {
  std::swap(segments, o.segments);
  return *this;
}

inline PathT *Path::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<PathT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Path::UnPackTo(PathT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = segments(); if (_e) { _o->segments.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->segments[_i]) { _e->Get(_i)->UnPackTo(_o->segments[_i].get(), _resolver); } else { _o->segments[_i] = std::unique_ptr<mqt::scpd::flatbuffers::geometry::SegmentT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->segments.resize(0); } }
}

inline ::flatbuffers::Offset<Path> CreatePath(::flatbuffers::FlatBufferBuilder &_fbb, const PathT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Path::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Path> Path::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PathT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PathT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _segments = _fbb.CreateVector<::flatbuffers::Offset<mqt::scpd::flatbuffers::geometry::Segment>> (_o->segments.size(), [](size_t i, _VectorArgs *__va) { return CreateSegment(*__va->__fbb, __va->__o->segments[i].get(), __va->__rehasher); }, &_va );
  return mqt::scpd::flatbuffers::geometry::CreatePath(
      _fbb,
      _segments);
}

template <bool B>
inline bool VerifySegmentShape(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, SegmentShape type) {
  switch (type) {
    case SegmentShape::NONE: {
      return true;
    }
    case SegmentShape::Line: {
      auto ptr = reinterpret_cast<const mqt::scpd::flatbuffers::geometry::Line *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case SegmentShape::Arc: {
      auto ptr = reinterpret_cast<const mqt::scpd::flatbuffers::geometry::Arc *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifySegmentShapeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<SegmentShape> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifySegmentShape(
        verifier,  values->Get(i), types->GetEnum<SegmentShape>(i))) {
      return false;
    }
  }
  return true;
}

inline void *SegmentShapeUnion::UnPack(const void *obj, SegmentShape type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case SegmentShape::Line: {
      auto ptr = reinterpret_cast<const mqt::scpd::flatbuffers::geometry::Line *>(obj);
      return ptr->UnPack(resolver);
    }
    case SegmentShape::Arc: {
      auto ptr = reinterpret_cast<const mqt::scpd::flatbuffers::geometry::Arc *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> SegmentShapeUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case SegmentShape::Line: {
      auto ptr = reinterpret_cast<const mqt::scpd::flatbuffers::geometry::LineT *>(value);
      return CreateLine(_fbb, ptr, _rehasher).Union();
    }
    case SegmentShape::Arc: {
      auto ptr = reinterpret_cast<const mqt::scpd::flatbuffers::geometry::ArcT *>(value);
      return CreateArc(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline SegmentShapeUnion::SegmentShapeUnion(const SegmentShapeUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case SegmentShape::Line: {
      value = new mqt::scpd::flatbuffers::geometry::LineT(*reinterpret_cast<mqt::scpd::flatbuffers::geometry::LineT *>(u.value));
      break;
    }
    case SegmentShape::Arc: {
      value = new mqt::scpd::flatbuffers::geometry::ArcT(*reinterpret_cast<mqt::scpd::flatbuffers::geometry::ArcT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void SegmentShapeUnion::Reset() {
  switch (type) {
    case SegmentShape::Line: {
      auto ptr = reinterpret_cast<mqt::scpd::flatbuffers::geometry::LineT *>(value);
      delete ptr;
      break;
    }
    case SegmentShape::Arc: {
      auto ptr = reinterpret_cast<mqt::scpd::flatbuffers::geometry::ArcT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = SegmentShape::NONE;
}

}  // namespace geometry
}  // namespace flatbuffers
}  // namespace scpd
}  // namespace mqt

#endif  // FLATBUFFERS_GENERATED_GEOMETRY_MQT_SCPD_FLATBUFFERS_GEOMETRY_H_
