# automatically generated by the FlatBuffers compiler, do not modify

# namespace: design

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.geometry.Point import Point
from typing import Optional
np = import_numpy()

# An air bridge where a feedline crosses a regular wire. Instantiated at
# exact physical dimensions in layout units.
class Bridge(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Bridge()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBridge(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Bridge
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bridge
    def Centre(self) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Bridge
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Bridge
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Bridge
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def BridgeStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    BridgeStart(builder)

def BridgeAddCentre(builder: flatbuffers.Builder, centre: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(centre), 0)

def AddCentre(builder: flatbuffers.Builder, centre: Any):
    BridgeAddCentre(builder, centre)

def BridgeAddRotation(builder: flatbuffers.Builder, rotation: int):
    builder.PrependUint8Slot(1, rotation, 0)

def AddRotation(builder: flatbuffers.Builder, rotation: int):
    BridgeAddRotation(builder, rotation)

def BridgeAddWidth(builder: flatbuffers.Builder, width: float):
    builder.PrependFloat64Slot(2, width, 0.0)

def AddWidth(builder: flatbuffers.Builder, width: float):
    BridgeAddWidth(builder, width)

def BridgeAddHeight(builder: flatbuffers.Builder, height: float):
    builder.PrependFloat64Slot(3, height, 0.0)

def AddHeight(builder: flatbuffers.Builder, height: float):
    BridgeAddHeight(builder, height)

def BridgeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BridgeEnd(builder)

import mqt.scpd.flatbuffers.geometry.Point
try:
    from typing import Optional
except:
    pass

class BridgeT(object):

    # BridgeT
    def __init__(
        self,
        centre = None,
        rotation = 0,
        width = 0.0,
        height = 0.0,
    ):
        self.centre = centre  # type: Optional[mqt.scpd.flatbuffers.geometry.Point.PointT]
        self.rotation = rotation  # type: int
        self.width = width  # type: float
        self.height = height  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bridge = Bridge()
        bridge.Init(buf, pos)
        return cls.InitFromObj(bridge)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, bridge):
        x = BridgeT()
        x._UnPack(bridge)
        return x

    # BridgeT
    def _UnPack(self, bridge):
        if bridge is None:
            return
        if bridge.Centre() is not None:
            self.centre = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(bridge.Centre())
        self.rotation = bridge.Rotation()
        self.width = bridge.Width()
        self.height = bridge.Height()

    # BridgeT
    def Pack(self, builder):
        BridgeStart(builder)
        if self.centre is not None:
            centre = self.centre.Pack(builder)
            BridgeAddCentre(builder, centre)
        BridgeAddRotation(builder, self.rotation)
        BridgeAddWidth(builder, self.width)
        BridgeAddHeight(builder, self.height)
        bridge = BridgeEnd(builder)
        return bridge
