# automatically generated by the FlatBuffers compiler, do not modify

# namespace: design

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.design.Port import Port
from mqt.scpd.flatbuffers.geometry.Polygon import Polygon
from typing import Optional
np = import_numpy()

# The chip: obstacle geometry and ports, exactly as the input carries them.
class Chip(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Chip()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChip(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Chip
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Chip
    def Obstacles(self, j: int) -> Optional[Polygon]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Polygon()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Chip
    def ObstaclesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Chip
    def ObstaclesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Chip
    def Ports(self, j: int) -> Optional[Port]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Port()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Chip
    def PortsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Chip
    def PortsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ChipStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    ChipStart(builder)

def ChipAddObstacles(builder: flatbuffers.Builder, obstacles: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(obstacles), 0)

def AddObstacles(builder: flatbuffers.Builder, obstacles: int):
    ChipAddObstacles(builder, obstacles)

def ChipStartObstaclesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartObstaclesVector(builder, numElems: int) -> int:
    return ChipStartObstaclesVector(builder, numElems)

def ChipAddPorts(builder: flatbuffers.Builder, ports: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ports), 0)

def AddPorts(builder: flatbuffers.Builder, ports: int):
    ChipAddPorts(builder, ports)

def ChipStartPortsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPortsVector(builder, numElems: int) -> int:
    return ChipStartPortsVector(builder, numElems)

def ChipEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ChipEnd(builder)

import mqt.scpd.flatbuffers.design.Port
import mqt.scpd.flatbuffers.geometry.Polygon
try:
    from typing import List
except:
    pass

class ChipT(object):

    # ChipT
    def __init__(
        self,
        obstacles = None,
        ports = None,
    ):
        self.obstacles = obstacles  # type: Optional[List[mqt.scpd.flatbuffers.geometry.Polygon.PolygonT]]
        self.ports = ports  # type: Optional[List[mqt.scpd.flatbuffers.design.Port.PortT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        chip = Chip()
        chip.Init(buf, pos)
        return cls.InitFromObj(chip)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, chip):
        x = ChipT()
        x._UnPack(chip)
        return x

    # ChipT
    def _UnPack(self, chip):
        if chip is None:
            return
        if not chip.ObstaclesIsNone():
            self.obstacles = []
            for i in range(chip.ObstaclesLength()):
                if chip.Obstacles(i) is None:
                    self.obstacles.append(None)
                else:
                    polygon_ = mqt.scpd.flatbuffers.geometry.Polygon.PolygonT.InitFromObj(chip.Obstacles(i))
                    self.obstacles.append(polygon_)
        if not chip.PortsIsNone():
            self.ports = []
            for i in range(chip.PortsLength()):
                if chip.Ports(i) is None:
                    self.ports.append(None)
                else:
                    port_ = mqt.scpd.flatbuffers.design.Port.PortT.InitFromObj(chip.Ports(i))
                    self.ports.append(port_)

    # ChipT
    def Pack(self, builder):
        if self.obstacles is not None:
            obstacleslist = []
            for i in range(len(self.obstacles)):
                obstacleslist.append(self.obstacles[i].Pack(builder))
            ChipStartObstaclesVector(builder, len(self.obstacles))
            for i in reversed(range(len(self.obstacles))):
                builder.PrependUOffsetTRelative(obstacleslist[i])
            obstacles = builder.EndVector()
        if self.ports is not None:
            portslist = []
            for i in range(len(self.ports)):
                portslist.append(self.ports[i].Pack(builder))
            ChipStartPortsVector(builder, len(self.ports))
            for i in reversed(range(len(self.ports))):
                builder.PrependUOffsetTRelative(portslist[i])
            ports = builder.EndVector()
        ChipStart(builder)
        if self.obstacles is not None:
            ChipAddObstacles(builder, obstacles)
        if self.ports is not None:
            ChipAddPorts(builder, ports)
        chip = ChipEnd(builder)
        return chip
