# automatically generated by the FlatBuffers compiler, do not modify

# namespace: design

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# A dense index into the connections of the Assignment stage's output.
class ConnectionRef(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 4

    # ConnectionRef
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConnectionRef
    def Index(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateConnectionRef(builder, index):
    builder.Prep(4, 4)
    builder.PrependUint32(index)
    return builder.Offset()


class ConnectionRefT(object):

    # ConnectionRefT
    def __init__(
        self,
        index = 0,
    ):
        self.index = index  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        connectionRef = ConnectionRef()
        connectionRef.Init(buf, pos)
        return cls.InitFromObj(connectionRef)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, connectionRef):
        x = ConnectionRefT()
        x._UnPack(connectionRef)
        return x

    # ConnectionRefT
    def _UnPack(self, connectionRef):
        if connectionRef is None:
            return
        self.index = connectionRef.Index()

    # ConnectionRefT
    def Pack(self, builder):
        return CreateConnectionRef(builder, self.index)
