# automatically generated by the FlatBuffers compiler, do not modify

# namespace: design

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# The design rules. Every rule is a length in layout units, held once and
# converted to cells only through cells_for. See decision 0019.
class DesignRules(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DesignRules()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDesignRules(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DesignRules
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DesignRules
    def MinWireSpacing(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DesignRules
    def MinObstacleSpacing(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DesignRules
    def MinBendRadius(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DesignRules
    def MinStraightLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DesignRules
    def TargetResonatorLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DesignRules
    def ResonatorLengthTolerance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DesignRules
    def MaxFeedlineUtilization(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DesignRules
    def FeedlineTerminations(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def DesignRulesStart(builder: flatbuffers.Builder):
    builder.StartObject(8)

def Start(builder: flatbuffers.Builder):
    DesignRulesStart(builder)

def DesignRulesAddMinWireSpacing(builder: flatbuffers.Builder, minWireSpacing: float):
    builder.PrependFloat64Slot(0, minWireSpacing, 0.0)

def AddMinWireSpacing(builder: flatbuffers.Builder, minWireSpacing: float):
    DesignRulesAddMinWireSpacing(builder, minWireSpacing)

def DesignRulesAddMinObstacleSpacing(builder: flatbuffers.Builder, minObstacleSpacing: float):
    builder.PrependFloat64Slot(1, minObstacleSpacing, 0.0)

def AddMinObstacleSpacing(builder: flatbuffers.Builder, minObstacleSpacing: float):
    DesignRulesAddMinObstacleSpacing(builder, minObstacleSpacing)

def DesignRulesAddMinBendRadius(builder: flatbuffers.Builder, minBendRadius: float):
    builder.PrependFloat64Slot(2, minBendRadius, 0.0)

def AddMinBendRadius(builder: flatbuffers.Builder, minBendRadius: float):
    DesignRulesAddMinBendRadius(builder, minBendRadius)

def DesignRulesAddMinStraightLength(builder: flatbuffers.Builder, minStraightLength: float):
    builder.PrependFloat64Slot(3, minStraightLength, 0.0)

def AddMinStraightLength(builder: flatbuffers.Builder, minStraightLength: float):
    DesignRulesAddMinStraightLength(builder, minStraightLength)

def DesignRulesAddTargetResonatorLength(builder: flatbuffers.Builder, targetResonatorLength: float):
    builder.PrependFloat64Slot(4, targetResonatorLength, 0.0)

def AddTargetResonatorLength(builder: flatbuffers.Builder, targetResonatorLength: float):
    DesignRulesAddTargetResonatorLength(builder, targetResonatorLength)

def DesignRulesAddResonatorLengthTolerance(builder: flatbuffers.Builder, resonatorLengthTolerance: float):
    builder.PrependFloat64Slot(5, resonatorLengthTolerance, 0.0)

def AddResonatorLengthTolerance(builder: flatbuffers.Builder, resonatorLengthTolerance: float):
    DesignRulesAddResonatorLengthTolerance(builder, resonatorLengthTolerance)

def DesignRulesAddMaxFeedlineUtilization(builder: flatbuffers.Builder, maxFeedlineUtilization: int):
    builder.PrependUint32Slot(6, maxFeedlineUtilization, 0)

def AddMaxFeedlineUtilization(builder: flatbuffers.Builder, maxFeedlineUtilization: int):
    DesignRulesAddMaxFeedlineUtilization(builder, maxFeedlineUtilization)

def DesignRulesAddFeedlineTerminations(builder: flatbuffers.Builder, feedlineTerminations: int):
    builder.PrependUint32Slot(7, feedlineTerminations, 0)

def AddFeedlineTerminations(builder: flatbuffers.Builder, feedlineTerminations: int):
    DesignRulesAddFeedlineTerminations(builder, feedlineTerminations)

def DesignRulesEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return DesignRulesEnd(builder)


class DesignRulesT(object):

    # DesignRulesT
    def __init__(
        self,
        minWireSpacing = 0.0,
        minObstacleSpacing = 0.0,
        minBendRadius = 0.0,
        minStraightLength = 0.0,
        targetResonatorLength = 0.0,
        resonatorLengthTolerance = 0.0,
        maxFeedlineUtilization = 0,
        feedlineTerminations = 0,
    ):
        self.minWireSpacing = minWireSpacing  # type: float
        self.minObstacleSpacing = minObstacleSpacing  # type: float
        self.minBendRadius = minBendRadius  # type: float
        self.minStraightLength = minStraightLength  # type: float
        self.targetResonatorLength = targetResonatorLength  # type: float
        self.resonatorLengthTolerance = resonatorLengthTolerance  # type: float
        self.maxFeedlineUtilization = maxFeedlineUtilization  # type: int
        self.feedlineTerminations = feedlineTerminations  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        designRules = DesignRules()
        designRules.Init(buf, pos)
        return cls.InitFromObj(designRules)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, designRules):
        x = DesignRulesT()
        x._UnPack(designRules)
        return x

    # DesignRulesT
    def _UnPack(self, designRules):
        if designRules is None:
            return
        self.minWireSpacing = designRules.MinWireSpacing()
        self.minObstacleSpacing = designRules.MinObstacleSpacing()
        self.minBendRadius = designRules.MinBendRadius()
        self.minStraightLength = designRules.MinStraightLength()
        self.targetResonatorLength = designRules.TargetResonatorLength()
        self.resonatorLengthTolerance = designRules.ResonatorLengthTolerance()
        self.maxFeedlineUtilization = designRules.MaxFeedlineUtilization()
        self.feedlineTerminations = designRules.FeedlineTerminations()

    # DesignRulesT
    def Pack(self, builder):
        DesignRulesStart(builder)
        DesignRulesAddMinWireSpacing(builder, self.minWireSpacing)
        DesignRulesAddMinObstacleSpacing(builder, self.minObstacleSpacing)
        DesignRulesAddMinBendRadius(builder, self.minBendRadius)
        DesignRulesAddMinStraightLength(builder, self.minStraightLength)
        DesignRulesAddTargetResonatorLength(builder, self.targetResonatorLength)
        DesignRulesAddResonatorLengthTolerance(builder, self.resonatorLengthTolerance)
        DesignRulesAddMaxFeedlineUtilization(builder, self.maxFeedlineUtilization)
        DesignRulesAddFeedlineTerminations(builder, self.feedlineTerminations)
        designRules = DesignRulesEnd(builder)
        return designRules
