# automatically generated by the FlatBuffers compiler, do not modify

# namespace: design

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.geometry.Point import Point
from typing import Optional
np = import_numpy()

# A port of the chip. The label is the only name the input has; no algorithm
# parses it.
class Port(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Port()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPort(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Port
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Port
    def Label(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Port
    def Center(self) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Degrees, as the chip input carries it.
    # Port
    def Orientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Port
    def Role(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def PortStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    PortStart(builder)

def PortAddLabel(builder: flatbuffers.Builder, label: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(label), 0)

def AddLabel(builder: flatbuffers.Builder, label: int):
    PortAddLabel(builder, label)

def PortAddCenter(builder: flatbuffers.Builder, center: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(center), 0)

def AddCenter(builder: flatbuffers.Builder, center: Any):
    PortAddCenter(builder, center)

def PortAddOrientation(builder: flatbuffers.Builder, orientation: float):
    builder.PrependFloat64Slot(2, orientation, 0.0)

def AddOrientation(builder: flatbuffers.Builder, orientation: float):
    PortAddOrientation(builder, orientation)

def PortAddRole(builder: flatbuffers.Builder, role: int):
    builder.PrependUint8Slot(3, role, 0)

def AddRole(builder: flatbuffers.Builder, role: int):
    PortAddRole(builder, role)

def PortEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PortEnd(builder)

import mqt.scpd.flatbuffers.geometry.Point
try:
    from typing import Optional
except:
    pass

class PortT(object):

    # PortT
    def __init__(
        self,
        label = None,
        center = None,
        orientation = 0.0,
        role = 0,
    ):
        self.label = label  # type: Optional[str]
        self.center = center  # type: Optional[mqt.scpd.flatbuffers.geometry.Point.PointT]
        self.orientation = orientation  # type: float
        self.role = role  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        port = Port()
        port.Init(buf, pos)
        return cls.InitFromObj(port)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, port):
        x = PortT()
        x._UnPack(port)
        return x

    # PortT
    def _UnPack(self, port):
        if port is None:
            return
        self.label = port.Label()
        if self.label is not None:
            self.label = self.label.decode('utf-8')
        if port.Center() is not None:
            self.center = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(port.Center())
        self.orientation = port.Orientation()
        self.role = port.Role()

    # PortT
    def Pack(self, builder):
        if self.label is not None:
            label = builder.CreateString(self.label)
        PortStart(builder)
        if self.label is not None:
            PortAddLabel(builder, label)
        if self.center is not None:
            center = self.center.Pack(builder)
            PortAddCenter(builder, center)
        PortAddOrientation(builder, self.orientation)
        PortAddRole(builder, self.role)
        port = PortEnd(builder)
        return port
