# automatically generated by the FlatBuffers compiler, do not modify

# namespace: design

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# A dense index into Chip.ports. A label is resolved to a PortRef once, at
# load. Ports are appended and never reordered, so a PortRef stays valid for
# the life of a run.
class PortRef(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 4

    # PortRef
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PortRef
    def Index(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreatePortRef(builder, index):
    builder.Prep(4, 4)
    builder.PrependUint32(index)
    return builder.Offset()


class PortRefT(object):

    # PortRefT
    def __init__(
        self,
        index = 0,
    ):
        self.index = index  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        portRef = PortRef()
        portRef.Init(buf, pos)
        return cls.InitFromObj(portRef)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, portRef):
        x = PortRefT()
        x._UnPack(portRef)
        return x

    # PortRefT
    def _UnPack(self, portRef):
        if portRef is None:
            return
        self.index = portRef.Index()

    # PortRefT
    def Pack(self, builder):
        return CreatePortRef(builder, self.index)
