# automatically generated by the FlatBuffers compiler, do not modify

# namespace: design

# The eight-way rotation of a placed component.
class Rotation(object):
    Unset = 0
    R0 = 1
    R45 = 2
    R90 = 3
    R135 = 4
    R180 = 5
    R225 = 6
    R270 = 7
    R315 = 8
