# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from flatbuffers.table import Table
from typing import Optional
np = import_numpy()

# The root of every stage artifact.
class Artifact(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Artifact()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArtifact(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ArtifactBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # Artifact
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The mqt-scpd version that wrote the artifact, for provenance.
    # Artifact
    def Producer(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Artifact
    def OutputType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Artifact
    def Output(self) -> Optional[flatbuffers.table.Table]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ArtifactStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    ArtifactStart(builder)

def ArtifactAddProducer(builder: flatbuffers.Builder, producer: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(producer), 0)

def AddProducer(builder: flatbuffers.Builder, producer: int):
    ArtifactAddProducer(builder, producer)

def ArtifactAddOutputType(builder: flatbuffers.Builder, outputType: int):
    builder.PrependUint8Slot(1, outputType, 0)

def AddOutputType(builder: flatbuffers.Builder, outputType: int):
    ArtifactAddOutputType(builder, outputType)

def ArtifactAddOutput(builder: flatbuffers.Builder, output: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(output), 0)

def AddOutput(builder: flatbuffers.Builder, output: int):
    ArtifactAddOutput(builder, output)

def ArtifactEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return ArtifactEnd(builder)

import mqt.scpd.flatbuffers.artifacts.Assignment
import mqt.scpd.flatbuffers.artifacts.CapacityPlan
import mqt.scpd.flatbuffers.artifacts.DetailRouting
import mqt.scpd.flatbuffers.artifacts.FinalRouting
import mqt.scpd.flatbuffers.artifacts.Geometry
import mqt.scpd.flatbuffers.artifacts.GlobalRouting
import mqt.scpd.flatbuffers.artifacts.StageOutput
try:
    from typing import Union
except:
    pass

class ArtifactT(object):

    # ArtifactT
    def __init__(
        self,
        producer = None,
        outputType = 0,
        output = None,
    ):
        self.producer = producer  # type: Optional[str]
        self.outputType = outputType  # type: int
        self.output = output  # type: Union[None, 'mqt.scpd.flatbuffers.artifacts.CapacityPlan.CapacityPlanT', 'mqt.scpd.flatbuffers.artifacts.Assignment.AssignmentT', 'mqt.scpd.flatbuffers.artifacts.GlobalRouting.GlobalRoutingT', 'mqt.scpd.flatbuffers.artifacts.DetailRouting.DetailRoutingT', 'mqt.scpd.flatbuffers.artifacts.FinalRouting.FinalRoutingT', 'mqt.scpd.flatbuffers.artifacts.Geometry.GeometryT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        artifact = Artifact()
        artifact.Init(buf, pos)
        return cls.InitFromObj(artifact)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, artifact):
        x = ArtifactT()
        x._UnPack(artifact)
        return x

    # ArtifactT
    def _UnPack(self, artifact):
        if artifact is None:
            return
        self.producer = artifact.Producer()
        if self.producer is not None:
            self.producer = self.producer.decode('utf-8')
        self.outputType = artifact.OutputType()
        self.output = mqt.scpd.flatbuffers.artifacts.StageOutput.StageOutputCreator(self.outputType, artifact.Output())

    # ArtifactT
    def Pack(self, builder):
        if self.producer is not None:
            producer = builder.CreateString(self.producer)
        if self.output is not None:
            output = self.output.Pack(builder)
        ArtifactStart(builder)
        if self.producer is not None:
            ArtifactAddProducer(builder, producer)
        ArtifactAddOutputType(builder, self.outputType)
        if self.output is not None:
            ArtifactAddOutput(builder, output)
        artifact = ArtifactEnd(builder)
        return artifact
