# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.design.Connection import Connection
from mqt.scpd.flatbuffers.design.PortRef import PortRef
from mqt.scpd.flatbuffers.geometry.Point import Point
from typing import Optional
np = import_numpy()

# Output of the Assignment stage.
class Assignment(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Assignment()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAssignment(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AssignmentBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # Assignment
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Assignment
    def Connections(self, j: int) -> Optional[Connection]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Connection()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Assignment
    def ConnectionsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Assignment
    def ConnectionsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Assignment
    def Objective(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # The ring the model consumed, in the order it consumed it.
    # Assignment
    def Ring(self, j: int) -> Optional[PortRef]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            obj = PortRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Assignment
    def RingLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Assignment
    def RingIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # The launcher each ring node was given, parallel to `ring`.
    # Assignment
    def Launchers(self, j: int) -> Optional[PortRef]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            obj = PortRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Assignment
    def LaunchersLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Assignment
    def LaunchersIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Where each ring node is actually fed from, parallel to `ring`.
    #
    # Usually the launcher slot `launchers` names. A resonator that ends a
    # feedline is not fed at a launcher at all: the run reaches it from one
    # side only, so the feed starts at a new slot on the segment between its
    # own launcher and the one its neighbour on the open side was given.
    # Assignment
    def Feeds(self, j: int) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Assignment
    def FeedsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Assignment
    def FeedsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def AssignmentStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    AssignmentStart(builder)

def AssignmentAddConnections(builder: flatbuffers.Builder, connections: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(connections), 0)

def AddConnections(builder: flatbuffers.Builder, connections: int):
    AssignmentAddConnections(builder, connections)

def AssignmentStartConnectionsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartConnectionsVector(builder, numElems: int) -> int:
    return AssignmentStartConnectionsVector(builder, numElems)

def AssignmentAddObjective(builder: flatbuffers.Builder, objective: float):
    builder.PrependFloat64Slot(1, objective, 0.0)

def AddObjective(builder: flatbuffers.Builder, objective: float):
    AssignmentAddObjective(builder, objective)

def AssignmentAddRing(builder: flatbuffers.Builder, ring: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ring), 0)

def AddRing(builder: flatbuffers.Builder, ring: int):
    AssignmentAddRing(builder, ring)

def AssignmentStartRingVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartRingVector(builder, numElems: int) -> int:
    return AssignmentStartRingVector(builder, numElems)

def AssignmentAddLaunchers(builder: flatbuffers.Builder, launchers: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(launchers), 0)

def AddLaunchers(builder: flatbuffers.Builder, launchers: int):
    AssignmentAddLaunchers(builder, launchers)

def AssignmentStartLaunchersVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartLaunchersVector(builder, numElems: int) -> int:
    return AssignmentStartLaunchersVector(builder, numElems)

def AssignmentAddFeeds(builder: flatbuffers.Builder, feeds: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(feeds), 0)

def AddFeeds(builder: flatbuffers.Builder, feeds: int):
    AssignmentAddFeeds(builder, feeds)

def AssignmentStartFeedsVector(builder, numElems: int) -> int:
    return builder.StartVector(16, numElems, 8)

def StartFeedsVector(builder, numElems: int) -> int:
    return AssignmentStartFeedsVector(builder, numElems)

def AssignmentEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return AssignmentEnd(builder)

import mqt.scpd.flatbuffers.design.Connection
import mqt.scpd.flatbuffers.design.PortRef
import mqt.scpd.flatbuffers.geometry.Point
try:
    from typing import List
except:
    pass

class AssignmentT(object):

    # AssignmentT
    def __init__(
        self,
        connections = None,
        objective = 0.0,
        ring = None,
        launchers = None,
        feeds = None,
    ):
        self.connections = connections  # type: Optional[List[mqt.scpd.flatbuffers.design.Connection.ConnectionT]]
        self.objective = objective  # type: float
        self.ring = ring  # type: Optional[List[mqt.scpd.flatbuffers.design.PortRef.PortRefT]]
        self.launchers = launchers  # type: Optional[List[mqt.scpd.flatbuffers.design.PortRef.PortRefT]]
        self.feeds = feeds  # type: Optional[List[mqt.scpd.flatbuffers.geometry.Point.PointT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        assignment = Assignment()
        assignment.Init(buf, pos)
        return cls.InitFromObj(assignment)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, assignment):
        x = AssignmentT()
        x._UnPack(assignment)
        return x

    # AssignmentT
    def _UnPack(self, assignment):
        if assignment is None:
            return
        if not assignment.ConnectionsIsNone():
            self.connections = []
            for i in range(assignment.ConnectionsLength()):
                if assignment.Connections(i) is None:
                    self.connections.append(None)
                else:
                    connection_ = mqt.scpd.flatbuffers.design.Connection.ConnectionT.InitFromObj(assignment.Connections(i))
                    self.connections.append(connection_)
        self.objective = assignment.Objective()
        if not assignment.RingIsNone():
            self.ring = []
            for i in range(assignment.RingLength()):
                if assignment.Ring(i) is None:
                    self.ring.append(None)
                else:
                    portRef_ = mqt.scpd.flatbuffers.design.PortRef.PortRefT.InitFromObj(assignment.Ring(i))
                    self.ring.append(portRef_)
        if not assignment.LaunchersIsNone():
            self.launchers = []
            for i in range(assignment.LaunchersLength()):
                if assignment.Launchers(i) is None:
                    self.launchers.append(None)
                else:
                    portRef_ = mqt.scpd.flatbuffers.design.PortRef.PortRefT.InitFromObj(assignment.Launchers(i))
                    self.launchers.append(portRef_)
        if not assignment.FeedsIsNone():
            self.feeds = []
            for i in range(assignment.FeedsLength()):
                if assignment.Feeds(i) is None:
                    self.feeds.append(None)
                else:
                    point_ = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(assignment.Feeds(i))
                    self.feeds.append(point_)

    # AssignmentT
    def Pack(self, builder):
        if self.connections is not None:
            connectionslist = []
            for i in range(len(self.connections)):
                connectionslist.append(self.connections[i].Pack(builder))
            AssignmentStartConnectionsVector(builder, len(self.connections))
            for i in reversed(range(len(self.connections))):
                builder.PrependUOffsetTRelative(connectionslist[i])
            connections = builder.EndVector()
        if self.ring is not None:
            AssignmentStartRingVector(builder, len(self.ring))
            for i in reversed(range(len(self.ring))):
                self.ring[i].Pack(builder)
            ring = builder.EndVector()
        if self.launchers is not None:
            AssignmentStartLaunchersVector(builder, len(self.launchers))
            for i in reversed(range(len(self.launchers))):
                self.launchers[i].Pack(builder)
            launchers = builder.EndVector()
        if self.feeds is not None:
            AssignmentStartFeedsVector(builder, len(self.feeds))
            for i in reversed(range(len(self.feeds))):
                self.feeds[i].Pack(builder)
            feeds = builder.EndVector()
        AssignmentStart(builder)
        if self.connections is not None:
            AssignmentAddConnections(builder, connections)
        AssignmentAddObjective(builder, self.objective)
        if self.ring is not None:
            AssignmentAddRing(builder, ring)
        if self.launchers is not None:
            AssignmentAddLaunchers(builder, launchers)
        if self.feeds is not None:
            AssignmentAddFeeds(builder, feeds)
        assignment = AssignmentEnd(builder)
        return assignment
