# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.geometry.Point import Point
from typing import Optional
np = import_numpy()

# The crossing slots of one partition border.
#
# A wire leaves one partition for another at one of these, and no two wires
# take the same one. The slots sit one wire spacing apart along the border,
# so their count is what the border can carry, which is what
# `PartitionBorder.budget` reports.
class BorderSlots(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BorderSlots()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBorderSlots(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BorderSlotsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # BorderSlots
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The border they belong to, as an index into CapacityPlan.borders, or
    # zero when `pocket` is set and they are on no border at all.
    # BorderSlots
    def Border(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # The slots in layout units, in the order the border runs.
    # BorderSlots
    def Positions(self, j: int) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BorderSlots
    def PositionsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BorderSlots
    def PositionsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Whether these are ways out of a port's own pocket rather than slots of a
    # border.
    #
    # The capacity grid places a target on the first cell beyond its port's
    # band that was free before the bands, and does not open the band. Where
    # the band and the artwork close around a port, the free space left is a
    # pocket that no border reaches; the band is that port's own approach, so
    # it is a way out, and it carries the one wire.
    # BorderSlots
    def Pocket(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BorderSlotsStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    BorderSlotsStart(builder)

def BorderSlotsAddBorder(builder: flatbuffers.Builder, border: int):
    builder.PrependUint32Slot(0, border, 0)

def AddBorder(builder: flatbuffers.Builder, border: int):
    BorderSlotsAddBorder(builder, border)

def BorderSlotsAddPositions(builder: flatbuffers.Builder, positions: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(positions), 0)

def AddPositions(builder: flatbuffers.Builder, positions: int):
    BorderSlotsAddPositions(builder, positions)

def BorderSlotsStartPositionsVector(builder, numElems: int) -> int:
    return builder.StartVector(16, numElems, 8)

def StartPositionsVector(builder, numElems: int) -> int:
    return BorderSlotsStartPositionsVector(builder, numElems)

def BorderSlotsAddPocket(builder: flatbuffers.Builder, pocket: bool):
    builder.PrependBoolSlot(2, pocket, 0)

def AddPocket(builder: flatbuffers.Builder, pocket: bool):
    BorderSlotsAddPocket(builder, pocket)

def BorderSlotsEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BorderSlotsEnd(builder)

import mqt.scpd.flatbuffers.geometry.Point
try:
    from typing import List
except:
    pass

class BorderSlotsT(object):

    # BorderSlotsT
    def __init__(
        self,
        border = 0,
        positions = None,
        pocket = False,
    ):
        self.border = border  # type: int
        self.positions = positions  # type: Optional[List[mqt.scpd.flatbuffers.geometry.Point.PointT]]
        self.pocket = pocket  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        borderSlots = BorderSlots()
        borderSlots.Init(buf, pos)
        return cls.InitFromObj(borderSlots)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, borderSlots):
        x = BorderSlotsT()
        x._UnPack(borderSlots)
        return x

    # BorderSlotsT
    def _UnPack(self, borderSlots):
        if borderSlots is None:
            return
        self.border = borderSlots.Border()
        if not borderSlots.PositionsIsNone():
            self.positions = []
            for i in range(borderSlots.PositionsLength()):
                if borderSlots.Positions(i) is None:
                    self.positions.append(None)
                else:
                    point_ = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(borderSlots.Positions(i))
                    self.positions.append(point_)
        self.pocket = borderSlots.Pocket()

    # BorderSlotsT
    def Pack(self, builder):
        if self.positions is not None:
            BorderSlotsStartPositionsVector(builder, len(self.positions))
            for i in reversed(range(len(self.positions))):
                self.positions[i].Pack(builder)
            positions = builder.EndVector()
        BorderSlotsStart(builder)
        BorderSlotsAddBorder(builder, self.border)
        if self.positions is not None:
            BorderSlotsAddPositions(builder, positions)
        BorderSlotsAddPocket(builder, self.pocket)
        borderSlots = BorderSlotsEnd(builder)
        return borderSlots
