# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.geometry.Point import Point
from typing import Optional
np = import_numpy()

# The narrowest place of a corridor: the two obstacle points that face each
# other across it, and how many wires fit between them.
class Bottleneck(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Bottleneck()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBottleneck(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BottleneckBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # Bottleneck
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bottleneck
    def From(self) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Bottleneck
    def To(self) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Bottleneck
    def Capacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def BottleneckStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    BottleneckStart(builder)

def BottleneckAddFrom(builder: flatbuffers.Builder, from_: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(from_), 0)

def AddFrom(builder: flatbuffers.Builder, from_: Any):
    BottleneckAddFrom(builder, from_)

def BottleneckAddTo(builder: flatbuffers.Builder, to: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(to), 0)

def AddTo(builder: flatbuffers.Builder, to: Any):
    BottleneckAddTo(builder, to)

def BottleneckAddCapacity(builder: flatbuffers.Builder, capacity: int):
    builder.PrependUint32Slot(2, capacity, 0)

def AddCapacity(builder: flatbuffers.Builder, capacity: int):
    BottleneckAddCapacity(builder, capacity)

def BottleneckEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return BottleneckEnd(builder)

import mqt.scpd.flatbuffers.geometry.Point
try:
    from typing import Optional
except:
    pass

class BottleneckT(object):

    # BottleneckT
    def __init__(
        self,
        from_ = None,
        to = None,
        capacity = 0,
    ):
        self.from_ = from_  # type: Optional[mqt.scpd.flatbuffers.geometry.Point.PointT]
        self.to = to  # type: Optional[mqt.scpd.flatbuffers.geometry.Point.PointT]
        self.capacity = capacity  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bottleneck = Bottleneck()
        bottleneck.Init(buf, pos)
        return cls.InitFromObj(bottleneck)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, bottleneck):
        x = BottleneckT()
        x._UnPack(bottleneck)
        return x

    # BottleneckT
    def _UnPack(self, bottleneck):
        if bottleneck is None:
            return
        if bottleneck.From() is not None:
            self.from_ = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(bottleneck.From())
        if bottleneck.To() is not None:
            self.to = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(bottleneck.To())
        self.capacity = bottleneck.Capacity()

    # BottleneckT
    def Pack(self, builder):
        BottleneckStart(builder)
        if self.from_ is not None:
            from_ = self.from_.Pack(builder)
            BottleneckAddFrom(builder, from_)
        if self.to is not None:
            to = self.to.Pack(builder)
            BottleneckAddTo(builder, to)
        BottleneckAddCapacity(builder, self.capacity)
        bottleneck = BottleneckEnd(builder)
        return bottleneck
