# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

# What one link of a capacity chain stands for.
class CapacityElement(object):
    Unset = 0
    # A port the chain has to serve.
    Target = 1
    # A gate the wires beyond it have to pass.
    Bottleneck = 2
    # The launcher the chain is rooted at.
    Launcher = 3
