# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# One link of a capacity chain.
#
# A chain is a tree and FlatBuffers has no recursive table, so the nodes are
# stored flat and a link names its branches by index. That also lets two
# chains share a subtree without storing it twice.
class CapacityNode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CapacityNode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCapacityNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CapacityNodeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # CapacityNode
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CapacityNode
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # The port for a Target and the index into `bottlenecks` for a
    # Bottleneck. Unused for a Launcher.
    # CapacityNode
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # How many wires this link lets through. Only a Bottleneck limits.
    # CapacityNode
    def Capacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Indices into CapacityPlan.nodes.
    # CapacityNode
    def Next(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # CapacityNode
    def NextAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # CapacityNode
    def NextLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CapacityNode
    def NextIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def CapacityNodeStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    CapacityNodeStart(builder)

def CapacityNodeAddKind(builder: flatbuffers.Builder, kind: int):
    builder.PrependUint8Slot(0, kind, 0)

def AddKind(builder: flatbuffers.Builder, kind: int):
    CapacityNodeAddKind(builder, kind)

def CapacityNodeAddId(builder: flatbuffers.Builder, id: int):
    builder.PrependUint32Slot(1, id, 0)

def AddId(builder: flatbuffers.Builder, id: int):
    CapacityNodeAddId(builder, id)

def CapacityNodeAddCapacity(builder: flatbuffers.Builder, capacity: int):
    builder.PrependUint32Slot(2, capacity, 0)

def AddCapacity(builder: flatbuffers.Builder, capacity: int):
    CapacityNodeAddCapacity(builder, capacity)

def CapacityNodeAddNext(builder: flatbuffers.Builder, next: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(next), 0)

def AddNext(builder: flatbuffers.Builder, next: int):
    CapacityNodeAddNext(builder, next)

def CapacityNodeStartNextVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartNextVector(builder, numElems: int) -> int:
    return CapacityNodeStartNextVector(builder, numElems)

def CapacityNodeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CapacityNodeEnd(builder)

try:
    from typing import List
except:
    pass

class CapacityNodeT(object):

    # CapacityNodeT
    def __init__(
        self,
        kind = 0,
        id = 0,
        capacity = 0,
        next = None,
    ):
        self.kind = kind  # type: int
        self.id = id  # type: int
        self.capacity = capacity  # type: int
        self.next = next  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        capacityNode = CapacityNode()
        capacityNode.Init(buf, pos)
        return cls.InitFromObj(capacityNode)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, capacityNode):
        x = CapacityNodeT()
        x._UnPack(capacityNode)
        return x

    # CapacityNodeT
    def _UnPack(self, capacityNode):
        if capacityNode is None:
            return
        self.kind = capacityNode.Kind()
        self.id = capacityNode.Id()
        self.capacity = capacityNode.Capacity()
        if not capacityNode.NextIsNone():
            if np is None:
                self.next = []
                for i in range(capacityNode.NextLength()):
                    self.next.append(capacityNode.Next(i))
            else:
                self.next = capacityNode.NextAsNumpy()

    # CapacityNodeT
    def Pack(self, builder):
        if self.next is not None:
            if np is not None and type(self.next) is np.ndarray:
                next = builder.CreateNumpyVector(self.next)
            else:
                CapacityNodeStartNextVector(builder, len(self.next))
                for i in reversed(range(len(self.next))):
                    builder.PrependUint32(self.next[i])
                next = builder.EndVector()
        CapacityNodeStart(builder)
        CapacityNodeAddKind(builder, self.kind)
        CapacityNodeAddId(builder, self.id)
        CapacityNodeAddCapacity(builder, self.capacity)
        if self.next is not None:
            CapacityNodeAddNext(builder, next)
        capacityNode = CapacityNodeEnd(builder)
        return capacityNode
