# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.artifacts.BorderSlots import BorderSlots
from mqt.scpd.flatbuffers.artifacts.Corridor import Corridor
from typing import Optional
np = import_numpy()

# Output of the Corridor stage.
#
# One entry per connection of the Assignment, in its order. A connection
# the stage could not route carries no partitions, so a reader counts the
# failures rather than being handed a separate list that can disagree with
# the routes beside it.
class CorridorRouting(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CorridorRouting()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCorridorRouting(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CorridorRoutingBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # CorridorRouting
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CorridorRouting
    def Corridors(self, j: int) -> Optional[Corridor]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Corridor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CorridorRouting
    def CorridorsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CorridorRouting
    def CorridorsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # The slots of every border a wire could cross, so a picture can show
    # which of them are taken. Parallel to nothing: a border with no free
    # space on either side has no entry.
    # CorridorRouting
    def Slots(self, j: int) -> Optional[BorderSlots]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = BorderSlots()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CorridorRouting
    def SlotsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CorridorRouting
    def SlotsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def CorridorRoutingStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    CorridorRoutingStart(builder)

def CorridorRoutingAddCorridors(builder: flatbuffers.Builder, corridors: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(corridors), 0)

def AddCorridors(builder: flatbuffers.Builder, corridors: int):
    CorridorRoutingAddCorridors(builder, corridors)

def CorridorRoutingStartCorridorsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartCorridorsVector(builder, numElems: int) -> int:
    return CorridorRoutingStartCorridorsVector(builder, numElems)

def CorridorRoutingAddSlots(builder: flatbuffers.Builder, slots: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(slots), 0)

def AddSlots(builder: flatbuffers.Builder, slots: int):
    CorridorRoutingAddSlots(builder, slots)

def CorridorRoutingStartSlotsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSlotsVector(builder, numElems: int) -> int:
    return CorridorRoutingStartSlotsVector(builder, numElems)

def CorridorRoutingEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CorridorRoutingEnd(builder)

import mqt.scpd.flatbuffers.artifacts.BorderSlots
import mqt.scpd.flatbuffers.artifacts.Corridor
try:
    from typing import List
except:
    pass

class CorridorRoutingT(object):

    # CorridorRoutingT
    def __init__(
        self,
        corridors = None,
        slots = None,
    ):
        self.corridors = corridors  # type: Optional[List[mqt.scpd.flatbuffers.artifacts.Corridor.CorridorT]]
        self.slots = slots  # type: Optional[List[mqt.scpd.flatbuffers.artifacts.BorderSlots.BorderSlotsT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        corridorRouting = CorridorRouting()
        corridorRouting.Init(buf, pos)
        return cls.InitFromObj(corridorRouting)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, corridorRouting):
        x = CorridorRoutingT()
        x._UnPack(corridorRouting)
        return x

    # CorridorRoutingT
    def _UnPack(self, corridorRouting):
        if corridorRouting is None:
            return
        if not corridorRouting.CorridorsIsNone():
            self.corridors = []
            for i in range(corridorRouting.CorridorsLength()):
                if corridorRouting.Corridors(i) is None:
                    self.corridors.append(None)
                else:
                    corridor_ = mqt.scpd.flatbuffers.artifacts.Corridor.CorridorT.InitFromObj(corridorRouting.Corridors(i))
                    self.corridors.append(corridor_)
        if not corridorRouting.SlotsIsNone():
            self.slots = []
            for i in range(corridorRouting.SlotsLength()):
                if corridorRouting.Slots(i) is None:
                    self.slots.append(None)
                else:
                    borderSlots_ = mqt.scpd.flatbuffers.artifacts.BorderSlots.BorderSlotsT.InitFromObj(corridorRouting.Slots(i))
                    self.slots.append(borderSlots_)

    # CorridorRoutingT
    def Pack(self, builder):
        if self.corridors is not None:
            corridorslist = []
            for i in range(len(self.corridors)):
                corridorslist.append(self.corridors[i].Pack(builder))
            CorridorRoutingStartCorridorsVector(builder, len(self.corridors))
            for i in reversed(range(len(self.corridors))):
                builder.PrependUOffsetTRelative(corridorslist[i])
            corridors = builder.EndVector()
        if self.slots is not None:
            slotslist = []
            for i in range(len(self.slots)):
                slotslist.append(self.slots[i].Pack(builder))
            CorridorRoutingStartSlotsVector(builder, len(self.slots))
            for i in reversed(range(len(self.slots))):
                builder.PrependUOffsetTRelative(slotslist[i])
            slots = builder.EndVector()
        CorridorRoutingStart(builder)
        if self.corridors is not None:
            CorridorRoutingAddCorridors(builder, corridors)
        if self.slots is not None:
            CorridorRoutingAddSlots(builder, slots)
        corridorRouting = CorridorRoutingEnd(builder)
        return corridorRouting
