# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.geometry.Point import Point
from typing import Optional
np = import_numpy()

# The coarse route of one connection: which partitions it passes through,
# and where it crosses from each into the next.
class Corridor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Corridor()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCorridor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def CorridorBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # Corridor
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The labels of the partitions, from the one the wire is fed in to the
    # one its target sits in. These are `Partition.label` values, not indices
    # into `CapacityPlan.partitions`.
    # Corridor
    def Partitions(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Corridor
    def PartitionsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Corridor
    def PartitionsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Corridor
    def PartitionsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # The crossing slots between them, in layout units. One shorter than
    # `partitions`.
    # Corridor
    def Crossings(self, j: int) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Corridor
    def CrossingsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Corridor
    def CrossingsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Where the wire starts: the cell the feed of the assignment was placed
    # at. Absent when the connection has no feed the grid can reach.
    # Corridor
    def Source(self) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Where it ends: the cell its target port is reached at. Absent when the
    # chip has no such cell.
    # Corridor
    def Target(self) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = o + self._tab.Pos
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CorridorStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    CorridorStart(builder)

def CorridorAddPartitions(builder: flatbuffers.Builder, partitions: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(partitions), 0)

def AddPartitions(builder: flatbuffers.Builder, partitions: int):
    CorridorAddPartitions(builder, partitions)

def CorridorStartPartitionsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPartitionsVector(builder, numElems: int) -> int:
    return CorridorStartPartitionsVector(builder, numElems)

def CorridorAddCrossings(builder: flatbuffers.Builder, crossings: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(crossings), 0)

def AddCrossings(builder: flatbuffers.Builder, crossings: int):
    CorridorAddCrossings(builder, crossings)

def CorridorStartCrossingsVector(builder, numElems: int) -> int:
    return builder.StartVector(16, numElems, 8)

def StartCrossingsVector(builder, numElems: int) -> int:
    return CorridorStartCrossingsVector(builder, numElems)

def CorridorAddSource(builder: flatbuffers.Builder, source: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(source), 0)

def AddSource(builder: flatbuffers.Builder, source: Any):
    CorridorAddSource(builder, source)

def CorridorAddTarget(builder: flatbuffers.Builder, target: Any):
    builder.PrependStructSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(target), 0)

def AddTarget(builder: flatbuffers.Builder, target: Any):
    CorridorAddTarget(builder, target)

def CorridorEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return CorridorEnd(builder)

import mqt.scpd.flatbuffers.geometry.Point
try:
    from typing import List, Optional
except:
    pass

class CorridorT(object):

    # CorridorT
    def __init__(
        self,
        partitions = None,
        crossings = None,
        source = None,
        target = None,
    ):
        self.partitions = partitions  # type: Optional[List[int]]
        self.crossings = crossings  # type: Optional[List[mqt.scpd.flatbuffers.geometry.Point.PointT]]
        self.source = source  # type: Optional[mqt.scpd.flatbuffers.geometry.Point.PointT]
        self.target = target  # type: Optional[mqt.scpd.flatbuffers.geometry.Point.PointT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        corridor = Corridor()
        corridor.Init(buf, pos)
        return cls.InitFromObj(corridor)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, corridor):
        x = CorridorT()
        x._UnPack(corridor)
        return x

    # CorridorT
    def _UnPack(self, corridor):
        if corridor is None:
            return
        if not corridor.PartitionsIsNone():
            if np is None:
                self.partitions = []
                for i in range(corridor.PartitionsLength()):
                    self.partitions.append(corridor.Partitions(i))
            else:
                self.partitions = corridor.PartitionsAsNumpy()
        if not corridor.CrossingsIsNone():
            self.crossings = []
            for i in range(corridor.CrossingsLength()):
                if corridor.Crossings(i) is None:
                    self.crossings.append(None)
                else:
                    point_ = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(corridor.Crossings(i))
                    self.crossings.append(point_)
        if corridor.Source() is not None:
            self.source = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(corridor.Source())
        if corridor.Target() is not None:
            self.target = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(corridor.Target())

    # CorridorT
    def Pack(self, builder):
        if self.partitions is not None:
            if np is not None and type(self.partitions) is np.ndarray:
                partitions = builder.CreateNumpyVector(self.partitions)
            else:
                CorridorStartPartitionsVector(builder, len(self.partitions))
                for i in reversed(range(len(self.partitions))):
                    builder.PrependUint32(self.partitions[i])
                partitions = builder.EndVector()
        if self.crossings is not None:
            CorridorStartCrossingsVector(builder, len(self.crossings))
            for i in reversed(range(len(self.crossings))):
                self.crossings[i].Pack(builder)
            crossings = builder.EndVector()
        CorridorStart(builder)
        if self.partitions is not None:
            CorridorAddPartitions(builder, partitions)
        if self.crossings is not None:
            CorridorAddCrossings(builder, crossings)
        if self.source is not None:
            source = self.source.Pack(builder)
            CorridorAddSource(builder, source)
        if self.target is not None:
            target = self.target.Pack(builder)
            CorridorAddTarget(builder, target)
        corridor = CorridorEnd(builder)
        return corridor
