# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.design.PortRef import PortRef
from typing import Optional
np = import_numpy()

# One edge of a feedline chain: what it runs between and how it is treated.
class FeedlineEdge(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FeedlineEdge()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFeedlineEdge(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FeedlineEdgeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # FeedlineEdge
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # The chain of the Assignment it belongs to.
    # FeedlineEdge
    def Chain(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # The ports the edge runs between: a launcher of the chip, or the port a
    # coupler created, which is the coupler's own `ResonatorSource` port.
    # FeedlineEdge
    def From(self) -> Optional[PortRef]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = PortRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FeedlineEdge
    def To(self) -> Optional[PortRef]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            obj = PortRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Whether the edge starts or ends at a launcher. Such an edge is a hard
    # obstacle for every wire and the clearance rule checks it; an edge from
    # one coupler to the next is crossed by the wires between them, at a
    # right angle, and the clearance rule leaves it out.
    # FeedlineEdge
    def Terminal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def FeedlineEdgeStart(builder: flatbuffers.Builder):
    builder.StartObject(4)

def Start(builder: flatbuffers.Builder):
    FeedlineEdgeStart(builder)

def FeedlineEdgeAddChain(builder: flatbuffers.Builder, chain: int):
    builder.PrependUint32Slot(0, chain, 0)

def AddChain(builder: flatbuffers.Builder, chain: int):
    FeedlineEdgeAddChain(builder, chain)

def FeedlineEdgeAddFrom(builder: flatbuffers.Builder, from_: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(from_), 0)

def AddFrom(builder: flatbuffers.Builder, from_: Any):
    FeedlineEdgeAddFrom(builder, from_)

def FeedlineEdgeAddTo(builder: flatbuffers.Builder, to: Any):
    builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(to), 0)

def AddTo(builder: flatbuffers.Builder, to: Any):
    FeedlineEdgeAddTo(builder, to)

def FeedlineEdgeAddTerminal(builder: flatbuffers.Builder, terminal: bool):
    builder.PrependBoolSlot(3, terminal, 0)

def AddTerminal(builder: flatbuffers.Builder, terminal: bool):
    FeedlineEdgeAddTerminal(builder, terminal)

def FeedlineEdgeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FeedlineEdgeEnd(builder)

import mqt.scpd.flatbuffers.design.PortRef
try:
    from typing import Optional
except:
    pass

class FeedlineEdgeT(object):

    # FeedlineEdgeT
    def __init__(
        self,
        chain = 0,
        from_ = None,
        to = None,
        terminal = False,
    ):
        self.chain = chain  # type: int
        self.from_ = from_  # type: Optional[mqt.scpd.flatbuffers.design.PortRef.PortRefT]
        self.to = to  # type: Optional[mqt.scpd.flatbuffers.design.PortRef.PortRefT]
        self.terminal = terminal  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        feedlineEdge = FeedlineEdge()
        feedlineEdge.Init(buf, pos)
        return cls.InitFromObj(feedlineEdge)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, feedlineEdge):
        x = FeedlineEdgeT()
        x._UnPack(feedlineEdge)
        return x

    # FeedlineEdgeT
    def _UnPack(self, feedlineEdge):
        if feedlineEdge is None:
            return
        self.chain = feedlineEdge.Chain()
        if feedlineEdge.From() is not None:
            self.from_ = mqt.scpd.flatbuffers.design.PortRef.PortRefT.InitFromObj(feedlineEdge.From())
        if feedlineEdge.To() is not None:
            self.to = mqt.scpd.flatbuffers.design.PortRef.PortRefT.InitFromObj(feedlineEdge.To())
        self.terminal = feedlineEdge.Terminal()

    # FeedlineEdgeT
    def Pack(self, builder):
        FeedlineEdgeStart(builder)
        FeedlineEdgeAddChain(builder, self.chain)
        if self.from_ is not None:
            from_ = self.from_.Pack(builder)
            FeedlineEdgeAddFrom(builder, from_)
        if self.to is not None:
            to = self.to.Pack(builder)
            FeedlineEdgeAddTo(builder, to)
        FeedlineEdgeAddTerminal(builder, self.terminal)
        feedlineEdge = FeedlineEdgeEnd(builder)
        return feedlineEdge
