# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.geometry.RCoord import RCoord
from typing import Optional
np = import_numpy()

# One wire's path on the router grid, cell by cell.
#
# The cells run from the point the wire is fed at to the cell its target port
# is reached at, and each one carries the heading the search held in it, so
# the bend structure survives into the geometry. A wire the stage could not
# draw carries no cells, so a reader counts the failures rather than being
# handed a separate list that can disagree with the paths beside it.
class FinalWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FinalWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFinalWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FinalWireBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # FinalWire
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FinalWire
    def Path(self, j: int) -> Optional[RCoord]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            obj = RCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FinalWire
    def PathLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FinalWire
    def PathIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def FinalWireStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    FinalWireStart(builder)

def FinalWireAddPath(builder: flatbuffers.Builder, path: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)

def AddPath(builder: flatbuffers.Builder, path: int):
    FinalWireAddPath(builder, path)

def FinalWireStartPathVector(builder, numElems: int) -> int:
    return builder.StartVector(12, numElems, 4)

def StartPathVector(builder, numElems: int) -> int:
    return FinalWireStartPathVector(builder, numElems)

def FinalWireEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FinalWireEnd(builder)

import mqt.scpd.flatbuffers.geometry.RCoord
try:
    from typing import List
except:
    pass

class FinalWireT(object):

    # FinalWireT
    def __init__(
        self,
        path = None,
    ):
        self.path = path  # type: Optional[List[mqt.scpd.flatbuffers.geometry.RCoord.RCoordT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        finalWire = FinalWire()
        finalWire.Init(buf, pos)
        return cls.InitFromObj(finalWire)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, finalWire):
        x = FinalWireT()
        x._UnPack(finalWire)
        return x

    # FinalWireT
    def _UnPack(self, finalWire):
        if finalWire is None:
            return
        if not finalWire.PathIsNone():
            self.path = []
            for i in range(finalWire.PathLength()):
                if finalWire.Path(i) is None:
                    self.path.append(None)
                else:
                    rCoord_ = mqt.scpd.flatbuffers.geometry.RCoord.RCoordT.InitFromObj(finalWire.Path(i))
                    self.path.append(rCoord_)

    # FinalWireT
    def Pack(self, builder):
        if self.path is not None:
            FinalWireStartPathVector(builder, len(self.path))
            for i in reversed(range(len(self.path))):
                self.path[i].Pack(builder)
            path = builder.EndVector()
        FinalWireStart(builder)
        if self.path is not None:
            FinalWireAddPath(builder, path)
        finalWire = FinalWireEnd(builder)
        return finalWire
