# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.geometry.RCoord import RCoord
from typing import Optional
np = import_numpy()

# One wire's path on the router grid, cell by cell.
#
# The cells run from the point the wire is fed at to the cell its target port
# is reached at, and each one carries the heading the search held in it, so
# the bend structure survives into the geometry. A wire the stage could not
# draw carries no cells, so a reader counts the failures rather than being
# handed a separate list that can disagree with the paths beside it.
class FinalWire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FinalWire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFinalWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FinalWireBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # FinalWire
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FinalWire
    def Path(self, j: int) -> Optional[RCoord]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            obj = RCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FinalWire
    def PathLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FinalWire
    def PathIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # How long the path is, in layout units, as the stage renders it: the
    # exact curves of its bends and not the cells they sweep. Zero for a wire
    # that carries no cells. The Final stage lengthens a resonator's way to
    # `meander_length` with a meander, and this is the figure it measured.
    # FinalWire
    def Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # What the stage held against the wire when it ended, as the bits of
    # `FinalVerdict`; zero for a wire nothing was held against. Set on the
    # end state only — the phase snapshots carry zero, because they are not
    # judged — so that a renderer can mark the wires the stage left failing
    # without re-deriving the stage's own count.
    # FinalWire
    def Verdict(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # What the stage says about the wire in words, for a picture's tooltip:
    # the figures behind a `Squeezed` verdict, say. Empty for most wires.
    # FinalWire
    def Note(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Cells of a line the stage draws beside the wire to show what `note`
    # measured: for a `Squeezed` edge the two ends of the line from the
    # edge to the wall of its channel, the worst line it found. Empty for
    # most wires.
    # FinalWire
    def Marks(self, j: int) -> Optional[RCoord]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            obj = RCoord()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FinalWire
    def MarksLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FinalWire
    def MarksIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def FinalWireStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    FinalWireStart(builder)

def FinalWireAddPath(builder: flatbuffers.Builder, path: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)

def AddPath(builder: flatbuffers.Builder, path: int):
    FinalWireAddPath(builder, path)

def FinalWireStartPathVector(builder, numElems: int) -> int:
    return builder.StartVector(12, numElems, 4)

def StartPathVector(builder, numElems: int) -> int:
    return FinalWireStartPathVector(builder, numElems)

def FinalWireAddLength(builder: flatbuffers.Builder, length: float):
    builder.PrependFloat64Slot(1, length, 0.0)

def AddLength(builder: flatbuffers.Builder, length: float):
    FinalWireAddLength(builder, length)

def FinalWireAddVerdict(builder: flatbuffers.Builder, verdict: int):
    builder.PrependUint8Slot(2, verdict, 0)

def AddVerdict(builder: flatbuffers.Builder, verdict: int):
    FinalWireAddVerdict(builder, verdict)

def FinalWireAddNote(builder: flatbuffers.Builder, note: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(note), 0)

def AddNote(builder: flatbuffers.Builder, note: int):
    FinalWireAddNote(builder, note)

def FinalWireAddMarks(builder: flatbuffers.Builder, marks: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(marks), 0)

def AddMarks(builder: flatbuffers.Builder, marks: int):
    FinalWireAddMarks(builder, marks)

def FinalWireStartMarksVector(builder, numElems: int) -> int:
    return builder.StartVector(12, numElems, 4)

def StartMarksVector(builder, numElems: int) -> int:
    return FinalWireStartMarksVector(builder, numElems)

def FinalWireEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FinalWireEnd(builder)

import mqt.scpd.flatbuffers.geometry.RCoord
try:
    from typing import List
except:
    pass

class FinalWireT(object):

    # FinalWireT
    def __init__(
        self,
        path = None,
        length = 0.0,
        verdict = 0,
        note = None,
        marks = None,
    ):
        self.path = path  # type: Optional[List[mqt.scpd.flatbuffers.geometry.RCoord.RCoordT]]
        self.length = length  # type: float
        self.verdict = verdict  # type: int
        self.note = note  # type: Optional[str]
        self.marks = marks  # type: Optional[List[mqt.scpd.flatbuffers.geometry.RCoord.RCoordT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        finalWire = FinalWire()
        finalWire.Init(buf, pos)
        return cls.InitFromObj(finalWire)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, finalWire):
        x = FinalWireT()
        x._UnPack(finalWire)
        return x

    # FinalWireT
    def _UnPack(self, finalWire):
        if finalWire is None:
            return
        if not finalWire.PathIsNone():
            self.path = []
            for i in range(finalWire.PathLength()):
                if finalWire.Path(i) is None:
                    self.path.append(None)
                else:
                    rCoord_ = mqt.scpd.flatbuffers.geometry.RCoord.RCoordT.InitFromObj(finalWire.Path(i))
                    self.path.append(rCoord_)
        self.length = finalWire.Length()
        self.verdict = finalWire.Verdict()
        self.note = finalWire.Note()
        if self.note is not None:
            self.note = self.note.decode('utf-8')
        if not finalWire.MarksIsNone():
            self.marks = []
            for i in range(finalWire.MarksLength()):
                if finalWire.Marks(i) is None:
                    self.marks.append(None)
                else:
                    rCoord_ = mqt.scpd.flatbuffers.geometry.RCoord.RCoordT.InitFromObj(finalWire.Marks(i))
                    self.marks.append(rCoord_)

    # FinalWireT
    def Pack(self, builder):
        if self.path is not None:
            FinalWireStartPathVector(builder, len(self.path))
            for i in reversed(range(len(self.path))):
                self.path[i].Pack(builder)
            path = builder.EndVector()
        if self.note is not None:
            note = builder.CreateString(self.note)
        if self.marks is not None:
            FinalWireStartMarksVector(builder, len(self.marks))
            for i in reversed(range(len(self.marks))):
                self.marks[i].Pack(builder)
            marks = builder.EndVector()
        FinalWireStart(builder)
        if self.path is not None:
            FinalWireAddPath(builder, path)
        FinalWireAddLength(builder, self.length)
        FinalWireAddVerdict(builder, self.verdict)
        if self.note is not None:
            FinalWireAddNote(builder, note)
        if self.marks is not None:
            FinalWireAddMarks(builder, marks)
        finalWire = FinalWireEnd(builder)
        return finalWire
