# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.artifacts.FinalWire import FinalWire
from mqt.scpd.flatbuffers.design.CpwCoupler import CpwCoupler
from typing import Optional
np = import_numpy()

# What the Final stage had drawn at the end of one of its phases.
#
# The stage runs five phases and each changes what the phase before it
# produced: the coupler insertion cuts a resonator back to its coupler, and
# the feedline passes re-route wires that are already drawn. A picture of one
# phase therefore cannot be derived from the end state, so each phase leaves
# its own snapshot here and the renderers draw the one they are asked for. A
# phase that has not been implemented yet carries no wires.
class FinalPhase(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FinalPhase()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFinalPhase(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FinalPhaseBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # FinalPhase
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # "inner", "outer", "couplers", "feedlines" or "refined".
    # FinalPhase
    def Name(self) -> Optional[str]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FinalPhase
    def Wires(self, j: int) -> Optional[FinalWire]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = FinalWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FinalPhase
    def WiresLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FinalPhase
    def WiresIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # FinalPhase
    def Inner(self, j: int) -> Optional[FinalWire]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = FinalWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FinalPhase
    def InnerLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FinalPhase
    def InnerIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # FinalPhase
    def Feedlines(self, j: int) -> Optional[FinalWire]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = FinalWire()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FinalPhase
    def FeedlinesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FinalPhase
    def FeedlinesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # FinalPhase
    def Couplers(self, j: int) -> Optional[CpwCoupler]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = CpwCoupler()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FinalPhase
    def CouplersLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FinalPhase
    def CouplersIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def FinalPhaseStart(builder: flatbuffers.Builder):
    builder.StartObject(5)

def Start(builder: flatbuffers.Builder):
    FinalPhaseStart(builder)

def FinalPhaseAddName(builder: flatbuffers.Builder, name: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder: flatbuffers.Builder, name: int):
    FinalPhaseAddName(builder, name)

def FinalPhaseAddWires(builder: flatbuffers.Builder, wires: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(wires), 0)

def AddWires(builder: flatbuffers.Builder, wires: int):
    FinalPhaseAddWires(builder, wires)

def FinalPhaseStartWiresVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartWiresVector(builder, numElems: int) -> int:
    return FinalPhaseStartWiresVector(builder, numElems)

def FinalPhaseAddInner(builder: flatbuffers.Builder, inner: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(inner), 0)

def AddInner(builder: flatbuffers.Builder, inner: int):
    FinalPhaseAddInner(builder, inner)

def FinalPhaseStartInnerVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartInnerVector(builder, numElems: int) -> int:
    return FinalPhaseStartInnerVector(builder, numElems)

def FinalPhaseAddFeedlines(builder: flatbuffers.Builder, feedlines: int):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(feedlines), 0)

def AddFeedlines(builder: flatbuffers.Builder, feedlines: int):
    FinalPhaseAddFeedlines(builder, feedlines)

def FinalPhaseStartFeedlinesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartFeedlinesVector(builder, numElems: int) -> int:
    return FinalPhaseStartFeedlinesVector(builder, numElems)

def FinalPhaseAddCouplers(builder: flatbuffers.Builder, couplers: int):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(couplers), 0)

def AddCouplers(builder: flatbuffers.Builder, couplers: int):
    FinalPhaseAddCouplers(builder, couplers)

def FinalPhaseStartCouplersVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartCouplersVector(builder, numElems: int) -> int:
    return FinalPhaseStartCouplersVector(builder, numElems)

def FinalPhaseEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FinalPhaseEnd(builder)

import mqt.scpd.flatbuffers.artifacts.FinalWire
import mqt.scpd.flatbuffers.design.CpwCoupler
try:
    from typing import List
except:
    pass

class FinalPhaseT(object):

    # FinalPhaseT
    def __init__(
        self,
        name = None,
        wires = None,
        inner = None,
        feedlines = None,
        couplers = None,
    ):
        self.name = name  # type: Optional[str]
        self.wires = wires  # type: Optional[List[mqt.scpd.flatbuffers.artifacts.FinalWire.FinalWireT]]
        self.inner = inner  # type: Optional[List[mqt.scpd.flatbuffers.artifacts.FinalWire.FinalWireT]]
        self.feedlines = feedlines  # type: Optional[List[mqt.scpd.flatbuffers.artifacts.FinalWire.FinalWireT]]
        self.couplers = couplers  # type: Optional[List[mqt.scpd.flatbuffers.design.CpwCoupler.CpwCouplerT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        finalPhase = FinalPhase()
        finalPhase.Init(buf, pos)
        return cls.InitFromObj(finalPhase)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, finalPhase):
        x = FinalPhaseT()
        x._UnPack(finalPhase)
        return x

    # FinalPhaseT
    def _UnPack(self, finalPhase):
        if finalPhase is None:
            return
        self.name = finalPhase.Name()
        if self.name is not None:
            self.name = self.name.decode('utf-8')
        if not finalPhase.WiresIsNone():
            self.wires = []
            for i in range(finalPhase.WiresLength()):
                if finalPhase.Wires(i) is None:
                    self.wires.append(None)
                else:
                    finalWire_ = mqt.scpd.flatbuffers.artifacts.FinalWire.FinalWireT.InitFromObj(finalPhase.Wires(i))
                    self.wires.append(finalWire_)
        if not finalPhase.InnerIsNone():
            self.inner = []
            for i in range(finalPhase.InnerLength()):
                if finalPhase.Inner(i) is None:
                    self.inner.append(None)
                else:
                    finalWire_ = mqt.scpd.flatbuffers.artifacts.FinalWire.FinalWireT.InitFromObj(finalPhase.Inner(i))
                    self.inner.append(finalWire_)
        if not finalPhase.FeedlinesIsNone():
            self.feedlines = []
            for i in range(finalPhase.FeedlinesLength()):
                if finalPhase.Feedlines(i) is None:
                    self.feedlines.append(None)
                else:
                    finalWire_ = mqt.scpd.flatbuffers.artifacts.FinalWire.FinalWireT.InitFromObj(finalPhase.Feedlines(i))
                    self.feedlines.append(finalWire_)
        if not finalPhase.CouplersIsNone():
            self.couplers = []
            for i in range(finalPhase.CouplersLength()):
                if finalPhase.Couplers(i) is None:
                    self.couplers.append(None)
                else:
                    cpwCoupler_ = mqt.scpd.flatbuffers.design.CpwCoupler.CpwCouplerT.InitFromObj(finalPhase.Couplers(i))
                    self.couplers.append(cpwCoupler_)

    # FinalPhaseT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.wires is not None:
            wireslist = []
            for i in range(len(self.wires)):
                wireslist.append(self.wires[i].Pack(builder))
            FinalPhaseStartWiresVector(builder, len(self.wires))
            for i in reversed(range(len(self.wires))):
                builder.PrependUOffsetTRelative(wireslist[i])
            wires = builder.EndVector()
        if self.inner is not None:
            innerlist = []
            for i in range(len(self.inner)):
                innerlist.append(self.inner[i].Pack(builder))
            FinalPhaseStartInnerVector(builder, len(self.inner))
            for i in reversed(range(len(self.inner))):
                builder.PrependUOffsetTRelative(innerlist[i])
            inner = builder.EndVector()
        if self.feedlines is not None:
            feedlineslist = []
            for i in range(len(self.feedlines)):
                feedlineslist.append(self.feedlines[i].Pack(builder))
            FinalPhaseStartFeedlinesVector(builder, len(self.feedlines))
            for i in reversed(range(len(self.feedlines))):
                builder.PrependUOffsetTRelative(feedlineslist[i])
            feedlines = builder.EndVector()
        if self.couplers is not None:
            couplerslist = []
            for i in range(len(self.couplers)):
                couplerslist.append(self.couplers[i].Pack(builder))
            FinalPhaseStartCouplersVector(builder, len(self.couplers))
            for i in reversed(range(len(self.couplers))):
                builder.PrependUOffsetTRelative(couplerslist[i])
            couplers = builder.EndVector()
        FinalPhaseStart(builder)
        if self.name is not None:
            FinalPhaseAddName(builder, name)
        if self.wires is not None:
            FinalPhaseAddWires(builder, wires)
        if self.inner is not None:
            FinalPhaseAddInner(builder, inner)
        if self.feedlines is not None:
            FinalPhaseAddFeedlines(builder, feedlines)
        if self.couplers is not None:
            FinalPhaseAddCouplers(builder, couplers)
        finalPhase = FinalPhaseEnd(builder)
        return finalPhase
