# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

# The verdicts the Final stage holds against one wire at its end, as bit
# flags: a wire can be open and off its length at once. Counted by the
# stage's own test, the one its last log line reports, with every wire down.
class FinalVerdict(object):
    # The wire has no way of its own: still on its seed, or not on the grid.
    Unrouted = 1
    # Its way comes within the wire clearance of another wire.
    Open = 2
    # It crosses a feedline edge other than at a right angle, or enters the
    # room around a feedline's bend.
    Crossing = 4
    # A resonator shorter than its target length allows.
    Short = 8
    # A resonator longer than its target length allows.
    Long = 16
    # Its way crosses or touches itself.
    Loop = 32
