# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.design.Bridge import Bridge
from mqt.scpd.flatbuffers.design.ConnectionRef import ConnectionRef
from mqt.scpd.flatbuffers.design.CpwCoupler import CpwCoupler
from typing import Optional
np = import_numpy()

# Output of the Final stage. The couplers carry the ports they create and
# the connections they complete, so a reloaded run can rebuild the grown
# port list and the completed connections without the stage.
class FinalRouting(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FinalRouting()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFinalRouting(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FinalRoutingBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # FinalRouting
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FinalRouting
    def Couplers(self, j: int) -> Optional[CpwCoupler]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = CpwCoupler()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FinalRouting
    def CouplersLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FinalRouting
    def CouplersIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # FinalRouting
    def Bridges(self, j: int) -> Optional[Bridge]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Bridge()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FinalRouting
    def BridgesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FinalRouting
    def BridgesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # The connections that did not route.
    # FinalRouting
    def Unresolved(self, j: int) -> Optional[ConnectionRef]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            obj = ConnectionRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # FinalRouting
    def UnresolvedLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # FinalRouting
    def UnresolvedIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def FinalRoutingStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    FinalRoutingStart(builder)

def FinalRoutingAddCouplers(builder: flatbuffers.Builder, couplers: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(couplers), 0)

def AddCouplers(builder: flatbuffers.Builder, couplers: int):
    FinalRoutingAddCouplers(builder, couplers)

def FinalRoutingStartCouplersVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartCouplersVector(builder, numElems: int) -> int:
    return FinalRoutingStartCouplersVector(builder, numElems)

def FinalRoutingAddBridges(builder: flatbuffers.Builder, bridges: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(bridges), 0)

def AddBridges(builder: flatbuffers.Builder, bridges: int):
    FinalRoutingAddBridges(builder, bridges)

def FinalRoutingStartBridgesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartBridgesVector(builder, numElems: int) -> int:
    return FinalRoutingStartBridgesVector(builder, numElems)

def FinalRoutingAddUnresolved(builder: flatbuffers.Builder, unresolved: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(unresolved), 0)

def AddUnresolved(builder: flatbuffers.Builder, unresolved: int):
    FinalRoutingAddUnresolved(builder, unresolved)

def FinalRoutingStartUnresolvedVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartUnresolvedVector(builder, numElems: int) -> int:
    return FinalRoutingStartUnresolvedVector(builder, numElems)

def FinalRoutingEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return FinalRoutingEnd(builder)

import mqt.scpd.flatbuffers.design.Bridge
import mqt.scpd.flatbuffers.design.ConnectionRef
import mqt.scpd.flatbuffers.design.CpwCoupler
try:
    from typing import List
except:
    pass

class FinalRoutingT(object):

    # FinalRoutingT
    def __init__(
        self,
        couplers = None,
        bridges = None,
        unresolved = None,
    ):
        self.couplers = couplers  # type: Optional[List[mqt.scpd.flatbuffers.design.CpwCoupler.CpwCouplerT]]
        self.bridges = bridges  # type: Optional[List[mqt.scpd.flatbuffers.design.Bridge.BridgeT]]
        self.unresolved = unresolved  # type: Optional[List[mqt.scpd.flatbuffers.design.ConnectionRef.ConnectionRefT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        finalRouting = FinalRouting()
        finalRouting.Init(buf, pos)
        return cls.InitFromObj(finalRouting)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, finalRouting):
        x = FinalRoutingT()
        x._UnPack(finalRouting)
        return x

    # FinalRoutingT
    def _UnPack(self, finalRouting):
        if finalRouting is None:
            return
        if not finalRouting.CouplersIsNone():
            self.couplers = []
            for i in range(finalRouting.CouplersLength()):
                if finalRouting.Couplers(i) is None:
                    self.couplers.append(None)
                else:
                    cpwCoupler_ = mqt.scpd.flatbuffers.design.CpwCoupler.CpwCouplerT.InitFromObj(finalRouting.Couplers(i))
                    self.couplers.append(cpwCoupler_)
        if not finalRouting.BridgesIsNone():
            self.bridges = []
            for i in range(finalRouting.BridgesLength()):
                if finalRouting.Bridges(i) is None:
                    self.bridges.append(None)
                else:
                    bridge_ = mqt.scpd.flatbuffers.design.Bridge.BridgeT.InitFromObj(finalRouting.Bridges(i))
                    self.bridges.append(bridge_)
        if not finalRouting.UnresolvedIsNone():
            self.unresolved = []
            for i in range(finalRouting.UnresolvedLength()):
                if finalRouting.Unresolved(i) is None:
                    self.unresolved.append(None)
                else:
                    connectionRef_ = mqt.scpd.flatbuffers.design.ConnectionRef.ConnectionRefT.InitFromObj(finalRouting.Unresolved(i))
                    self.unresolved.append(connectionRef_)

    # FinalRoutingT
    def Pack(self, builder):
        if self.couplers is not None:
            couplerslist = []
            for i in range(len(self.couplers)):
                couplerslist.append(self.couplers[i].Pack(builder))
            FinalRoutingStartCouplersVector(builder, len(self.couplers))
            for i in reversed(range(len(self.couplers))):
                builder.PrependUOffsetTRelative(couplerslist[i])
            couplers = builder.EndVector()
        if self.bridges is not None:
            bridgeslist = []
            for i in range(len(self.bridges)):
                bridgeslist.append(self.bridges[i].Pack(builder))
            FinalRoutingStartBridgesVector(builder, len(self.bridges))
            for i in reversed(range(len(self.bridges))):
                builder.PrependUOffsetTRelative(bridgeslist[i])
            bridges = builder.EndVector()
        if self.unresolved is not None:
            FinalRoutingStartUnresolvedVector(builder, len(self.unresolved))
            for i in reversed(range(len(self.unresolved))):
                self.unresolved[i].Pack(builder)
            unresolved = builder.EndVector()
        FinalRoutingStart(builder)
        if self.couplers is not None:
            FinalRoutingAddCouplers(builder, couplers)
        if self.bridges is not None:
            FinalRoutingAddBridges(builder, bridges)
        if self.unresolved is not None:
            FinalRoutingAddUnresolved(builder, unresolved)
        finalRouting = FinalRoutingEnd(builder)
        return finalRouting
