# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.geometry.Point import Point
from typing import Optional
np = import_numpy()

# One lattice the inner circuit is solved on: the Hanan grid that the ports
# of one capacity chain induce.
class Lattice(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Lattice()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLattice(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def LatticeBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # Lattice
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Lattice
    def Points(self, j: int) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Lattice
    def PointsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Lattice
    def PointsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Two point indices per edge, flat.
    # Lattice
    def Edges(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Lattice
    def EdgesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Lattice
    def EdgesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Lattice
    def EdgesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # The edges the solution selected, as indices into `edges` divided by two.
    # Lattice
    def Selected(self, j: int):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Lattice
    def SelectedAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Lattice
    def SelectedLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Lattice
    def SelectedIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def LatticeStart(builder: flatbuffers.Builder):
    builder.StartObject(3)

def Start(builder: flatbuffers.Builder):
    LatticeStart(builder)

def LatticeAddPoints(builder: flatbuffers.Builder, points: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)

def AddPoints(builder: flatbuffers.Builder, points: int):
    LatticeAddPoints(builder, points)

def LatticeStartPointsVector(builder, numElems: int) -> int:
    return builder.StartVector(16, numElems, 8)

def StartPointsVector(builder, numElems: int) -> int:
    return LatticeStartPointsVector(builder, numElems)

def LatticeAddEdges(builder: flatbuffers.Builder, edges: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(edges), 0)

def AddEdges(builder: flatbuffers.Builder, edges: int):
    LatticeAddEdges(builder, edges)

def LatticeStartEdgesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartEdgesVector(builder, numElems: int) -> int:
    return LatticeStartEdgesVector(builder, numElems)

def LatticeAddSelected(builder: flatbuffers.Builder, selected: int):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(selected), 0)

def AddSelected(builder: flatbuffers.Builder, selected: int):
    LatticeAddSelected(builder, selected)

def LatticeStartSelectedVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartSelectedVector(builder, numElems: int) -> int:
    return LatticeStartSelectedVector(builder, numElems)

def LatticeEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return LatticeEnd(builder)

import mqt.scpd.flatbuffers.geometry.Point
try:
    from typing import List
except:
    pass

class LatticeT(object):

    # LatticeT
    def __init__(
        self,
        points = None,
        edges = None,
        selected = None,
    ):
        self.points = points  # type: Optional[List[mqt.scpd.flatbuffers.geometry.Point.PointT]]
        self.edges = edges  # type: Optional[List[int]]
        self.selected = selected  # type: Optional[List[int]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        lattice = Lattice()
        lattice.Init(buf, pos)
        return cls.InitFromObj(lattice)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, lattice):
        x = LatticeT()
        x._UnPack(lattice)
        return x

    # LatticeT
    def _UnPack(self, lattice):
        if lattice is None:
            return
        if not lattice.PointsIsNone():
            self.points = []
            for i in range(lattice.PointsLength()):
                if lattice.Points(i) is None:
                    self.points.append(None)
                else:
                    point_ = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(lattice.Points(i))
                    self.points.append(point_)
        if not lattice.EdgesIsNone():
            if np is None:
                self.edges = []
                for i in range(lattice.EdgesLength()):
                    self.edges.append(lattice.Edges(i))
            else:
                self.edges = lattice.EdgesAsNumpy()
        if not lattice.SelectedIsNone():
            if np is None:
                self.selected = []
                for i in range(lattice.SelectedLength()):
                    self.selected.append(lattice.Selected(i))
            else:
                self.selected = lattice.SelectedAsNumpy()

    # LatticeT
    def Pack(self, builder):
        if self.points is not None:
            LatticeStartPointsVector(builder, len(self.points))
            for i in reversed(range(len(self.points))):
                self.points[i].Pack(builder)
            points = builder.EndVector()
        if self.edges is not None:
            if np is not None and type(self.edges) is np.ndarray:
                edges = builder.CreateNumpyVector(self.edges)
            else:
                LatticeStartEdgesVector(builder, len(self.edges))
                for i in reversed(range(len(self.edges))):
                    builder.PrependUint32(self.edges[i])
                edges = builder.EndVector()
        if self.selected is not None:
            if np is not None and type(self.selected) is np.ndarray:
                selected = builder.CreateNumpyVector(self.selected)
            else:
                LatticeStartSelectedVector(builder, len(self.selected))
                for i in reversed(range(len(self.selected))):
                    builder.PrependUint32(self.selected[i])
                selected = builder.EndVector()
        LatticeStart(builder)
        if self.points is not None:
            LatticeAddPoints(builder, points)
        if self.edges is not None:
            LatticeAddEdges(builder, edges)
        if self.selected is not None:
            LatticeAddSelected(builder, selected)
        lattice = LatticeEnd(builder)
        return lattice
