# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.geometry.Polygon import Polygon
from typing import Optional
np = import_numpy()

# One partition of the free space, as the watershed left it.
class Partition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Partition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPartition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def PartitionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # Partition
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Partition
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Closed rings in layout units. More than one where the partition has a
    # hole, or the watershed left it in pieces.
    # Partition
    def Outlines(self, j: int) -> Optional[Polygon]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Polygon()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Partition
    def OutlinesLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Partition
    def OutlinesIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def PartitionStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    PartitionStart(builder)

def PartitionAddLabel(builder: flatbuffers.Builder, label: int):
    builder.PrependUint32Slot(0, label, 0)

def AddLabel(builder: flatbuffers.Builder, label: int):
    PartitionAddLabel(builder, label)

def PartitionAddOutlines(builder: flatbuffers.Builder, outlines: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(outlines), 0)

def AddOutlines(builder: flatbuffers.Builder, outlines: int):
    PartitionAddOutlines(builder, outlines)

def PartitionStartOutlinesVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartOutlinesVector(builder, numElems: int) -> int:
    return PartitionStartOutlinesVector(builder, numElems)

def PartitionEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return PartitionEnd(builder)

import mqt.scpd.flatbuffers.geometry.Polygon
try:
    from typing import List
except:
    pass

class PartitionT(object):

    # PartitionT
    def __init__(
        self,
        label = 0,
        outlines = None,
    ):
        self.label = label  # type: int
        self.outlines = outlines  # type: Optional[List[mqt.scpd.flatbuffers.geometry.Polygon.PolygonT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        partition = Partition()
        partition.Init(buf, pos)
        return cls.InitFromObj(partition)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, partition):
        x = PartitionT()
        x._UnPack(partition)
        return x

    # PartitionT
    def _UnPack(self, partition):
        if partition is None:
            return
        self.label = partition.Label()
        if not partition.OutlinesIsNone():
            self.outlines = []
            for i in range(partition.OutlinesLength()):
                if partition.Outlines(i) is None:
                    self.outlines.append(None)
                else:
                    polygon_ = mqt.scpd.flatbuffers.geometry.Polygon.PolygonT.InitFromObj(partition.Outlines(i))
                    self.outlines.append(polygon_)

    # PartitionT
    def Pack(self, builder):
        if self.outlines is not None:
            outlineslist = []
            for i in range(len(self.outlines)):
                outlineslist.append(self.outlines[i].Pack(builder))
            PartitionStartOutlinesVector(builder, len(self.outlines))
            for i in reversed(range(len(self.outlines))):
                builder.PrependUOffsetTRelative(outlineslist[i])
            outlines = builder.EndVector()
        PartitionStart(builder)
        PartitionAddLabel(builder, self.label)
        if self.outlines is not None:
            PartitionAddOutlines(builder, outlines)
        partition = PartitionEnd(builder)
        return partition
