# automatically generated by the FlatBuffers compiler, do not modify

# namespace: artifacts

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.design.ConnectionRef import ConnectionRef
from mqt.scpd.flatbuffers.geometry.Path import Path
from typing import Optional
np = import_numpy()

# One connection's wire in its exact analytic form.
class Wire(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Wire()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWire(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def WireBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x53\x43\x50\x31", size_prefixed=size_prefixed)

    # Wire
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Wire
    def Connection(self) -> Optional[ConnectionRef]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = ConnectionRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Wire
    def Path(self) -> Optional[Path]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = Path()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WireStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    WireStart(builder)

def WireAddConnection(builder: flatbuffers.Builder, connection: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(connection), 0)

def AddConnection(builder: flatbuffers.Builder, connection: Any):
    WireAddConnection(builder, connection)

def WireAddPath(builder: flatbuffers.Builder, path: int):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)

def AddPath(builder: flatbuffers.Builder, path: int):
    WireAddPath(builder, path)

def WireEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return WireEnd(builder)

import mqt.scpd.flatbuffers.design.ConnectionRef
import mqt.scpd.flatbuffers.geometry.Path
try:
    from typing import Optional
except:
    pass

class WireT(object):

    # WireT
    def __init__(
        self,
        connection = None,
        path = None,
    ):
        self.connection = connection  # type: Optional[mqt.scpd.flatbuffers.design.ConnectionRef.ConnectionRefT]
        self.path = path  # type: Optional[mqt.scpd.flatbuffers.geometry.Path.PathT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        wire = Wire()
        wire.Init(buf, pos)
        return cls.InitFromObj(wire)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, wire):
        x = WireT()
        x._UnPack(wire)
        return x

    # WireT
    def _UnPack(self, wire):
        if wire is None:
            return
        if wire.Connection() is not None:
            self.connection = mqt.scpd.flatbuffers.design.ConnectionRef.ConnectionRefT.InitFromObj(wire.Connection())
        if wire.Path() is not None:
            self.path = mqt.scpd.flatbuffers.geometry.Path.PathT.InitFromObj(wire.Path())

    # WireT
    def Pack(self, builder):
        if self.path is not None:
            path = self.path.Pack(builder)
        WireStart(builder)
        if self.connection is not None:
            connection = self.connection.Pack(builder)
            WireAddConnection(builder, connection)
        if self.path is not None:
            WireAddPath(builder, path)
        wire = WireEnd(builder)
        return wire
