# automatically generated by the FlatBuffers compiler, do not modify

# namespace: geometry

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from mqt.scpd.flatbuffers.geometry.Point import Point
from typing import Optional
np = import_numpy()

# A straight segment in layout space.
class Line(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Line()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLine(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Line
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Line
    def Start(self) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Line
    def End(self) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def LineStart(builder: flatbuffers.Builder):
    builder.StartObject(2)

def Start(builder: flatbuffers.Builder):
    LineStart(builder)

def LineAddStart(builder: flatbuffers.Builder, start: Any):
    builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(start), 0)

def AddStart(builder: flatbuffers.Builder, start: Any):
    LineAddStart(builder, start)

def LineAddEnd(builder: flatbuffers.Builder, end: Any):
    builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(end), 0)

def AddEnd(builder: flatbuffers.Builder, end: Any):
    LineAddEnd(builder, end)

def LineEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return LineEnd(builder)

import mqt.scpd.flatbuffers.geometry.Point
try:
    from typing import Optional
except:
    pass

class LineT(object):

    # LineT
    def __init__(
        self,
        start = None,
        end = None,
    ):
        self.start = start  # type: Optional[mqt.scpd.flatbuffers.geometry.Point.PointT]
        self.end = end  # type: Optional[mqt.scpd.flatbuffers.geometry.Point.PointT]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        line = Line()
        line.Init(buf, pos)
        return cls.InitFromObj(line)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, line):
        x = LineT()
        x._UnPack(line)
        return x

    # LineT
    def _UnPack(self, line):
        if line is None:
            return
        if line.Start() is not None:
            self.start = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(line.Start())
        if line.End() is not None:
            self.end = mqt.scpd.flatbuffers.geometry.Point.PointT.InitFromObj(line.End())

    # LineT
    def Pack(self, builder):
        LineStart(builder)
        if self.start is not None:
            start = self.start.Pack(builder)
            LineAddStart(builder, start)
        if self.end is not None:
            end = self.end.Pack(builder)
            LineAddEnd(builder, end)
        line = LineEnd(builder)
        return line
