# automatically generated by the FlatBuffers compiler, do not modify

# namespace: geometry

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
np = import_numpy()

# A state of the router grid: a cell of the final grid and the eight-way
# heading 0..7 of the wire in it. A wire leaves a heading-0 state toward
# negative y, and the headings continue clockwise in eighth turns when y
# points up: heading 2 travels toward negative x, heading 4 toward positive
# y, heading 6 toward positive x.
class RCoord(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls) -> int:
        return 12

    # RCoord
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RCoord
    def X(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # RCoord
    def Y(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # RCoord
    def Heading(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateRcoord(builder, x, y, heading):
    builder.Prep(4, 12)
    builder.Pad(3)
    builder.PrependUint8(heading)
    builder.PrependUint32(y)
    builder.PrependUint32(x)
    return builder.Offset()


class RCoordT(object):

    # RCoordT
    def __init__(
        self,
        x = 0,
        y = 0,
        heading = 0,
    ):
        self.x = x  # type: int
        self.y = y  # type: int
        self.heading = heading  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        rcoord = RCoord()
        rcoord.Init(buf, pos)
        return cls.InitFromObj(rcoord)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, rcoord):
        x = RCoordT()
        x._UnPack(rcoord)
        return x

    # RCoordT
    def _UnPack(self, rcoord):
        if rcoord is None:
            return
        self.x = rcoord.X()
        self.y = rcoord.Y()
        self.heading = rcoord.Heading()

    # RCoordT
    def Pack(self, builder):
        return CreateRcoord(builder, self.x, self.y, self.heading)
