# automatically generated by the FlatBuffers compiler, do not modify

# namespace: geometry

# The two analytic shapes a routed wire consists of.
class SegmentShape(object):
    NONE = 0
    Line = 1
    Arc = 2

def SegmentShapeCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == SegmentShape.Line:
        import mqt.scpd.flatbuffers.geometry.Line
        return mqt.scpd.flatbuffers.geometry.Line.LineT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == SegmentShape.Arc:
        import mqt.scpd.flatbuffers.geometry.Arc
        return mqt.scpd.flatbuffers.geometry.Arc.ArcT.InitFromBuf(table.Bytes, table.Pos)
    return None
